import { PageData } from '../../types';
import { cleanParagraphs } from '../dataUtils';

const CHAPTER_2_TITLE = "Chương 2: Doanh nghiệp và Chiến lược Marketing – Hợp tác để Thu hút Khách hàng, Tạo Giá trị và Xây dựng Quan hệ";

export const chap2SecIPageData: PageData = {
  id: 'chap2-secI',
  chapterTitle: CHAPTER_2_TITLE,
  pageTitle: "I. Hoạch định Chiến lược Toàn Công ty: Xác định Vai trò của Marketing",
  paragraphs: cleanParagraphs([
    "Nhiều công ty lớn thường bao gồm nhiều đơn vị kinh doanh nhỏ hơn. Ví dụ, Disney không chỉ vận hành các công viên giải trí mà còn sở hữu các hãng phim (bao gồm Walt Disney Pictures, Twentieth Century Studios, Marvel Studios, Lucasfilm, Pixar), các mạng truyền hình (ABC, ESPN, Disney Channel, FX, National Geographic), và các dòng sản phẩm tiêu dùng. Ban lãnh đạo công ty cần phải hoạch định chiến lược cho toàn bộ tập đoàn.",
    "Hoạch định chiến lược là <span class=\"text-rose-600\"><strong>quy trình phát triển và duy trì sự phù hợp mang tính chiến lược giữa các mục tiêu và năng lực của tổ chức với những cơ hội marketing luôn thay đổi.</strong></span> Hoạch định chiến lược đặt nền tảng cho mọi kế hoạch khác trong công ty.",
    "Ở cấp độ doanh nghiệp, quy trình hoạch định chiến lược bắt đầu bằng việc xác định mục đích và sứ mệnh tổng thể của công ty (xem Hình 2.1). Sứ mệnh này sau đó được chuyển thành các mục tiêu hỗ trợ chi tiết, định hướng cho toàn bộ công ty. Tiếp theo, ban lãnh đạo quyết định danh mục các hoạt động kinh doanh và sản phẩm nào là tốt nhất cho công ty và cần nhận được bao nhiêu sự hỗ trợ. Đổi lại, mỗi đơn vị kinh doanh và sản phẩm phải phát triển các kế hoạch marketing và các phòng ban chi tiết hơn để hỗ trợ kế hoạch toàn công ty. Do đó, các kế hoạch marketing ở cấp độ đơn vị kinh doanh, sản phẩm và thị trường hoạt động trong một khuôn khổ rộng hơn của các kế hoạch bắt đầu ở cấp độ doanh nghiệp.",
    "<strong>Hình 2.1 | Các bước trong Hoạch định Chiến lược</strong>",
    "<span class=\"text-xs text-slate-600\">Hoạch định chiến lược đặt nền móng cho phần còn lại của việc lập kế hoạch trong công ty. Các công ty thường chuẩn bị kế hoạch hàng năm, kế hoạch dài hạn và kế hoạch chiến lược. Kế hoạch hàng năm và kế hoạch dài hạn giải quyết các hoạt động kinh doanh hiện tại của công ty và cách duy trì chúng. Ngược lại, kế hoạch chiến lược liên quan đến việc thích ứng công ty để tận dụng các cơ hội trong môi trường luôn thay đổi của nó.</span>",
    "<strong>A. Xác định Sứ mệnh Định hướng Thị trường</strong>",
    "Một tổ chức tồn tại để hoàn thành một điều gì đó. Ban đầu, nó có thể có các kế hoạch, chính sách và mục tiêu rõ ràng. Tuy nhiên, theo thời gian, khi tổ chức phát triển và các sản phẩm và thị trường mới được thêm vào, tổ chức có thể đi chệch hướng. Hoặc các mục tiêu có thể vẫn rõ ràng nhưng không còn phù hợp với các điều kiện môi trường đang thay đổi. Khi điều đó xảy ra, tổ chức phải làm mới mình bằng cách quay trở lại những điều cơ bản. Ban lãnh đạo phải tự hỏi: <em>Ngành nghề kinh doanh của chúng ta là gì? Khách hàng của chúng ta là ai? Người tiêu dùng của chúng ta coi trọng điều gì? Ngành nghề kinh doanh của chúng ta nên là gì?</em>",
    "Những câu hỏi tưởng chừng đơn giản này lại là những câu hỏi khó nhất mà công ty sẽ phải trả lời. Nhiều tổ chức phát triển các tuyên bố sứ mệnh chính thức để trả lời những câu hỏi này. <span class=\"text-rose-600\"><strong>Tuyên ngôn sứ mệnh (mission statement)</strong></span> là một tuyên bố về mục đích của tổ chức—những gì nó muốn đạt được trong môi trường rộng lớn hơn. Một tuyên ngôn sứ mệnh rõ ràng đóng vai trò như một \"bàn tay vô hình\" hướng dẫn mọi người trong tổ chức.",
    "Một số công ty xác định sứ mệnh của mình theo thuật ngữ sản phẩm hoặc công nghệ (\"Chúng tôi sản xuất và bán đồ nội thất\" hoặc \"Chúng tôi là một công ty xử lý hóa chất\"). Tuy nhiên, các tuyên ngôn sứ mệnh nên <span class=\"text-rose-600\"><strong>định hướng thị trường (market-oriented)</strong></span> và được xác định theo việc thỏa mãn nhu cầu cơ bản của khách hàng. Ví dụ, Chipotle không xác định mình là một chuỗi nhà hàng bán burrito. Sứ mệnh của họ là cung cấp \"thực phẩm có lương tâm\"—những nguyên liệu tươi ngon được chế biến theo phương pháp nấu ăn cổ điển và phục vụ trong một môi trường tương tác đặc biệt. Nhà cung cấp dịch vụ chăm sóc sức khỏe CVS Health không chỉ đơn thuần là một chuỗi nhà thuốc lớn. Sứ mệnh của họ là \"giúp mọi người trên con đường nâng cao sức khỏe\" của họ. Và sứ mệnh của Facebook không phải là \"một nơi để mọi người đăng ảnh và video trực tuyến\". Thay vào đó, sứ mệnh của họ là \"mang đến cho mọi người sức mạnh để xây dựng cộng đồng và đưa thế giới đến gần nhau hơn\".",
    "Các sản phẩm và công nghệ cuối cùng sẽ lỗi thời, nhưng các nhu cầu cơ bản của thị trường có thể tồn tại mãi mãi. Ví dụ, nếu nhà sản xuất bút chì nổi tiếng Faber-Castell xác định sứ mệnh của mình là \"Chúng tôi sản xuất bút chì\", thì họ có thể bị phá sản bởi các công cụ viết khác hoặc giao tiếp kỹ thuật số. Nhưng sứ mệnh của Faber-Castell là \"khơi gợi sự sáng tạo và truyền cảm hứng cho sự thể hiện bản thân ở mọi lứa tuổi\". Sứ mệnh này bao gồm một loạt các sản phẩm và dịch vụ vượt xa những chiếc bút chì đơn thuần. Bảng 2.1 cung cấp một số ví dụ về các tuyên ngôn sứ mệnh định hướng sản phẩm so với định hướng thị trường.",
    "<strong>Bảng 2.1 | Các Tuyên ngôn Sứ mệnh Định hướng Thị trường</strong>",
    "<em>Công ty: Pinterest</em>",
    "Định hướng Sản phẩm: Chúng tôi điều hành một trang web ghim ảnh.",
    "Định hướng Thị trường: Chúng tôi mang đến cho mọi người một nền tảng mạng xã hội để thu thập, sắp xếp và chia sẻ những thứ mà họ thích.",
    "<em>Công ty: Instagram</em>",
    "Định hướng Sản phẩm: Chúng tôi là một ứng dụng chia sẻ ảnh và video trên thiết bị di động.",
    "Định hướng Thị trường: Chúng tôi giúp mọi người ghi lại và chia sẻ những khoảnh khắc trong cuộc sống khi chúng diễn ra.",
    "<em>Công ty: Home Depot</em>",
    "Định hướng Sản phẩm: Chúng tôi bán công cụ và vật tư sửa chữa nhà cửa.",
    "Định hướng Thị trường: Chúng tôi trao quyền cho người tiêu dùng đạt được ngôi nhà mơ ước của họ.",
    "<em>Công ty: NASA</em>",
    "Định hướng Sản phẩm: Chúng tôi khám phá không gian bên ngoài.",
    "Định hướng Thị trường: Chúng tôi vươn tới những tầm cao mới và khám phá những điều chưa biết để những gì chúng tôi làm và học hỏi sẽ mang lại lợi ích cho toàn nhân loại.",
    "<em>Công ty: Starbucks</em>",
    "Định hướng Sản phẩm: Chúng tôi bán cà phê và đồ ăn nhẹ.",
    "Định hướng Thị trường: Chúng tôi truyền cảm hứng và nuôi dưỡng tinh thần con người—một người, một tách cà phê và một khu phố tại một thời điểm.",
    "Sứ mệnh nên <span class=\"text-rose-600\"><em>có ý nghĩa</em></span> và <span class=\"text-rose-600\"><em>cụ thể</em></span> nhưng <span class=\"text-rose-600\"><em>mang tính thúc đẩy</em></span>. Chúng nên nhấn mạnh điểm mạnh của công ty trên thị trường. Trong nhiều thập kỷ, sứ mệnh của Walmart là \"Chúng tôi bán lẻ với giá thấp hơn\". Sứ mệnh này đã cung cấp một định hướng rõ ràng, nhưng bị hạn chế. \"Chúng tôi giúp mọi người trên toàn thế giới tiết kiệm tiền và sống tốt hơn—mọi lúc, mọi nơi,\" tuyên bố của Walmart hiện nay, rộng hơn và phù hợp hơn. Nó định vị Walmart như một \"tác nhân vì mục đích tốt đẹp\" vượt ra ngoài \"tiền bạc\" và \"bán lẻ\". Quan trọng nhất, sứ mệnh của Walmart nên tập trung vào khách hàng và trải nghiệm khách hàng mà công ty tìm cách tạo ra.",
    "<strong>B. Thiết lập Mục tiêu và Mục đích của Công ty</strong>",
    "Sứ mệnh của công ty cần được chuyển hóa thành các mục tiêu hỗ trợ chi tiết cho từng cấp quản lý. Mỗi nhà quản lý nên có mục tiêu và chịu trách nhiệm đạt được chúng.",
    "Ví dụ, sứ mệnh rộng lớn của CVS Health là \"giúp mọi người trên con đường nâng cao sức khỏe\" của họ. CVS Health có một hệ thống các mục tiêu kinh doanh như tăng cường khả năng tiếp cận, giảm chi phí và cải thiện chất lượng chăm sóc sức khỏe. Và nó có các mục tiêu marketing như cải thiện mối quan hệ khách hàng và nâng cao thị phần. Marketing tạo ra giá trị cho khách hàng và xây dựng mối quan hệ khách hàng để giúp đạt được những mục tiêu này.",
    "Để minh họa, khi CVS Health quyết định ngừng bán các sản phẩm thuốc lá, họ đã mất khoảng 2 tỷ đô la doanh thu thuốc lá hàng năm. Nhưng CVS Health đã bù đắp một phần khoản lỗ đó bằng cách mở rộng các dịch vụ chăm sóc sức khỏe khác, bao gồm cả các phòng khám MinuteClinic của mình. Quyết định táo bạo của CVS Health nhằm ưu tiên sức khỏe của khách hàng thay vì doanh số bán thuốc lá đã nâng cao đáng kể danh tiếng của công ty với tư cách là một nhà cung cấp dịch vụ chăm sóc sức khỏe và thúc đẩy các mối quan hệ khách hàng có lợi nhuận. Do đó, các chiến lược và chương trình marketing phải được phát triển để hỗ trợ các mục tiêu marketing này. Ví dụ, để tăng cường khả năng tiếp cận các dịch vụ chăm sóc sức khỏe, CVS Health có thể mở rộng các phòng khám MinuteClinic và triển khai các chiến dịch marketing để quảng bá các dịch vụ này."
  ]),
};