import { PageData } from '../../types';
import { cleanParagraphs } from '../dataUtils';

const CHAPTER_2_TITLE = "Chương 2: Doanh nghiệp và Chiến lược Marketing – Hợp tác để Thu hút Khách hàng, Tạo Giá trị và Xây dựng Quan hệ";

export const chap2SecIIPageData: PageData = {
  id: 'chap2-secII',
  chapterTitle: CHAPTER_2_TITLE,
  pageTitle: "II. Thiết lập Danh mục Kinh doanh",
  paragraphs: cleanParagraphs([
    "Được định hướng bởi tuyên ngôn sứ mệnh và các mục tiêu của công ty, ban lãnh đạo giờ đây phải lập kế hoạch cho <span class=\"text-rose-600\"><strong>danh mục kinh doanh (business portfolio)</strong></span> của mình—tập hợp các hoạt động kinh doanh và sản phẩm tạo nên công ty. Danh mục kinh doanh tốt nhất là danh mục phù hợp nhất với điểm mạnh và điểm yếu của công ty trước các cơ hội của môi trường.",
    "Hoạch định danh mục kinh doanh bao gồm hai bước. Đầu tiên, công ty phải phân tích danh mục kinh doanh hiện tại của mình và xác định hoạt động kinh doanh nào nên nhận được nhiều hơn, ít hơn hoặc không đầu tư nữa. Thứ hai, công ty phải định hình danh mục tương lai bằng cách phát triển các chiến lược tăng trưởng và cắt giảm.",
    "<strong>A. Phân tích Danh mục Kinh doanh Hiện tại</strong>",
    "Hoạt động chính trong hoạch định chiến lược là <span class=\"text-rose-600\"><strong>phân tích danh mục kinh doanh (business portfolio analysis)</strong></span>, qua đó ban quản trị đánh giá các sản phẩm và hoạt động kinh doanh tạo nên công ty. Công ty sẽ muốn đầu tư nhiều nguồn lực hơn vào các hoạt động kinh doanh sinh lợi hơn và cắt giảm hoặc loại bỏ các hoạt động yếu kém hơn.",
    "Bước đầu tiên của ban quản trị là xác định các hoạt động kinh doanh chính tạo nên công ty, được gọi là <span class=\"text-rose-600\"><strong>đơn vị kinh doanh chiến lược (strategic business units - SBUs)</strong></span>. Một SBU có thể là một bộ phận của công ty, một dòng sản phẩm trong một bộ phận, hoặc đôi khi là một sản phẩm hoặc thương hiệu đơn lẻ. Sau đó, công ty đánh giá mức độ hấp dẫn của các SBU khác nhau của mình và quyết định mức độ hỗ trợ mà mỗi SBU xứng đáng nhận được. Nhiều công ty rất giỏi trong việc rút lui khỏi các hoạt động kinh doanh đang suy giảm để giải phóng nguồn lực cần thiết và đầu tư vào các hoạt động kinh doanh của tương lai.",
    "Mục đích của hoạch định chiến lược là tìm ra những cách mà công ty có thể sử dụng tốt nhất điểm mạnh của mình để tận dụng các cơ hội hấp dẫn trong môi trường. Vì vậy, hầu hết các phương pháp phân tích danh mục tiêu chuẩn đều đánh giá các SBU dựa trên hai khía cạnh quan trọng: mức độ hấp dẫn của thị trường hoặc ngành của SBU và sức mạnh vị thế của SBU trên thị trường hoặc ngành đó.",
    "Phương pháp hoạch định danh mục nổi tiếng nhất được phát triển bởi Boston Consulting Group, một công ty tư vấn quản lý hàng đầu. Sử dụng phương pháp của Boston Consulting Group (BCG), một công ty phân loại tất cả các SBU của mình theo <span class=\"text-rose-600\"><strong>ma trận tăng trưởng-thị phần (growth-share matrix)</strong></span>, như thể hiện trong Hình 2.2. Trên trục tung, tỷ lệ tăng trưởng thị trường cung cấp một thước đo về sức hấp dẫn của thị trường. Trên trục hoành, tương quan thị phần đóng vai trò là thước đo sức mạnh của công ty trên thị trường. Ma trận tăng trưởng-thị phần xác định bốn loại SBU:",
    "<strong>Hình 2.2 | Ma trận Tăng trưởng-Thị phần của BCG</strong>",
    "<span class=\"text-xs text-slate-600\">Sử dụng ma trận tăng trưởng-thị phần cổ điển của Boston Consulting Group, công ty đầu tư tiền từ những \"bò sữa\" vững chắc để giúp tài trợ cho những \"ngôi sao\" và \"dấu hỏi\" đầy hứa hẹn, hy vọng biến chúng thành những \"bò sữa\" trong tương lai.</span>",
    "1. <span class=\"text-rose-600\"><strong>Ngôi sao (Stars).</strong></span> <em>Ngôi sao</em> là các doanh nghiệp hoặc sản phẩm có tốc độ tăng trưởng cao và thị phần lớn. Chúng thường cần đầu tư lớn để tài trợ cho sự tăng trưởng nhanh chóng của mình. Cuối cùng, tốc độ tăng trưởng của chúng sẽ chậm lại, và chúng sẽ biến thành bò sữa.",
    "2. <span class=\"text-rose-600\"><strong>Bò sữa (Cash Cows).</strong></span> <em>Bò sữa</em> là các doanh nghiệp hoặc sản phẩm có tốc độ tăng trưởng thấp và thị phần lớn. Các SBU đã được thiết lập và thành công này cần ít đầu tư hơn để giữ thị phần của mình. Do đó, chúng tạo ra rất nhiều tiền mặt mà công ty sử dụng để thanh toán các hóa đơn và hỗ trợ các SBU khác cần đầu tư.",
    "3. <span class=\"text-rose-600\"><strong>Dấu hỏi (Question Marks).</strong></span> <em>Dấu hỏi</em> là các đơn vị kinh doanh có thị phần thấp trong các thị trường tăng trưởng cao. Chúng đòi hỏi rất nhiều tiền mặt để giữ thị phần của mình, chưa kể đến việc tăng thị phần. Ban lãnh đạo phải suy nghĩ kỹ về những dấu hỏi nào nên cố gắng xây dựng thành ngôi sao và những dấu hỏi nào nên loại bỏ dần.",
    "4. <span class=\"text-rose-600\"><strong>Chó (Dogs).</strong></span> <em>Chó</em> là các doanh nghiệp hoặc sản phẩm có tốc độ tăng trưởng thấp và thị phần thấp. Chúng có thể tự tạo ra đủ tiền mặt để duy trì bản thân nhưng không hứa hẹn sẽ là nguồn tiền mặt lớn.",
    "Ma trận BCG đã được một số tập đoàn lớn sử dụng trong nhiều thập kỷ, chẳng hạn như Disney. Disney đã sử dụng ma trận BCG để quản lý danh mục đầu tư đa dạng của mình, từ các công viên giải trí, hãng phim, đến các kênh truyền hình và sản phẩm tiêu dùng. Ví dụ, dịch vụ phát trực tuyến Disney+ ban đầu có thể được coi là một \"Dấu hỏi\" với tiềm năng tăng trưởng cao nhưng thị phần ban đầu thấp. Sau khi đầu tư mạnh mẽ, nó nhanh chóng trở thành một \"Ngôi sao\". Các công viên giải trí lâu đời như Disneyland có thể được coi là \"Bò sữa\", tạo ra dòng tiền ổn định. Một số kênh truyền hình cáp nhỏ hơn, ít phổ biến hơn có thể rơi vào danh mục \"Chó\".",
    "Khi một công ty đã phân loại các SBU của mình, nó phải xác định vai trò mà mỗi SBU sẽ đóng trong tương lai. Nó có thể theo đuổi một trong bốn chiến lược cho mỗi SBU. Công ty có thể đầu tư nhiều hơn vào đơn vị kinh doanh để <span class=\"text-rose-600\"><em>xây dựng (build)</em></span> thị phần của mình. Hoặc nó có thể đầu tư vừa đủ để <span class=\"text-rose-600\"><em>giữ (hold)</em></span> thị phần của SBU ở mức hiện tại. Nó có thể <span class=\"text-rose-600\"><em>tận thu (harvest)</em></span> SBU, vắt sữa dòng tiền ngắn hạn của nó bất kể tác động dài hạn. Cuối cùng, công ty có thể <span class=\"text-rose-600\"><em>loại bỏ (divest)</em></span> SBU bằng cách bán nó hoặc loại bỏ dần và sử dụng các nguồn lực ở nơi khác.",
    "Khi các SBU của công ty thay đổi theo thời gian, chúng có thể trải qua những thay đổi về vị trí trong ma trận tăng trưởng-thị phần. Mỗi SBU có một vòng đời. Nhiều SBU bắt đầu là dấu hỏi và chuyển sang danh mục ngôi sao nếu thành công. Sau đó, khi tăng trưởng thị trường chậm lại, chúng trở thành bò sữa. Cuối cùng, khi thị phần và tăng trưởng giảm, SBU có thể chết đi hoặc biến thành chó vào cuối vòng đời của nó. Công ty cần liên tục bổ sung các sản phẩm và đơn vị mới để một số trong số chúng sẽ trở thành ngôi sao và cuối cùng là bò sữa giúp tài trợ cho các SBU khác.",
    "<em><u>Các vấn đề của phương pháp ma trận.</u></em> Cách tiếp cận BCG và các phương pháp ma trận chính thức khác đã cách mạng hóa việc hoạch định chiến lược. Tuy nhiên, các phương pháp tập trung như vậy có những hạn chế. Chúng có thể khó khăn, tốn kém thời gian và chi phí để thực hiện. Ban quản trị có thể gặp khó khăn trong việc xác định các SBU và đo lường thị phần và tăng trưởng. Ngoài ra, các phương pháp này tập trung vào việc phân loại các hoạt động kinh doanh hiện tại nhưng ít đưa ra lời khuyên cho việc lập kế hoạch trong tương lai. Ban quản trị có thể thấy khó khăn khi thực hiện. Do đó, nhiều công ty đã loại bỏ các phương pháp ma trận chính thức để chuyển sang các phương pháp tùy chỉnh hơn phù hợp hơn với các tình huống cụ thể của họ. Hơn nữa, không giống như hoạch định chiến lược tập trung trước đây, nhiều công ty hiện nay phân quyền hoạch định chiến lược cho các nhà quản lý SBU. Họ đặt trách nhiệm hoạch định chiến lược vào tay các nhóm đa chức năng gồm các nhà quản lý bộ phận gần gũi với thị trường của họ hơn.",
    "Ví dụ, xem xét việc quản lý danh mục đầu tư khổng lồ và đa dạng của General Electric (GE). GE điều hành hàng chục đơn vị kinh doanh rất khác nhau, từ thiết bị gia dụng, động cơ máy bay, tuabin gió, thiết bị y tế, đến các dịch vụ tài chính. CEO của GE, Larry Culp, mô tả công việc của mình là \"nhà phân bổ vốn và người điều hành có trí tưởng tượng.\" Ông và đội ngũ của mình không ngừng xem xét lại danh mục đầu tư của GE, thoái vốn khỏi các doanh nghiệp kém hiệu quả hoặc không phù hợp chiến lược, và đầu tư vào các lĩnh vực tăng trưởng cao như năng lượng tái tạo và hàng không bền vững. Việc quản lý một danh mục đầu tư phức tạp như vậy đòi hỏi sự kết hợp giữa phân tích tài chính nghiêm ngặt, hiểu biết sâu sắc về thị trường và khả năng đưa ra các quyết định chiến lược khó khăn.",
    "<strong>B. Phát triển Chiến lược Tăng trưởng và Chiến lược Cắt giảm</strong>",
    "Ngoài việc đánh giá các hoạt động kinh doanh hiện tại, việc thiết kế danh mục kinh doanh liên quan đến việc tìm kiếm các hoạt động kinh doanh và sản phẩm mà công ty nên xem xét trong tương lai. Các công ty cần tăng trưởng nếu muốn cạnh tranh hiệu quả hơn, đáp ứng các bên liên quan và thu hút nhân tài hàng đầu. \"Tăng trưởng vì mục đích tăng trưởng\" không phải là mục tiêu. Thay vào đó, mục tiêu của công ty phải là quản lý \"tăng trưởng có lợi nhuận\".",
    "Marketing có trách nhiệm chính trong việc đạt được tăng trưởng có lợi nhuận cho công ty. Marketing cần xác định, đánh giá và lựa chọn các cơ hội thị trường và thiết lập các chiến lược để nắm bắt chúng. Một công cụ hữu ích để xác định các cơ hội tăng trưởng là <span class=\"text-rose-600\"><strong>hệ thống mở rộng sản phẩm/thị trường (product/market expansion grid)</strong></span>, như thể hiện trong Hình 2.3. Hệ thống mở rộng sản phẩm/thị trường xác định bốn con đường tăng trưởng tiềm năng:",
    "<strong>Hình 2.3 | Hệ thống Mở rộng Sản phẩm/Thị trường</strong>",
    "<span class=\"text-xs text-slate-600\">Các công ty có thể phát triển bằng cách thâm nhập tốt hơn vào các thị trường hiện tại với các sản phẩm hiện có, phát triển các thị trường mới cho các sản phẩm hiện có, phát triển các sản phẩm mới cho các thị trường hiện tại hoặc đa dạng hóa vào các doanh nghiệp mới.</span>",
    "Đầu tiên, <span class=\"text-rose-600\"><strong>thâm nhập thị trường (market penetration)</strong></span> liên quan đến việc tăng doanh số bán các sản phẩm hiện có cho các phân khúc thị trường hiện tại mà không thay đổi sản phẩm. Các nhà quản lý có thể thúc đẩy tăng trưởng hơn nữa thông qua một loạt các hoạt động marketing, bao gồm điều chỉnh thiết kế sản phẩm, quảng cáo, giá cả và các nỗ lực phân phối. Ví dụ, Under Armour đã cố gắng tăng cường thâm nhập thị trường bằng cách cải thiện thiết kế sản phẩm và bao bì, tăng chi tiêu cho quảng cáo và giảm giá. Để có thêm sự tăng trưởng, các nhà quản lý của Under Armour cũng có thể cố gắng tăng cường sự hiện diện của thương hiệu trong các cửa hàng hiện có và trực tuyến.",
    "Thứ hai, <span class=\"text-rose-600\"><strong>phát triển thị trường (market development)</strong></span> liên quan đến việc xác định và phát triển các phân khúc thị trường mới cho các sản phẩm hiện có của công ty. Ví dụ, các nhà quản lý tại Under Armour ban đầu tập trung vào nam giới. Nhưng sau đó, công ty đã cải thiện hiệu suất của mình bằng cách nhắm mục tiêu vào phụ nữ và sau đó là trẻ em. Under Armour cũng đã mở rộng sang các thị trường địa lý mới, đặc biệt là Trung Quốc, Châu Á và Châu Âu.",
    "Thứ ba, các công ty có thể xem xét <span class=\"text-rose-600\"><strong>phát triển sản phẩm (product development)</strong></span>—chào bán các sản phẩm mới hoặc được sửa đổi cho các thị trường hiện tại. Ví dụ, Under Armour đã mở rộng dòng sản phẩm quần áo thể thao hiệu suất của mình sang giày dép. Sau đó, hãng đã giới thiệu dòng sản phẩm \"UA HOVR\", bao gồm các đôi giày chạy bộ thông minh có thể theo dõi hiệu suất của vận động viên và cung cấp phản hồi theo thời gian thực.",
    "Cuối cùng, các công ty có thể xem xét <span class=\"text-rose-600\"><strong>đa dạng hóa (diversification)</strong></span>—bắt đầu hoặc mua lại các hoạt động kinh doanh ngoài các sản phẩm và thị trường hiện tại của công ty. Ví dụ, Under Armour đã đa dạng hóa bằng cách mua lại ba công ty ứng dụng theo dõi thể dục và luyện tập—MapMyFitness, MyFitnessPal và Endomondo—để tạo ra cộng đồng thể dục kỹ thuật số lớn nhất thế giới. Sau đó, họ đã ra mắt nền tảng Connected Fitness, tích hợp các ứng dụng này với quần áo và thiết bị hiệu suất của mình để cung cấp cho người tiêu dùng trải nghiệm theo dõi sức khỏe và thể chất toàn diện.",
    "Các công ty phải không chỉ phát triển chiến lược để phát triển danh mục kinh doanh của mình mà còn cả chiến lược để <span class=\"text-rose-600\"><strong>cắt giảm (downsizing)</strong></span> chúng. Có nhiều lý do khiến một công ty có thể muốn từ bỏ các sản phẩm hoặc thị trường. Công ty có thể đã phát triển quá nhanh hoặc đã tham gia vào các lĩnh vực mà họ thiếu kinh nghiệm. Đây là trường hợp của một số công ty trong thời kỳ suy thoái gần đây, khi nhiều công ty đã cắt tỉa các dòng sản phẩm và thị trường không có lợi nhuận để tập trung tốt hơn vào các dòng sản phẩm và thị trường có lợi nhuận hơn. Hoặc môi trường thị trường có thể thay đổi, làm cho một số sản phẩm hoặc thị trường trở nên kém sinh lợi hơn. Ví dụ, để đáp ứng môi trường bán lẻ đang thay đổi nhanh chóng, Procter & Gamble gần đây đã bán đi nhiều thương hiệu lớn của mình—bao gồm Pringles, Crisco, Jif, Folgers, Duracell và CoverGirl—để tập trung vào các thương hiệu cốt lõi của mình, như Tide, Crest, Pampers và Gillette. Tương tự, General Motors đã loại bỏ các thương hiệu kém năng suất như Pontiac, Saturn và Hummer để tập trung vào các thương hiệu cốt lõi của mình. Cuối cùng, một số sản phẩm hoặc đơn vị kinh doanh đơn giản là già đi và chết.",
    "Khi một công ty tìm thấy một thương hiệu hoặc SBU không có lợi nhuận hoặc không còn phù hợp với chiến lược tổng thể của công ty, nó phải quyết định xem nên giữ nó hay loại bỏ nó. Các lựa chọn yếu bao gồm thu hoạch hoặc thoái vốn. Khi một công ty quyết định cắt giảm, nó có thể loại bỏ các sản phẩm hoặc thị trường hoặc nó có thể bán các đơn vị kinh doanh đó cho các công ty khác phù hợp hơn."
  ]),
};