import { PageData } from '../../types';
import { cleanParagraphs } from '../dataUtils';

const CHAPTER_2_TITLE = "Chương 2: Doanh nghiệp và Chiến lược Marketing – Hợp tác để Thu hút Khách hàng, Tạo Giá trị và Xây dựng Quan hệ";

export const chap2SecIVPageData: PageData = {
  id: 'chap2-secIV',
  chapterTitle: CHAPTER_2_TITLE,
  pageTitle: "IV. Chiến lược Marketing và Tổ hợp Marketing",
  paragraphs: cleanParagraphs([
    "Sau khi kế hoạch chiến lược tổng thể được thiết lập, mỗi đơn vị kinh doanh cần một chiến lược marketing chi tiết. <span class=\"text-rose-600\"><strong>Chiến lược marketing (marketing strategy)</strong></span> là logic marketing mà theo đó công ty hy vọng tạo ra giá trị khách hàng và đạt được các mối quan hệ khách hàng có lợi nhuận. Công ty quyết định sẽ phục vụ khách hàng nào (phân khúc và mục tiêu) và phục vụ như thế nào (khác biệt hóa và định vị). Sau đó, công ty thiết kế một <span class=\"text-rose-600\"><strong>tổ hợp marketing (marketing mix)</strong></span> tích hợp.",
    "<strong>A. Chiến lược Marketing Hướng đến Giá trị Khách hàng</strong>",
    "Để thành công trong thị trường cạnh tranh ngày nay, các công ty phải lấy khách hàng làm trung tâm, giành được khách hàng từ đối thủ cạnh tranh, sau đó giữ chân và phát triển họ bằng cách cung cấp giá trị lớn hơn.",
    "Trong các phần trước của chương này, chúng ta đã thảo luận về quản trị mối quan hệ khách hàng—quá trình xây dựng và duy trì mối quan hệ khách hàng có lợi nhuận. Không có chiến lược nào phù hợp với tất cả các khách hàng. Do đó, công ty trước tiên phải phân chia thị trường tổng thể, chọn các phân khúc tốt nhất và thiết kế các chiến lược để phục vụ các phân khúc đã chọn một cách có lợi nhuận. Quá trình này bao gồm ba bước: <span class=\"text-rose-600\"><strong>phân khúc thị trường (market segmentation)</strong></span>, <span class=\"text-rose-600\"><strong>thị trường mục tiêu (market targeting)</strong></span>, và <span class=\"text-rose-600\"><strong>khác biệt hóa và định vị thị trường (market differentiation and positioning)</strong></span> (xem Hình 2.5).",
    "<strong>Hình 2.5 | Quản lý Chiến lược Marketing</strong>",
    "<span class=\"text-xs text-slate-600\">Ở trung tâm của hình là khách hàng—mục tiêu của chiến lược marketing là tạo ra giá trị cho khách hàng và xây dựng các mối quan hệ khách hàng có lợi nhuận. Tiếp theo là chiến lược marketing—logic marketing mà theo đó công ty hy vọng tạo ra giá trị khách hàng này và đạt được những mối quan hệ có lợi nhuận này. Được định hướng bởi chiến lược, công ty thiết kế một tổ hợp marketing tích hợp, bao gồm các yếu tố chịu sự kiểm soát của mình—sản phẩm, giá cả, phân phối và xúc tiến (4Ps). Để tìm ra chiến lược và tổ hợp marketing tốt nhất, công ty tham gia vào phân tích marketing, lập kế hoạch, triển khai và kiểm soát. Thông qua các hoạt động này, công ty theo dõi và thích ứng với các tác nhân và lực lượng trong môi trường marketing.</span>",
    "<strong><span class=\"text-rose-600\">Phân khúc thị trường (Market Segmentation).</span></strong> Thị trường bao gồm nhiều loại khách hàng, sản phẩm và nhu cầu khác nhau. Nhà marketing phải xác định các phân khúc thị trường khác nhau, chia thị trường thành các nhóm người mua riêng biệt có nhu cầu, đặc điểm hoặc hành vi khác nhau, và những người có thể yêu cầu các chiến lược hoặc tổ hợp marketing riêng biệt. Công ty có thể chia thị trường dựa trên các yếu tố địa lý (quốc gia, vùng, thành phố), nhân khẩu học (tuổi, giai đoạn vòng đời, giới tính, thu nhập, nghề nghiệp, trình độ học vấn, tôn giáo, dân tộc, thế hệ), tâm lý (lối sống, cá tính), hoặc hành vi (các dịp, lợi ích tìm kiếm, tình trạng người dùng, tỷ lệ sử dụng, mức độ trung thành). Quá trình phân chia thị trường thành các nhóm người mua nhỏ hơn với nhu cầu, đặc điểm hoặc hành vi riêng biệt có thể yêu cầu các chiến lược hoặc tổ hợp marketing riêng biệt được gọi là phân khúc thị trường.",
    "<strong><span class=\"text-rose-600\">Thị trường mục tiêu (Market Targeting).</span></strong> Sau khi một công ty đã xác định các phân khúc thị trường của mình, nó có thể thâm nhập một hoặc nhiều phân khúc này. Thị trường mục tiêu liên quan đến việc đánh giá sức hấp dẫn của từng phân khúc thị trường và lựa chọn một hoặc nhiều phân khúc để thâm nhập. Một công ty nên nhắm mục tiêu vào các phân khúc mà nó có thể tạo ra giá trị khách hàng lớn nhất và duy trì nó một cách có lợi nhuận theo thời gian. Một công ty có nguồn lực hạn chế có thể quyết định chỉ phục vụ một hoặc một vài phân khúc đặc biệt hoặc \"thị trường ngách\". Những thị trường ngách như vậy chuyên phục vụ các phân khúc khách hàng mà các đối thủ cạnh tranh lớn hơn bỏ qua hoặc không nhìn thấy. Ví dụ, nhiều công ty khởi nghiệp nhỏ bắt đầu bằng cách phục vụ các thị trường ngách. Alternativ, một công ty có thể chọn phục vụ một số phân khúc liên quan—có lẽ là những phân khúc có các loại khách hàng khác nhau nhưng có cùng nhu cầu cơ bản. Hoặc một công ty lớn có thể quyết định cung cấp một loạt sản phẩm hoàn chỉnh để phục vụ tất cả các phân khúc thị trường của mình. Hầu hết các công ty thâm nhập một thị trường mới bằng cách phục vụ một phân khúc duy nhất; nếu điều này chứng tỏ thành công, họ sẽ bổ sung thêm các phân khúc.",
    "<strong><span class=\"text-rose-600\">Khác biệt hóa và Định vị thị trường (Market Differentiation and Positioning).</span></strong> Sau khi một công ty đã quyết định phân khúc thị trường nào để thâm nhập, nó phải quyết định cách tạo sự khác biệt cho các đề xuất thị trường của mình cho từng phân khúc mục tiêu và vị trí mà nó muốn chiếm giữ trong các phân khúc đó. <span class=\"text-rose-600\"><strong>Định vị (positioning)</strong></span> là việc sắp xếp để một sản phẩm chiếm một vị trí rõ ràng, khác biệt và mong muốn so với các sản phẩm cạnh tranh trong tâm trí người tiêu dùng mục tiêu. Các nhà marketing lên kế hoạch định vị để tạo cho sản phẩm của họ lợi thế lớn nhất trong các thị trường mục tiêu đã chọn; họ thiết kế các tổ hợp marketing để tạo ra các vị trí đã hoạch định này.",
    "Trong việc định vị thương hiệu của mình, một công ty trước tiên xác định các điểm khác biệt giá trị khách hàng có thể có để xây dựng vị trí. Công ty có thể cung cấp giá trị khách hàng lớn hơn bằng cách tính giá thấp hơn so với đối thủ cạnh tranh hoặc bằng cách cung cấp nhiều lợi ích hơn để biện minh cho giá cao hơn. Nhưng nếu công ty hứa hẹn giá trị lớn hơn, nó phải thực sự cung cấp giá trị đó. Do đó, định vị hiệu quả bắt đầu bằng việc <span class=\"text-rose-600\"><strong>khác biệt hóa (differentiation)</strong></span> thực sự đề xuất giá trị của công ty để nó mang lại cho người tiêu dùng nhiều giá trị hơn.",
    "Khi công ty đã chọn được một vị trí mong muốn, nó phải thực hiện các bước mạnh mẽ để cung cấp và truyền đạt vị trí đó cho người tiêu dùng mục tiêu. Toàn bộ chương trình marketing của công ty phải hỗ trợ chiến lược định vị đã chọn.",
    "<strong>B. Phát triển Tổ hợp Marketing Tích hợp</strong>",
    "Sau khi xác định chiến lược marketing tổng thể của mình, công ty bắt đầu lập kế hoạch chi tiết cho <span class=\"text-rose-600\"><strong>tổ hợp marketing (marketing mix)</strong></span>—một tập hợp các công cụ marketing chiến thuật, có thể kiểm soát mà công ty phối hợp để tạo ra phản ứng mong muốn từ thị trường mục tiêu. Tổ hợp marketing bao gồm mọi thứ mà công ty có thể làm để thu hút người tiêu dùng và cung cấp giá trị cho khách hàng. Các khả năng này có thể được tập hợp thành bốn nhóm biến số chính, được gọi là 4Ps của marketing: sản phẩm, giá cả, phân phối và xúc tiến.",
    "<strong><span class=\"text-rose-600\">Sản phẩm (Product)</span></strong> có nghĩa là sự kết hợp hàng hóa và dịch vụ mà công ty cung cấp cho thị trường mục tiêu. Vì vậy, một chiếc Ford Escape bao gồm các loại hạt và bu lông, bugi, piston, đèn pha và vô số bộ phận khác. Ford cung cấp một số kiểu Escape và hàng chục tính năng tùy chọn. Chiếc xe đi kèm với dịch vụ bảo hành đầy đủ cho các bộ phận và tay nghề, đồng thời người mua có thể nhận được các dịch vụ hậu mãi từ đại lý Ford. Để tập trung hơn, sản phẩm bao gồm thiết kế, thương hiệu, bao bì, dịch vụ và các tính năng khác.",
    "<strong><span class=\"text-rose-600\">Giá (Price)</span></strong> là số tiền khách hàng phải trả để có được sản phẩm. Ford tính toán giá bán lẻ đề xuất mà các đại lý của họ có thể tính cho mỗi chiếc Escape. Nhưng các đại lý của Ford hiếm khi tính giá niêm yết đầy đủ. Thay vào đó, họ đàm phán giá với từng khách hàng, đưa ra chiết khấu, phụ cấp đổi hàng và các điều khoản tín dụng. Những hành động này điều chỉnh giá cho tình hình cạnh tranh hiện tại và cho nhận thức của người mua về giá trị của chiếc xe. Giá bao gồm giá niêm yết, chiết khấu, phụ cấp, thời hạn thanh toán và các điều khoản tín dụng.",
    "<strong><span class=\"text-rose-600\">Phân phối (Place)</span></strong> bao gồm các hoạt động của công ty giúp sản phẩm đến tay người tiêu dùng mục tiêu. Ford hợp tác với một mạng lưới lớn gồm các đại lý độc lập bán các mẫu xe khác nhau của công ty. Ford lựa chọn các đại lý của mình một cách cẩn thận và hỗ trợ họ mạnh mẽ. Các đại lý giữ một kho xe Ford, trình diễn chúng cho khách hàng tiềm năng, đàm phán giá cả, chốt giao dịch mua bán và bảo dưỡng xe sau khi bán. Phân phối bao gồm các kênh, phạm vi bao phủ, chủng loại, địa điểm, hàng tồn kho, vận chuyển và hậu cần.",
    "<strong><span class=\"text-rose-600\">Xúc tiến (Promotion)</span></strong> đề cập đến các hoạt động truyền đạt giá trị của sản phẩm và thuyết phục khách hàng mục tiêu mua nó. Ford chi hơn 1.5 tỷ đô la mỗi năm cho quảng cáo ở Hoa Kỳ để nói với người tiêu dùng về công ty và nhiều sản phẩm của mình. Các nhân viên bán hàng của đại lý hỗ trợ khách hàng tiềm năng và thuyết phục họ rằng Ford là chiếc xe tốt nhất cho họ. Ford và các đại lý của mình đưa ra các chương trình khuyến mãi đặc biệt—giảm giá bán hàng, hoàn tiền mặt và các khoản vay lãi suất thấp như các ưu đãi mua hàng bổ sung. Và bộ phận quan hệ công chúng của Ford truyền đạt thông tin về công ty và các sản phẩm của mình. Xúc tiến bao gồm quảng cáo, bán hàng cá nhân, xúc tiến bán hàng và quan hệ công chúng.",
    "Một chương trình marketing hiệu quả sẽ phối hợp tất cả các yếu tố của marketing hỗn hợp thành một chương trình tích hợp được thiết kế để đạt được các mục tiêu marketing của công ty bằng cách cung cấp giá trị cho người tiêu dùng. Tổ hợp marketing tạo nên bộ công cụ chiến thuật của công ty để thiết lập định vị vững chắc trong các thị trường mục tiêu.",
    "Lưu ý rằng 4Ps có quan điểm của người bán về thị trường, chứ không phải quan điểm của người mua. Từ quan điểm của người mua, trong thời đại kết nối, giá trị khách hàng và mối quan hệ ngày nay, 4Ps có thể được mô tả tốt hơn là 4As:",
    "<strong><span class=\"text-rose-600\">Chấp nhận (Acceptability)</span></strong> là mức độ mà một sản phẩm vượt quá mong đợi của khách hàng.",
    "<strong><span class=\"text-rose-600\">Khả năng chi trả (Affordability)</span></strong> là mức độ mà khách hàng sẵn sàng và có thể trả giá của sản phẩm.",
    "<strong><span class=\"text-rose-600\">Khả năng tiếp cận (Accessibility)</span></strong> là mức độ mà khách hàng có thể dễ dàng mua được sản phẩm.",
    "<strong><span class=\"text-rose-600\">Nhận thức (Awareness)</span></strong> là mức độ mà khách hàng được thông báo về các tính năng của sản phẩm, bị thuyết phục để dùng thử và được nhắc nhở mua lại."
  ]),
};