import { PageData } from '../../types';
import { cleanParagraphs } from '../dataUtils';

const CHAPTER_2_TITLE = "Chương 2: Doanh nghiệp và Chiến lược Marketing – Hợp tác để Thu hút Khách hàng, Tạo Giá trị và Xây dựng Quan hệ";

export const chap2SecIIIPageData: PageData = {
  id: 'chap2-secIII',
  chapterTitle: CHAPTER_2_TITLE,
  pageTitle: "III. Lập kế hoạch Marketing: Hợp tác Xây dựng Quan hệ Khách hàng",
  paragraphs: cleanParagraphs([
    "Kế hoạch chiến lược của công ty thiết lập các loại hình kinh doanh mà công ty sẽ hoạt động và các mục tiêu cho từng loại. Sau đó, trong mỗi đơn vị kinh doanh, cần có kế hoạch chi tiết hơn. Các phòng ban chức năng chính trong mỗi đơn vị—marketing, tài chính, kế toán, mua hàng, vận hành, công nghệ thông tin, nhân sự và các phòng ban khác—phải làm việc cùng nhau để hoàn thành các mục tiêu chiến lược.",
    "Marketing đóng một vai trò quan trọng trong hoạch định chiến lược của công ty theo nhiều cách. Thứ nhất, marketing cung cấp một triết lý định hướng—quan điểm marketing—cho rằng chiến lược công ty nên xoay quanh việc tạo ra giá trị khách hàng và xây dựng các mối quan hệ có lợi nhuận với các nhóm người tiêu dùng quan trọng. Thứ hai, marketing cung cấp thông tin đầu vào cho các nhà hoạch định chiến lược bằng cách giúp xác định các cơ hội thị trường hấp dẫn và đánh giá tiềm năng của công ty để tận dụng chúng. Cuối cùng, trong các đơn vị kinh doanh riêng lẻ, marketing thiết kế các chiến lược để đạt được các mục tiêu của đơn vị một cách có lợi nhuận.",
    "Tuy nhiên, bộ phận marketing không thể đơn độc tạo ra giá trị vượt trội cho khách hàng. Như đã thảo luận trong Chương 1, theo quan điểm marketing của công ty, tất cả các phòng ban đều phải lấy khách hàng làm trung tâm và tất cả các phòng ban phải hợp tác hài hòa để tạo ra và cung cấp giá trị và sự hài lòng cho khách hàng. Như một nhà quản lý của McDonald's đã nói, \"Nếu bạn không phục vụ khách hàng, thì tốt hơn bạn nên phục vụ người nào đó đang phục vụ khách hàng.\" Vì vậy, các nhà quản lý marketing phải làm việc chặt chẽ với các phòng ban khác. Họ cũng phải hợp tác với các công ty khác trong toàn bộ hệ thống marketing để hình thành một mạng lưới phân phối giá trị hiệu quả nhằm phục vụ khách hàng.",
    "<strong>A. Hợp tác với các Phòng ban Nội bộ</strong>",
    "Mỗi phòng ban của công ty có thể được coi là một mắt xích trong <span class=\"text-rose-600\"><strong>chuỗi giá trị (value chain)</strong></span> nội bộ của công ty (xem Hình 2.4). Nghĩa là, mỗi phòng ban thực hiện các hoạt động tạo giá trị để thiết kế, sản xuất, tiếp thị, phân phối và hỗ trợ các sản phẩm của công ty. Thành công của công ty không chỉ phụ thuộc vào việc mỗi phòng ban thực hiện tốt công việc của mình như thế nào mà còn phụ thuộc vào việc các phòng ban khác nhau phối hợp tốt các hoạt động của họ như thế nào.",
    "<strong>Hình 2.4 | Chuỗi Giá trị</strong>",
    "<span class=\"text-xs text-slate-600\">Một công ty thành công khi toàn bộ chuỗi giá trị của nó—mỗi phòng ban làm việc cùng nhau để phục vụ khách hàng—tạo ra giá trị khách hàng.</span>",
    "Ví dụ, mục tiêu của Walmart là tạo ra giá trị khách hàng và sự hài lòng bằng cách cung cấp cho người mua sắm những sản phẩm họ muốn với giá thấp nhất có thể. Các nhà marketing của Walmart đóng một vai trò quan trọng. Họ tìm hiểu nhu cầu của người mua, lựa chọn hàng hóa, tích trữ hàng hóa, định giá và trưng bày hàng hóa một cách hiệu quả, đồng thời quảng bá các cửa hàng và các sản phẩm trong đó. Bộ phận mua hàng của Walmart chịu trách nhiệm tìm kiếm các nhà cung cấp phù hợp và mua hàng hóa với chi phí thấp. Bộ phận vận hành chịu trách nhiệm vận chuyển và phân phối hàng hóa. Bộ phận CNTT của Walmart duy trì một hệ thống thông tin tiên tiến để theo dõi sản phẩm, quản lý hàng tồn kho, liên lạc với nhà cung cấp và phục vụ khách hàng. Những bộ phận này và các bộ phận khác phải làm việc cùng nhau một cách hài hòa.",
    "Lý tưởng nhất, chuỗi giá trị của một công ty chỉ mạnh bằng mắt xích yếu nhất của nó. Sự thành công phụ thuộc vào mức độ phối hợp tốt của từng phòng ban trong việc gia tăng giá trị cho khách hàng và mức độ phối hợp tốt của các hoạt động của các phòng ban khác nhau. Ví dụ, một công ty có thể có một đội ngũ bán hàng và marketing xuất sắc, nhưng nếu hoạt động vận hành của công ty chậm chạp, dịch vụ khách hàng kém hoặc sản phẩm có chất lượng thấp, thì công ty đó sẽ không thành công. Các công ty như Walmart và McDonald's đào tạo nhân viên từ tất cả các phòng ban để nghĩ về khách hàng và làm việc theo nhóm nhằm xây dựng mối quan hệ khách hàng có lợi nhuận.",
    "<strong>B. Hợp tác với các Đối tác Khác trong Hệ thống Marketing</strong>",
    "Để tạo ra giá trị cho khách hàng, công ty cần phải nhìn xa hơn chuỗi giá trị nội bộ của mình và thâm nhập vào chuỗi giá trị của các nhà cung cấp, nhà phân phối và cuối cùng là khách hàng. Ngày càng nhiều công ty ngày nay hợp tác với các thành viên khác của chuỗi cung ứng—nhà cung cấp, nhà phân phối và cuối cùng là khách hàng—để cải thiện hiệu suất của <span class=\"text-rose-600\"><strong>mạng lưới phân phối giá trị cho khách hàng (customer value delivery network)</strong></span> bao gồm công ty, nhà cung cấp, nhà phân phối và cuối cùng là khách hàng hợp tác với nhau để cải thiện hiệu suất của toàn bộ hệ thống.",
    "Ví dụ, Ford coi các nhà cung cấp của mình là đối tác. Hãng hợp tác chặt chẽ với họ để tìm ra những cách tốt nhất để sản xuất và cung cấp các bộ phận. Đổi lại, các nhà cung cấp của Ford được hưởng lợi từ mối quan hệ lâu dài và doanh số bán hàng ổn định. Tương tự như vậy, Lexus làm việc chặt chẽ với các đại lý của mình để cung cấp dịch vụ bán hàng và dịch vụ chất lượng cao. Cả nhà cung cấp của Ford và đại lý của Lexus đều là một phần không thể thiếu trong mạng lưới phân phối giá trị của Ford và Lexus. Cạnh tranh không còn chỉ diễn ra giữa các đối thủ cạnh tranh riêng lẻ nữa. Thay vào đó, nó diễn ra giữa toàn bộ mạng lưới phân phối giá trị do các đối thủ cạnh tranh này tạo ra."
  ]),
};