import { PageData } from '../../types';
import { cleanParagraphs } from '../dataUtils';

const CHAPTER_2_TITLE = "Chương 2: Doanh nghiệp và Chiến lược Marketing – Hợp tác để Thu hút Khách hàng, Tạo Giá trị và Xây dựng Quan hệ";

export const chap2SecVIPageData: PageData = {
  id: 'chap2-secVI',
  chapterTitle: CHAPTER_2_TITLE,
  pageTitle: "VI. Đo lường và Quản trị Tỷ lệ Hoàn vốn Đầu tư cho Marketing (Marketing ROI)",
  paragraphs: cleanParagraphs([
    "Các nhà quản lý marketing phải đảm bảo rằng tiền chi cho marketing được đầu tư đúng đắn. Trong nhiều năm, các nhà marketing đã chi tiêu thoải mái cho các chương trình marketing lớn và đắt tiền, thường không suy nghĩ kỹ về lợi tức tài chính từ các khoản chi tiêu của họ. Họ cho rằng marketing tạo ra nhuận cầu và sự nhận biết thương hiệu, và điều đó bằng cách nào đó sẽ dẫn đến doanh số và lợi nhuận cao hơn. Nhưng tất cả những điều đó đã thay đổi trong những năm gần đây. Các thời kỳ kinh tế khó khăn và không chắc chắn đã tạo ra một thế hệ mới các nhà quản lý tài chính thận trọng hơn, những người yêu cầu có trách nhiệm giải trình cao hơn cho các khoản đầu tư marketing của họ.",
    "Để đáp lại, các nhà marketing đang phát triển các biện pháp tốt hơn về <span class=\"text-rose-600\"><strong>tỷ lệ hoàn vốn đầu tư cho marketing (marketing return on investment - marketing ROI)</strong></span>. Marketing ROI (còn được gọi là marketing profit hoặc return on marketing investment—ROMI) là lợi nhuận ròng từ một khoản đầu tư marketing chia cho chi phí của khoản đầu tư marketing đó. Marketing ROI đo lường lợi nhuận được tạo ra bởi các khoản đầu tư vào các hoạt động marketing. Ví dụ, giả sử một công ty chi 500.000 đô la cho một chiến dịch quảng cáo và thu về 750.000 đô la lợi nhuận ròng từ doanh số bán hàng tăng thêm do chiến dịch đó tạo ra. Marketing ROI trong trường hợp này là 50 phần trăm (750.000 đô la / 500.000 đô la = 1,5; 1,5 – 1 = 0,50, hoặc 50 phần trăm).",
    "Marketing ROI có thể khó đo lường. Ví dụ, không có định nghĩa nhất quán về marketing ROI. Theo một cuộc khảo sát, 65% các nhà quản lý marketing cho biết họ sử dụng các thước đo marketing ROI, nhưng chỉ 43% số đó đo lường marketing ROI bằng cách sử dụng các định nghĩa và phương pháp đã được thiết lập. Và trong việc đo lường marketing ROI, có nhiều cách để đo lường cả \"lợi nhuận\" và \"đầu tư\". Lợi nhuận có thể là doanh số bán hàng tăng thêm, tăng nhận biết thương hiệu, tăng lòng trung thành của khách hàng, hoặc các thước đo tập trung vào khách hàng khác.",
    "Hơn nữa, lợi nhuận từ một khoản đầu tư marketing có thể khó xác định. Ví dụ, quảng cáo có thể làm tăng nhận biết thương hiệu và gắn kết thương hiệu. Đổi lại, sự nhận biết và gắn kết thương hiệu tăng lên có thể dẫn đến doanh số bán hàng cao hơn, lợi nhuận lớn hơn và giá trị khách hàng lớn hơn. Tuy nhiên, việc đo lường tác động chính xác của các yếu tố này có thể khó khăn.",
    "Bất chấp những thách thức này, các nhà marketing phải cố gắng đo lường marketing ROI. Họ có thể đánh giá marketing ROI bằng cách sử dụng các phân tích marketing tiêu chuẩn, chẳng hạn như phân tích doanh số và thị phần. Hoặc họ có thể sử dụng các phân tích phức tạp hơn, chẳng hạn như mô hình tổ hợp marketing (marketing-mix models), để cô lập tác động của các hoạt động marketing khác nhau.",
    "Ngày càng nhiều, các nhà marketing đang sử dụng các thước đo marketing tập trung vào khách hàng làm đầu vào cho các quyết định đầu tư chiến lược của họ. Các thước đo marketing tiêu chuẩn, tập trung vào hiệu suất bao gồm nhận biết thương hiệu, doanh số bán hàng hoặc thị phần. Nhiều công ty đang tập hợp các thước đo như vậy thành <span class=\"text-rose-600\"><strong>bảng điều khiển marketing (marketing dashboards)</strong></span>—các bộ thước đo marketing có ý nghĩa được tập hợp lại trong một màn hình duy nhất được sử dụng để theo dõi hiệu suất chiến lược.",
    "Ví dụ, Unilever sử dụng một bảng điều khiển marketing có tên \"Brand Health Check\" để theo dõi hiệu suất của các thương hiệu của mình trên một loạt các thước đo, bao gồm thị phần, doanh số bán hàng, giá cả, phân phối, quảng cáo và các chương trình khuyến mãi. Bảng điều khiển cho phép các nhà quản lý thương hiệu của Unilever nhanh chóng xác định các lĩnh vực mà thương hiệu của họ đang hoạt động tốt hoặc kém, và thực hiện các hành động khắc phục khi cần thiết.",
    "Tuy nhiên, các thước đo marketing ngày nay cũng phải tính đến các thước đo tập trung vào khách hàng như mức độ thu hút khách hàng, tỷ lệ giữ chân khách hàng, giá trị trọn đời của khách hàng và tổng giá trị vòng đời khách hàng. Bảng điều khiển marketing chính của McDonald's, ví dụ, theo dõi một bộ thước đo hiệu suất cân bằng bao gồm các mục như số lượt khách hàng, sự hài lòng của khách hàng và giá trị thương hiệu. \"Chúng tôi theo dõi sát sao những gì khách hàng nói với chúng tôi về trải nghiệm của họ tại McDonald's,\" một giám đốc điều hành của McDonald's nói. \"Chúng tôi sử dụng phản hồi đó để cải thiện hoạt động của mình và cung cấp trải nghiệm tốt hơn cho khách hàng của mình.\" (Xem Hình 2.8.)",
    "<strong>Hình 2.8 | Tỷ lệ Hoàn vốn Đầu tư cho Marketing (Marketing ROI)</strong>",
    "<span class=\"text-xs text-slate-600\">Các công ty đang xác định các thước đo hiệu suất marketing tập trung vào khách hàng và liên kết chúng với tỷ lệ hoàn vốn đầu tư cho marketing.</span>"
  ]),
};