import { PageData } from '../../types';
import { cleanParagraphs } from '../dataUtils';

const CHAPTER_1_TITLE = "Chương 1: Marketing – Tạo Giá Trị và Thu Hút Khách Hàng";

export const chap1SecIIIPageData: PageData = {
  id: 'chap1-secIII',
  chapterTitle: CHAPTER_1_TITLE,
  pageTitle: "III. Thấu hiểu Thị trường và Nhu cầu Khách hàng",
  paragraphs: cleanParagraphs([
    "Bước đầu tiên và nền tảng trong quy trình marketing là việc thấu hiểu một cách toàn diện thị trường và các nhu cầu, mong muốn của khách hàng. Điều này bao gồm việc nắm bắt các khái niệm cốt lõi sau:",
    "<strong>A. Nhu cầu, Mong muốn và Đòi hỏi</strong>",
    "Ba khái niệm này là trọng tâm để hiểu hành vi tiêu dùng:",
    "<strong><span class=\"text-rose-600\">Nhu cầu (Needs)</span></strong>: Là trạng thái cảm thấy thiếu hụt một điều gì đó cơ bản. Nhu cầu bao gồm các khía cạnh vật chất (thực phẩm, quần áo, sự an toàn), xã hội (sự thuộc về, tình cảm) và cá nhân (kiến thức, sự tự thể hiện). Quan trọng là, người làm marketing <em><u>không</u></em> tạo ra những nhu cầu này; chúng là một phần cố hữu của con người.",
    "<strong><span class=\"text-rose-600\">Mong muốn (Wants)</span></strong>: Là hình thức cụ thể mà nhu cầu của con người biểu hiện, được định hình bởi văn hóa và cá tính cá nhân. Ví dụ, nhu cầu về thức ăn có thể biểu hiện thành mong muốn một chiếc bánh Big Mac ở Mỹ, hoặc khoai môn và thịt lợn ở Papua New Guinea. Một người Mỹ <em>cần</em> thức ăn nhưng <em>mong muốn</em> một chiếc Big Mac.",
    "<strong><span class=\"text-rose-600\">Đòi hỏi (Demands)</span></strong>: Là những mong muốn được hỗ trợ bởi sức mua. Khi có mong muốn và nguồn lực (khả năng chi trả), con người sẽ hình thành đòi hỏi đối với các sản phẩm và dịch vụ cụ thể mà họ tin rằng sẽ mang lại giá trị và sự hài lòng cao nhất. Ví dụ, nhiều người mong muốn một chiếc xe Mercedes, nhưng chỉ một số ít có khả năng và sẵn sàng mua.",
    "Sự phân biệt giữa ba khái niệm này rất quan trọng. Các nỗ lực marketing hiệu quả thường tập trung vào việc chuyển đổi các nhu cầu cơ bản thành những mong muốn cụ thể đối với sản phẩm hoặc dịch vụ của công ty, và sau đó kích thích nhu cầu bằng cách làm cho những sản phẩm/dịch vụ đó trở nên dễ tiếp cận và hấp dẫn. Các công ty xuất sắc trong marketing đầu tư đáng kể vào việc nghiên cứu người tiêu dùng, phân tích dữ liệu khách hàng và quan sát hành vi của họ để thấu hiểu sâu sắc những nhu cầu, mong muốn và đòi hỏi này.",
    "<strong>B. Đề xuất Thị trường – Sản phẩm, Dịch vụ và Trải nghiệm</strong>",
    "Nhu cầu và mong muốn của người tiêu dùng được đáp ứng thông qua các <strong><span class=\"text-rose-600\">đề xuất thị trường (market offerings)</span></strong>. Đây là sự kết hợp của sản phẩm, dịch vụ, thông tin hoặc trải nghiệm được cung cấp cho thị trường nhằm thỏa mãn một nhu cầu hoặc mong muốn cụ thể. Đề xuất thị trường không chỉ giới hạn ở các sản phẩm hữu hình mà còn bao gồm các dịch vụ (như ngân hàng, hàng không, khách sạn, sửa chữa nhà cửa), con người (chính trị gia, người nổi tiếng), địa điểm (điểm du lịch, thành phố), tổ chức (nhà thờ, trường học), thông tin (cơ sở dữ liệu, nền tảng tin tức) và ý tưởng (chiến dịch sức khỏe cộng đồng, sáng kiến môi trường).",
    "Một sai lầm phổ biến mà các nhà tiếp thị mắc phải là <strong><span class=\"text-rose-600\">thiển cận trong marketing (marketing myopia)</span></strong>, tức là quá tập trung vào các sản phẩm cụ thể mà họ cung cấp thay vì các lợi ích và trải nghiệm mà những sản phẩm đó tạo ra. Ví dụ, một nhà sản xuất mũi khoan có thể nghĩ rằng khách hàng cần một mũi khoan, nhưng thực tế cái khách hàng cần là một cái lỗ 1/4 inch. Những nhà marketing thông thái nhìn xa hơn các thuộc tính của sản phẩm và dịch vụ để tạo ra <strong><span class=\"text-rose-600\">trải nghiệm thương hiệu (brand experiences)</span></strong> cho người tiêu dùng. Walt Disney World Resort không chỉ bán vé vào cổng; họ mang đến một thế giới kỳ diệu, nơi \"những giấc mơ trở thành hiện thực\". Tương tự, American Girl không chỉ bán búp bê; họ tạo ra những trải nghiệm đặc biệt giữa búp bê và các bé gái thông qua các cửa hàng, tạp chí và các sự kiện tương tác.",
    "Sự chuyển dịch từ việc bán sản phẩm sang việc điều phối trải nghiệm cho thấy một sự thấu hiểu sâu sắc hơn về giá trị tiêu dùng. Trải nghiệm thường đáng nhớ hơn, gắn kết về mặt cảm xúc hơn và khó bị sao chép hơn so với các sản phẩm vật lý đơn thuần. Điều này dẫn đến sự khác biệt hóa thương hiệu mạnh mẽ hơn và lòng trung thành của khách hàng cao hơn. Bởi lẽ, khách hàng mua sản phẩm để giải quyết vấn đề hoặc để có được những trải nghiệm mà sản phẩm đó mang lại. Những kết nối cảm xúc được tạo ra thông qua trải nghiệm thường bền vững và có giá trị hơn nhiều so với các thuộc tính chức năng đơn thuần của sản phẩm, từ đó tạo ra lợi thế cạnh tranh bền vững hơn.",
    "<strong>C. Giá trị và Sự hài lòng của Khách hàng</strong>",
    "Đối mặt với vô số lựa chọn sản phẩm và dịch vụ, khách hàng hình thành những kỳ vọng về giá trị và sự hài lòng mà các đề xuất thị trường khác nhau sẽ mang lại, sau đó mới đưa ra quyết định mua hàng.",
    "<strong><span class=\"text-rose-600\">Giá trị được nhận thức bởi khách hàng (Customer-perceived value)</span></strong>: Đây là sự đánh giá của khách hàng về sự khác biệt giữa tất cả các lợi ích và tất cả các chi phí của một đề xuất thị trường so với các đề xuất của đối thủ cạnh tranh. Điều quan trọng là khách hàng hành động dựa trên giá trị nhận thức, chứ không nhất thiết là một đánh giá khách quan hay chính xác tuyệt đối. Ví dụ, một số khách hàng có thể coi một chiếc smartphone giá 1000 đô la là có giá trị cao do các tính năng, thiết kế và hệ sinh thái của nó, trong khi những người khác có thể thấy nó quá đắt so với nhu cầu của họ.",
    "<strong><span class=\"text-rose-600\">Sự hài lòng của khách hàng (Customer satisfaction)</span></strong>: Phụ thuộc vào mức độ mà hiệu suất nhận thức được của sản phẩm khớp với kỳ vọng của người mua. Nếu hiệu suất không đạt kỳ vọng, khách hàng sẽ không hài lòng. Nếu hiệu suất đáp ứng kỳ vọng, họ sẽ hài lòng. Nếu hiệu suất vượt quá kỳ vọng, họ sẽ rất hài lòng hoặc vui sướng (delighted).",
    "Các nhà marketing phải cẩn trọng trong việc thiết lập mức độ kỳ vọng phù hợp. Kỳ vọng quá thấp có thể làm hài lòng những người mua nhưng không thu hút đủ khách hàng. Kỳ vọng quá cao có thể dẫn đến sự thất vọng. Mức độ hài lòng cao thường dẫn đến lòng trung thành lớn hơn, khiến khách hàng mua lại và chia sẻ trải nghiệm tích cực với người khác. Giá trị cảm nhận mang tính chủ quan và tương đối, trong khi sự hài lòng là một đánh giá sau mua hàng dựa trên những cảm nhận này. Do đó, việc quản lý cả hai đòi hỏi sự thấu hiểu sâu sắc quan điểm của khách hàng, chứ không chỉ từ góc độ của công ty. Các công ty không chỉ cần tạo ra giá trị thực tế mà còn phải truyền thông hiệu quả và quản lý nhận thức về giá trị đó để đặt ra những kỳ vọng phù hợp.",
    "<strong>D. Trao đổi và Các mối Quan hệ</strong>",
    "Marketing diễn ra khi con người quyết định thỏa mãn nhu cầu và mong muốn của họ thông qua các mối quan hệ trao đổi. <strong><span class=\"text-rose-600\">Trao đổi (Exchange)</span></strong> là hành động nhận được một đối tượng mong muốn từ ai đó bằng cách đưa lại một thứ gì đó. Ví dụ, một ứng cử viên chính trị muốn phiếu bầu, một nhà thờ muốn thành viên, một dàn nhạc muốn khán giả. Để trao đổi diễn ra, nhiều điều kiện phải được thỏa mãn. Marketing bao gồm các hành động được thực hiện để tạo ra, duy trì và phát triển các mối quan hệ trao đổi mong muốn với các đối tượng mục tiêu. Các công ty xây dựng mối quan hệ bền chặt bằng cách liên tục cung cấp giá trị khách hàng vượt trội. Phạm vi của marketing không chỉ dừng lại ở các giao dịch đơn lẻ mà mở rộng đến việc nuôi dưỡng các mối quan hệ lâu dài, mang lại giá trị, vốn bền vững và có lợi hơn.",
    "<strong>E. Thị trường</strong>",
    "<strong><span class=\"text-rose-600\">Thị trường (Market)</span></strong> là tập hợp tất cả những người mua thực tế và tiềm năng của một sản phẩm hoặc dịch vụ. Những người mua này chia sẻ một nhu cầu hoặc mong muốn cụ thể có thể được thỏa mãn thông qua các mối quan hệ trao đổi. Marketing có nghĩa là quản lý thị trường để mang lại các mối quan hệ khách hàng có lợi nhuận. Các hoạt động marketing cốt lõi bao gồm nghiên cứu người tiêu dùng, phát triển sản phẩm, truyền thông, phân phối, định giá và dịch vụ.",
    "Trong kỷ nguyên số, người mua cũng tham gia vào hoạt động marketing khi họ tìm kiếm sản phẩm, tương tác với công ty để lấy thông tin và thực hiện mua hàng. Công nghệ kỹ thuật số đã trao quyền cho người tiêu dùng, biến marketing thành một hoạt động hai chiều thực sự, dẫn đến khái niệm <strong><span class=\"text-rose-600\">\"mối quan hệ do khách hàng quản lý\" (customer-managed relationships)</span></strong>. Điều này cho thấy sự suy giảm quyền kiểm soát của nhà tiếp thị. Các thương hiệu hiện nay phải tham gia vào các cuộc đối thoại do người tiêu dùng khởi xướng và kiểm soát, đòi hỏi sự minh bạch và khả năng đáp ứng cao hơn. Nhà tiếp thị không chỉ hỏi \"Làm thế nào chúng ta có thể ảnh hưởng đến khách hàng?\" mà còn phải xem xét \"Khách hàng có thể ảnh hưởng đến chúng ta như thế nào?\" và \"Khách hàng của chúng ta có thể ảnh hưởng lẫn nhau như thế nào?\". Hệ thống marketing hiện đại (Hình 1.2 sẽ được trình bày chi tiết hơn sau này) bao gồm công ty (nhà marketing), nhà cung cấp, các trung gian marketing (nhà bán lẻ, nhà phân phối), đối thủ cạnh tranh và công chúng (các yếu tố môi trường vĩ mô như nhân khẩu học, kinh tế, tự nhiên, công nghệ, chính trị và văn hóa) và khách hàng mục tiêu. Mỗi bên trong hệ thống đều cung cấp giá trị và bị ảnh hưởng bởi các yếu tố khác. Walmart không thể đưa ra giá thấp hơn nếu nhà cung cấp không đưa ra giá thấp hơn. Ford không thể cung cấp dịch vụ khách hàng tốt nếu các nhà phân phối lẻ không cung cấp tốt. Mũi tên biểu thị những mối quan hệ cần phát triển và quản trị để xây dựng giá trị khách hàng và các mối quan hệ khách hàng có thể sinh lời."
  ]),
};