import { PageData } from '../../types';
import { cleanParagraphs } from '../dataUtils';

const CHAPTER_1_TITLE = "Chương 1: Marketing – Tạo Giá Trị và Thu Hút Khách Hàng";

export const chap1SecIVPageData: PageData = {
  id: 'chap1-secIV',
  chapterTitle: CHAPTER_1_TITLE,
  pageTitle: "IV. Thiết kế Chiến lược và Kế hoạch Marketing Hướng đến Giá trị Khách hàng (Bước 2 & 3)",
  paragraphs: cleanParagraphs([
    "Sau khi đã thấu hiểu thị trường và người tiêu dùng, nhà quản trị marketing có thể thiết kế một chiến lược marketing hướng đến giá trị khách hàng và xây dựng một kế hoạch marketing tích hợp.",
    "<strong>A. Chiến lược Marketing Hướng đến Giá trị Khách hàng</strong>",
    "<strong><span class=\"text-rose-600\">Quản trị marketing (Marketing management)</span></strong> được định nghĩa là nghệ thuật và khoa học của việc lựa chọn thị trường mục tiêu và xây dựng các mối quan hệ có lợi nhuận với những thị trường đó. Để thiết kế một chiến lược marketing thành công, nhà quản trị phải trả lời hai câu hỏi quan trọng:",
    "1. <u>Chúng ta sẽ phục vụ khách hàng nào (Thị trường mục tiêu là gì)?</u> Công ty thực hiện điều này bằng cách chia thị trường thành các phân khúc khách hàng (<strong><span class=\"text-rose-600\">phân khúc thị trường - market segmentation</span></strong>) và lựa chọn một hoặc nhiều phân khúc để theo đuổi (<strong><span class=\"text-rose-600\">marketing mục tiêu - target marketing</span></strong>). Các công ty không thể phục vụ tốt tất cả khách hàng bằng mọi cách; do đó, họ chọn những khách hàng mà họ có thể phục vụ tốt nhất và có khả năng sinh lời cao nhất. Ví dụ, Nordstrom nhắm đến những người tiêu dùng có thu nhập cao tìm kiếm hàng hóa và dịch vụ sang trọng, trong khi Dollar General phục vụ các gia đình có thu nhập khiêm tốn hơn với các sản phẩm giá rẻ.",
    "2. <u>Làm thế nào chúng ta có thể phục vụ những khách hàng này tốt nhất (Đề xuất giá trị là gì)?</u> Công ty phải quyết định cách họ sẽ khác biệt hóa (differentiate) và định vị (position) mình trên thị trường. <strong><span class=\"text-rose-600\">Đề xuất giá trị (value proposition)</span></strong> của một thương hiệu là tập hợp các lợi ích hoặc giá trị mà nó hứa hẹn sẽ cung cấp cho người tiêu dùng để thỏa mãn nhu cầu của họ. Ví dụ, JetBlue hứa hẹn \"Đưa bạn vượt lên tất cả\" (You Above All), tập trung vào dịch vụ khách hàng tốt và tiện nghi. Trong khi đó, Spirit Airlines cung cấp \"Ít tiền hơn. Đi nhiều hơn.\" (Less Money. More Go.), nhấn mạnh giá vé cực rẻ. Thương hiệu khách sạn sang trọng Hyatt Regency lại gợi ý rằng đôi khi \"Thật tốt khi không ở nhà,\" (It’s Good Not to Be Home) nhấn mạnh trải nghiệm thú vị và thư giãn khi đi công tác hoặc du lịch.",
    "Khung chiến lược STP (Segmentation - Phân khúc, Targeting - Mục tiêu, Positioning - Định vị) chính là xương sống của mọi hoạt động marketing hiệu quả. Nó buộc các công ty phải đưa ra những lựa chọn có chủ ý về nơi họ sẽ cạnh tranh và cách họ sẽ chiến thắng, từ bỏ cách tiếp cận \"một kích cỡ cho tất cả\" để chuyển sang một mô hình cung cấp giá trị tập trung. Nếu không có STP, các nỗ lực marketing sẽ trở nên dàn trải và kém hiệu quả.",
    "<strong>B. Các Định hướng Quản trị Marketing</strong>",
    "Quản trị marketing muốn thiết kế các chiến lược nhằm thu hút khách hàng mục tiêu và xây dựng mối quan hệ lợi nhuận với họ. Có năm triết lý (định hướng) cạnh tranh mà các tổ chức có thể dựa vào để thực hiện chiến lược marketing của mình:",
    "1. <strong><span class=\"text-rose-600\">Triết lý sản xuất (Production Concept)</span></strong>: Cho rằng người tiêu dùng sẽ ưa chuộng những sản phẩm có sẵn và giá cả phải chăng; do đó, tổ chức nên tập trung vào việc cải thiện hiệu quả sản xuất và phân phối. Triết lý này hữu ích trong hai tình huống: khi nhu cầu vượt quá cung (ví dụ: PC của Lenovo tại Trung Quốc) hoặc khi chi phí sản phẩm quá cao và cần cải thiện năng suất để giảm giá. Tuy nhiên, triết lý này có thể dẫn đến thiển cận trong marketing, bỏ qua nhu cầu thực sự của khách hàng và tập trung quá mức vào hoạt động nội bộ.",
    "2. <strong><span class=\"text-rose-600\">Triết lý sản phẩm (Product Concept)</span></strong>: Cho rằng người tiêu dùng sẽ ưu tiên những sản phẩm cung cấp chất lượng, hiệu suất và tính năng sáng tạo nhất; do đó, tổ chức nên dành năng lượng để cải tiến sản phẩm liên tục. Theo triết lý này, chiến lược marketing tập trung vào việc cải tiến sản phẩm không ngừng. Tuy nhiên, điều này cũng có thể dẫn đến thiển cận, như ảo tưởng về \"chiếc bẫy chuột tốt hơn\" mà không xem xét giải pháp tổng thể mà khách hàng tìm kiếm hoặc liệu họ có thực sự muốn một chiếc bẫy chuột phức tạp hơn không. Khách hàng có thể đang tìm kiếm một giải pháp tốt hơn để diệt chuột, chứ không nhất thiết là một chiếc bẫy chuột được cải tiến.",
    "3. <strong><span class=\"text-rose-600\">Triết lý bán hàng (Selling Concept)</span></strong>: Cho rằng người tiêu dùng sẽ không mua đủ sản phẩm của công ty trừ khi công ty thực hiện những nỗ lực bán hàng và quảng bá quy mô lớn. Triết lý này thường được áp dụng với các <em><u>hàng hóa không được tìm kiếm (unsought goods)</u></em> – những thứ mà người mua thường không nghĩ đến việc mua, như bảo hiểm nhân thọ hoặc quyên góp máu. Đây là một quan điểm từ trong ra ngoài (inside-out), tập trung vào việc tạo ra các giao dịch bán hàng hơn là xây dựng mối quan hệ lâu dài và có thể mang lại rủi ro cao, vì nó tập trung vào việc bán những gì công ty tạo ra hơn là tạo ra những gì thị trường muốn.",
    "4. <strong><span class=\"text-rose-600\">Triết lý marketing (Marketing Concept)</span></strong>: Cho rằng việc đạt được các mục tiêu của tổ chức phụ thuộc vào việc biết được nhu cầu và mong muốn của thị trường mục tiêu và cung cấp sự hài lòng mong muốn một cách hiệu quả hơn so với đối thủ cạnh tranh. Đây là một triết lý lấy khách hàng làm trung tâm, \"cảm nhận và đáp ứng\" (sense and respond), theo hướng từ ngoài vào trong (outside-in). Mục tiêu là tìm đúng sản phẩm cho khách hàng, chứ không phải tìm đúng khách hàng cho sản phẩm (Hình 1.3 sẽ so sánh triết lý bán hàng và marketing). Đôi khi, điều này đòi hỏi <strong><span class=\"text-rose-600\">marketing thúc đẩy khách hàng (customer-driving marketing)</span></strong>, tức là thấu hiểu nhu cầu của khách hàng thậm chí còn tốt hơn chính họ và tạo ra các sản phẩm đáp ứng nhu cầu tiềm ẩn mà họ chưa nhận ra hoặc chưa thể diễn đạt. Ví dụ, không ai yêu cầu máy tính bảng iPad trước khi Apple giới thiệu nó.",
    "5. <strong><span class=\"text-rose-600\">Triết lý marketing xã hội (Societal Marketing Concept)</span></strong>: Cho rằng các quyết định marketing của một công ty nên xem xét mong muốn của người tiêu dùng, yêu cầu của công ty, lợi ích lâu dài của người tiêu dùng và lợi ích lâu dài của xã hội. Triết lý này kêu gọi <strong><span class=\"text-rose-600\">marketing bền vững (sustainable marketing)</span></strong>, có trách nhiệm với xã hội và môi trường, đáp ứng nhu cầu hiện tại của người tiêu dùng và doanh nghiệp đồng thời bảo tồn hoặc nâng cao khả năng của các thế hệ tương lai để đáp ứng nhu cầu của họ. Khái niệm <strong><span class=\"text-rose-600\">giá trị chia sẻ (shared value)</span></strong> – tạo ra giá trị kinh tế đồng thời tạo ra giá trị cho xã hội – ngày càng được chú trọng. Điều này còn được gọi là Marketing 3.0 (định hướng giá trị) hoặc marketing có mục đích (purpose-driven marketing). Các công ty nên cân bằng ba yếu tố: lợi nhuận công ty, mong muốn của người tiêu dùng và lợi ích xã hội (Hình 1.4 sẽ minh họa điều này). Ví dụ điển hình là Door to Door Organics, một công ty không chỉ bán thực phẩm hữu cơ mà còn cam kết tạo tác động tích cực đến hệ thống thực phẩm và sức khỏe cộng đồng thông qua các chương trình như quyên góp thực phẩm cho các ngân hàng thực phẩm địa phương.",
    "Sự tiến hóa từ các triết lý sản xuất, sản phẩm và bán hàng sang triết lý marketing và marketing xã hội phản ánh sự trưởng thành trong tư duy kinh doanh. Đó là một sự chuyển dịch lũy tiến từ góc độ tập trung vào nội bộ công ty sang góc độ tập trung vào bên ngoài – khách hàng và xã hội. Điều này cho thấy một nhận thức ngày càng tăng rằng thành công dài hạn gắn liền mật thiết với việc tạo ra giá trị rộng lớn hơn. Khái niệm \"giá trị chia sẻ\" liên kết trực tiếp nhu cầu xã hội với các cơ hội thị trường, gợi ý rằng việc giải quyết các vấn đề xã hội có thể là một nguồn gốc của sự đổi mới và tăng trưởng kinh doanh.",
    "<strong><span class=\"text-lg md:text-xl lg:text-2xl font-semibold\">C. Chuẩn bị một Chương trình và Kế hoạch Marketing Tích hợp</span></strong>",
    "Chiến lược marketing phác thảo những khách hàng nào công ty sẽ phục vụ và cách công ty sẽ tạo ra giá trị cho họ. Tiếp theo, nhà marketing phát triển một <strong><span class=\"text-rose-600\">chương trình marketing tích hợp (integrated marketing program)</span></strong> sẽ thực sự mang lại giá trị dự định cho khách hàng mục tiêu. Chương trình này chuyển đổi chiến lược marketing thành hành động.",
    "Nó bao gồm (<strong><span class=\"text-rose-600\">marketing mix</span></strong>) của công ty – một tập hợp các công cụ marketing mà công ty sử dụng để thực hiện chiến lược marketing của mình. Các công cụ chính trong marketing hỗn hợp được phân thành bốn nhóm lớn, gọi là 4Ps của marketing:",
    "<strong><span class=\"text-rose-600\">Sản phẩm (Product):</span></strong> Đề xuất thị trường đáp ứng nhu cầu (bao gồm cả dịch vụ, thương hiệu, bao bì, thiết kế, tính năng, chất lượng). Công ty cần tạo ra một đề xuất thị trường (sản phẩm) đáp ứng nhu cầu.",
    "<strong><span class=\"text-rose-600\">Giá (Price):</span></strong> Số tiền khách hàng phải trả để có được sản phẩm. Công ty phải quyết định mức giá cho sản phẩm đó.",
    "<strong><span class=\"text-rose-600\">Phân phối (Place):</span></strong> Các hoạt động giúp sản phẩm đến tay khách hàng mục tiêu (bao gồm kênh phân phối, địa điểm, hậu cần, quản lý hàng tồn kho). Công ty phải quyết định cách thức cung cấp sản phẩm cho khách hàng.",
    "<strong><span class=\"text-rose-600\">Xúc tiến (Promotion):</span></strong> Các hoạt động truyền thông về sản phẩm và thuyết phục khách hàng mục tiêu mua nó (bao gồm quảng cáo, quan hệ công chúng, bán hàng cá nhân, khuyến mãi bán hàng, marketing trực tiếp và kỹ thuật số). Công ty phải thu hút khách hàng mục tiêu, truyền đạt về sản phẩm và thuyết phục họ mua hàng.",
    "Công ty phải phối hợp từng công cụ trong marketing hỗn hợp thành một chương trình marketing tích hợp toàn diện để truyền đạt và cung cấp giá trị dự định cho các khách hàng được chọn. Một chiến lược marketing hiệu quả (STP) cung cấp bản thiết kế, và một tổ hợp marketing hỗn hợp (4Ps) được phối hợp tốt, tích hợp chặt chẽ sẽ cung cấp các công cụ để thực thi bản thiết kế đó và mang lại giá trị đã hứa cho khách hàng mục tiêu. Một yếu tố không thể thành công nếu thiếu yếu tố kia."
  ]),
};