import { PageData } from '../../types';
import { cleanParagraphs } from '../dataUtils';

const CHAPTER_1_TITLE = "Chương 1: Marketing – Tạo Giá Trị và Thu Hút Khách Hàng";

export const chap1SecVIPageData: PageData = {
  id: 'chap1-secVI',
  chapterTitle: CHAPTER_1_TITLE,
  pageTitle: "VI. Thu nhận Giá trị từ Khách hàng",
  paragraphs: cleanParagraphs([
    "Bước cuối cùng trong quy trình marketing là thu nhận lại giá trị từ khách hàng. Nếu các bước trước được thực hiện tốt, công ty sẽ gặt hái được thành quả dưới dạng lòng trung thành, doanh số, thị phần và lợi nhuận.",
    "<strong>A. Tạo dựng Lòng trung thành và Duy trì Khách hàng</strong>",
    "CRM tốt tạo ra sự hài lòng, thậm chí là sự vui thích cho khách hàng, dẫn đến lòng trung thành và sự ủng hộ tích cực. Việc giữ chân khách hàng có lợi hơn nhiều so với việc thu hút khách hàng mới. Việc mất một khách hàng đồng nghĩa với việc mất đi <strong><span class=\"text-rose-600\">giá trị trọn đời của khách hàng (customer lifetime value - CLV)</span></strong> – toàn bộ dòng chảy mua hàng mà khách hàng đó sẽ thực hiện trong suốt cuộc đời bảo trợ của họ. Ví dụ của Stew Leonard, chủ một chuỗi siêu thị, cho thấy một khách hàng không hài lòng có thể gây thiệt hại 50.000 USD doanh thu trọn đời. Nghiên cứu cho thấy việc tăng tỷ lệ giữ chân khách hàng chỉ 5% có thể tăng lợi nhuận từ 25% đến 95%.",
    "Sự vui thích của khách hàng, vượt trên cả sự hài lòng đơn thuần, là một động lực mạnh mẽ của lòng trung thành và sự ủng hộ. Nó tạo ra một kết nối cảm xúc vượt qua sở thích lý trí. CRM tốt tạo ra \"sự hài lòng của khách hàng\", nhưng mục tiêu là \"sự vui thích của khách hàng\". Những khách hàng vui thích không chỉ mua hàng lặp lại mà còn là \"những đối tác truyền miệng sẵn lòng\" (willing apostles), tích cực quảng bá thương hiệu cho người khác. Điều này cho thấy sự vui thích tạo ra một mối ràng buộc tình cảm, biến khách hàng thành những người ủng hộ chứ không chỉ là người mua. Mối ràng buộc tình cảm này khó bị đối thủ cạnh tranh phá vỡ hơn so với một mối quan hệ thuần túy giao dịch.",
    "<strong>B. Giá trị Trọn đời của Khách hàng (Customer Lifetime Value - CLV)</strong>",
    "<strong><span class=\"text-rose-600\">CLV</span></strong> là giá trị của toàn bộ dòng mua hàng mà một khách hàng thực hiện trong suốt cuộc đời bảo trợ. Ví dụ, Lexus ước tính CLV của một khách hàng trung thành là 600.000 USD, còn Starbucks là hơn 25.000 USD (con số này có thể thay đổi tùy theo nguồn và cách tính). Việc tập trung vào CLV khuyến khích các nhà tiếp thị đầu tư vào các hoạt động xây dựng mối quan hệ có thể không mang lại lợi nhuận ngay lập tức nhưng đảm bảo giá trị khách hàng lâu dài. Đây là một thước đo quan trọng để đánh giá hiệu quả của các chiến lược marketing và CRM.",
    "<strong>C. Gia tăng Tỷ lệ Tiêu dùng của Khách hàng (Growing Share of Customer)</strong>",
    "Ngoài việc giữ chân khách hàng, các công ty còn đặt mục tiêu giành được <strong><span class=\"text-rose-600\">tỷ lệ tiêu dùng của khách hàng (share of customer)</span></strong> lớn hơn – tức là phần chi tiêu của khách hàng trong các danh mục sản phẩm của công ty. Các công ty có thể cung cấp sự đa dạng hơn, bán chéo (cross-sell) và bán thêm (up-sell). Amazon là một bậc thầy trong lĩnh vực này, liên tục mở rộng các mặt hàng từ sách sang điện tử, đồ gia dụng, thực phẩm, và sử dụng các đề xuất được cá nhân hóa (\"Khách hàng mua mặt hàng này cũng đã mua...\") để thúc đẩy mua hàng thêm. Ngân hàng có thể muốn tăng \"tỷ lệ ví tiền\" của khách hàng bằng cách cung cấp thêm các dịch vụ như thế chấp, đầu tư, bảo hiểm. Mối quan hệ khách hàng bền chặt (được xây dựng thông qua CRM và sự gắn kết) dẫn đến sự tin cậy cao hơn, khiến khách hàng dễ tiếp nhận việc mua một loạt sản phẩm/dịch vụ rộng hơn từ công ty, từ đó làm tăng tỷ lệ tiêu dùng của khách hàng.",
    "<strong>D. Xây dựng Tổng Giá trị Vòng đời Khách hàng và các Nhóm Quan hệ Khách hàng</strong>",
    "Mục tiêu cuối cùng của CRM là tạo ra <strong><span class=\"text-rose-600\">tổng giá trị vòng đời khách hàng (customer equity)</span></strong> cao. Đây là tổng hợp giá trị trọn đời của tất cả các khách hàng hiện tại và tiềm năng của công ty; nó là một thước đo giá trị tương lai của cơ sở khách hàng của công ty. Trong khi thị phần và doanh số phản ánh quá khứ và hiện tại, tổng giá trị vòng đời khách hàng dự đoán tương lai. Ví dụ so sánh giữa Cadillac và BMW minh họa tầm quan trọng của tổng giá trị vòng đời khách hàng so với thị phần hiện tại: Cadillac từng có thị phần cao nhưng khách hàng già đi và ít trung thành hơn, trong khi BMW thu hút khách hàng trẻ hơn với CLV cao hơn, dẫn đến tăng trưởng và lợi nhuận bền vững hơn sau này.",
    "Các công ty cần quản lý khách hàng như những tài sản. Tuy nhiên, không phải tất cả khách hàng đều mang lại giá trị như nhau. Khách hàng có thể được phân loại thành các nhóm dựa trên khả năng sinh lời tiềm năng và lòng trung thành dự kiến (Hình 1.5 sẽ minh họa một ma trận phân loại khách hàng):",
    "1. <em>Người lạ (Strangers)</em>: Khả năng sinh lời - Thấp. Dự đoán trung thành - Ngắn hạn. Có ít sự phù hợp giữa sản phẩm của công ty và nhu cầu của họ. Chiến lược quản trị quan hệ: Không đầu tư nhiều; tạo lợi nhuận trên mỗi giao dịch.",
    "2. <em>Bươm bướm (Butterflies)</em>: Khả năng sinh lời - Cao. Dự đoán trung thành - Ngắn hạn. Có sự phù hợp tốt nhưng họ có thể chuyển sang đối thủ cạnh tranh một cách dễ dàng. Chiến lược quản trị quan hệ: Nỗ lực thỏa mãn và tạo lợi nhuận trong thời gian ngắn họ còn ở lại; sau đó ngừng đầu tư cho đến lần tiếp theo. Tận hưởng họ trong khoảnh khắc.",
    "3. <em>Bạn tốt (True Friends)</em>: Khả năng sinh lời - Cao. Dự đoán trung thành - Dài hạn. Có sự phù hợp mạnh mẽ. Chiến lược quản trị quan hệ: Đầu tư liên tục để giữ chân và phát triển họ; biến họ thành những người ủng hộ trung thành (true believers) cho thương hiệu.",
    "4. <em>Kẻ đeo bám (Barnacles)</em>: Khả năng sinh lời - Thấp. Dự đoán trung thành - Dài hạn. Rất trung thành nhưng không chi tiêu nhiều. Họ tạo ra lực cản. Chiến lược quản trị quan hệ: Cố gắng tăng khả năng sinh lời của họ (bán thêm, tăng phí, giảm dịch vụ); nếu không được, có thể cần \"sa thải\" họ một cách tế nhị.",
    "Khái niệm \"sa thải\" những khách hàng (nhóm Kẻ đeo bám) có vẻ phản trực giác nhưng lại hợp lý về mặt chiến lược. Nó nhấn mạnh rằng nguồn lực marketing là hữu hạn và nên được đầu tư vào nơi mang lại lợi tức cao nhất về mặt tổng giá trị vòng đời khách hàng. Tổng giá trị vòng đời khách hàng là tổng của tất cả các CLV. Mục tiêu là tối đa hóa con số này. \"Kẻ đeo bám\" là những khách hàng trung thành nhưng có khả năng sinh lời thấp. Việc phục vụ họ có thể tốn kém hơn doanh thu mà họ tạo ra, do đó làm giảm tổng giá trị vòng đời khách hàng chung. Nếu không thể tăng khả năng sinh lời của họ (ví dụ, bằng cách bán thêm các sản phẩm/dịch vụ có lợi nhuận cao hơn hoặc tăng giá), việc thoái lui khỏi những mối quan hệ này cho phép công ty chuyển hướng nguồn lực sang những \"Bạn tốt\" có lợi hơn hoặc những \"Bươm bướm\" hay \"Dấu hỏi\" (theo ma trận BCG) có tiềm năng lợi nhuận. Do đó, việc lựa chọn thoái vốn khỏi những khách hàng không mang lại lợi nhuận cao, một cách nghịch lý, có thể làm tăng tổng giá trị vòng đời khách hàng tổng thể."
  ]),
};