import { PageData } from '../../types';
import { cleanParagraphs } from '../dataUtils';

const CHAPTER_1_TITLE = "Chương 1: Marketing – Tạo Giá Trị và Thu Hút Khách Hàng";

export const chap1SecVIIPageData: PageData = {
  id: 'chap1-secVII',
  chapterTitle: CHAPTER_1_TITLE,
  pageTitle: "VII. Bối cảnh Marketing Không ngừng Thay đổi",
  paragraphs: cleanParagraphs([
    "Marketing không diễn ra trong một môi trường tĩnh tại. Các nhà marketing phải liên tục theo dõi và thích ứng với những thay đổi lớn trong bối cảnh hoạt động của mình. Năm lực lượng chính đang định hình lại bối cảnh marketing:",
    "<strong>A. Kỷ nguyên Số: Marketing Trực tuyến, Di động và Qua phương tiện Truyền thông Xã hội</strong>",
    "Sự bùng nổ của công nghệ số (Internet, điện thoại thông minh, máy tính bảng, TV thông minh, Internet Vạn Vật - IoT) đã cách mạng hóa cách con người sống, giao tiếp, học hỏi, làm việc và mua sắm. Người tiêu dùng ngày càng gắn bó với các thiết bị kỹ thuật số, dành nhiều thời gian hơn trực tuyến và trên các ứng dụng di động. Marketing số và qua phương tiện truyền thông xã hội sử dụng các công cụ kỹ thuật số để thu hút người tiêu dùng mọi lúc, mọi nơi thông qua máy tính, điện thoại thông minh, máy tính bảng, thiết bị kết nối Internet và các nền tảng kỹ thuật số khác.",
    "<em>Marketing qua phương tiện truyền thông xã hội:</em> Các nền tảng lớn (Facebook, Instagram, Twitter, YouTube, Pinterest, Snapchat, LinkedIn) và các nền tảng chuyên biệt hơn cung cấp cơ hội tương tác và tạo ra các cuộc thảo luận về thương hiệu. Đây là nền tảng lý tưởng cho <strong><span class=\"text-rose-600\">marketing theo thời gian thực (real-time marketing)</span></strong>, kết nối thương hiệu với các sự kiện và xu hướng hiện tại một cách kịp thời và phù hợp (ví dụ: chiến dịch \"Dunk in the Dark\" của Oreo trong sự kiện mất điện Super Bowl, cách NASA sử dụng mạng xã hội để tạo sự phấn khích cho các sứ mệnh không gian).",
    "<em>Marketing trên thiết bị di động:</em> Là nền tảng marketing số phát triển nhanh nhất. Điện thoại thông minh luôn bên người, mang tính cá nhân cao và có thể nhắm mục tiêu dựa trên vị trí. Các nhà marketing sử dụng kênh di động để kích thích mua hàng ngay lập tức, làm cho việc mua sắm dễ dàng hơn, làm phong phú trải nghiệm thương hiệu và cung cấp các ưu đãi, thông tin phù hợp với ngữ cảnh (ví dụ: ứng dụng và câu lạc bộ tin nhắn của Redbox cung cấp các ưu đãi dựa trên vị trí và lịch sử thuê phim).",
    "Kỷ nguyên số đã tạo ra một <strong><span class=\"text-rose-600\">\"cơn lũ dữ liệu\" (data deluge)</span></strong> từ hàng tỷ tương tác trực tuyến và di động mỗi ngày. Các công ty hiện có thể thu thập lượng lớn dữ liệu về người tiêu dùng. Nếu được khai thác hiệu quả thông qua phân tích <strong><span class=\"text-rose-600\">Dữ liệu lớn (Big Data)</span></strong>, dữ liệu này cho phép cá nhân hóa và đáp ứng theo thời gian thực ở mức độ chưa từng có trong marketing. Các tương tác kỹ thuật số (trang web, mạng xã hội, ứng dụng di động) tạo ra lượng lớn dữ liệu khách hàng. Phân tích dữ liệu này giúp hiểu sở thích, hành vi và bối cảnh thời gian thực của từng cá nhân, cho phép các nhà tiếp thị cung cấp thông điệp, ưu đãi và trải nghiệm được cá nhân hóa cao (ví dụ: Redbox nhắm mục tiêu dựa trên tương tác di động). <strong><span class=\"text-rose-600\">Marketing theo thời gian thực</span></strong> là một kết quả trực tiếp của khả năng này. Tuy nhiên, việc thu thập và sử dụng dữ liệu cá nhân chi tiết như vậy cũng đặt ra các trách nhiệm đạo đức và nguy cơ phản ứng tiêu cực từ người tiêu dùng nếu quyền riêng tư bị xâm phạm hoặc dữ liệu bị lạm dụng. Do đó, sức mạnh của marketing kỹ thuật số phải được cân bằng với việc quản lý dữ liệu có đạo đức và minh bạch.",
    "<strong>B. Môi trường Kinh tế Thay đổi</strong>",
    "Cuộc Đại suy thoái 2008-2009 và những biến động kinh tế sau đó đã khiến người tiêu dùng xem xét lại ưu tiên mua sắm và áp dụng lối sống tiết kiệm hơn, ngay cả sau khi kinh tế phục hồi. Mặc dù nền kinh tế Mỹ đã cải thiện, người tiêu dùng vẫn tiếp tục tìm kiếm giá trị lớn hơn cho đồng tiền của họ. Các nhà marketing đã đáp lại bằng cách nhấn mạnh vào giá trị đồng tiền, tính thực tế và độ bền của sản phẩm. Ví dụ, Target đã điều chỉnh thông điệp của mình từ \"Expect More. Pay Less.\" (Mong đợi nhiều hơn. Trả tiền ít hơn.) sang việc tập trung hơn vào khía cạnh \"Trả tiền ít hơn\" trong thời kỳ suy thoái, và sau đó nhấn mạnh sự cân bằng giữa phong cách và tiết kiệm.",
    "Sự bất ổn kinh tế có thể thúc đẩy nhu cầu về \"giá trị\" theo nghĩa rộng nhất, không chỉ là giá thấp mà là sự kết hợp đúng đắn giữa chất lượng sản phẩm và dịch vụ tốt với một mức giá hợp lý. Suy thoái khiến người tiêu dùng thận trọng hơn và tập trung vào \"tiêu dùng hợp lý\". Điều này không nhất thiết có nghĩa là mua hàng rẻ nhất, mà là tìm kiếm \"giá trị tốt hơn cho đồng tiền\". Các nhà tiếp thị phản ứng bằng cách nhấn mạnh \"giá trị trong các đề xuất giá trị của họ\". Điều này cho thấy rằng trong thời kỳ kinh tế suy thoái, tính hữu dụng và độ tin cậy của sản phẩm/dịch vụ trở nên quan trọng hơn so với các thuộc tính khát vọng hoặc dựa trên hình ảnh đối với nhiều người tiêu dùng. Các thương hiệu có thể trình bày và cung cấp rõ ràng cảm giác giá trị nâng cao này sẽ có vị thế tốt hơn. Ngay cả trong thời kỳ phục hồi, nhiều người tiêu dùng vẫn giữ thói quen chi tiêu cẩn trọng hơn.",
    "<strong>C. Sự phát triển của Marketing Phi lợi nhuận</strong>",
    "Marketing ngày càng trở nên quan trọng đối với các tổ chức phi lợi nhuận (trường đại học, bệnh viện, bảo tàng, dàn nhạc giao hưởng, nhà thờ, tổ chức từ thiện) trong việc thu hút thành viên, quỹ và sự hỗ trợ. Ví dụ như Bệnh viện Nhi St. Jude sử dụng marketing để huy động hàng tỷ đô la mỗi năm, và Quỹ Quốc tế Bảo vệ Thiên nhiên (WWF) với chiến dịch #LastSelfie thành công của mình để nâng cao nhận thức về các loài có nguy cơ tuyệt chủng. Các cơ quan chính phủ cũng sử dụng marketing cho các chiến dịch xã hội như chống hút thuốc, tiết kiệm năng lượng, hoặc thúc đẩy du lịch. Việc áp dụng các nguyên tắc marketing trong lĩnh vực phi lợi nhuận cho thấy tính phổ quát của các khái niệm marketing trong việc ảnh hưởng đến hành vi và đạt được các mục tiêu của tổ chức, cho dù đó là mục tiêu tài chính hay xã hội.",
    "<strong>D. Toàn cầu hóa Nhanh chóng</strong>",
    "Thế giới ngày càng trở nên nhỏ bé hơn. Các công ty thuộc mọi quy mô ngày càng bị ảnh hưởng bởi cạnh tranh và cơ hội toàn cầu. Nhiều công ty đang phát triển các sản phẩm toàn cầu hơn, tìm nguồn cung ứng toàn cầu và bán hàng trên toàn thế giới. Các nhà marketing đang có cái nhìn toàn cầu hơn về ngành, đối thủ và cơ hội của họ. Các thương hiệu lớn như McDonald's, Nike, Coca-Cola có doanh thu đáng kể từ thị trường quốc tế, thường vượt xa doanh thu nội địa. Toàn cầu hóa đòi hỏi sự nhạy cảm văn hóa và khả năng thích ứng trong các chiến lược marketing. Một cách tiếp cận \"một kích cỡ cho tất cả\" hiếm khi hiệu quả trên các thị trường quốc tế đa dạng. Các công ty phải hiểu sự khác biệt về văn hóa, kinh tế, chính trị và pháp lý khi hoạt động ở nước ngoài.",
    "<strong>E. Marketing Bền vững – Trách nhiệm Xã hội và Môi trường</strong>",
    "Các nhà marketing đang xem xét lại mối quan hệ của họ với các giá trị xã hội, trách nhiệm và hành tinh. Đạo đức doanh nghiệp và trách nhiệm xã hội là những vấn đề then chốt khi các phong trào bảo vệ người tiêu dùng và môi trường trên toàn thế giới ngày càng trưởng thành. Có một lời kêu gọi ngày càng tăng đối với marketing bền vững – đáp ứng nhu cầu hiện tại trong khi vẫn bảo tồn hoặc nâng cao khả năng của các thế hệ tương lai để đáp ứng nhu cầu của họ. Một số công ty thực hành <strong><span class=\"text-rose-600\">\"chủ nghĩa tư bản có tâm\" (caring capitalism)</span></strong>, tích hợp trách nhiệm xã hội và môi trường vào giá trị cốt lõi và mục đích của họ (ví dụ: Patagonia, Ben & Jerry's, The Body Shop). Họ coi việc làm điều đúng đắn không chỉ là một nghĩa vụ mà còn là một cơ hội.",
    "<strong><span class=\"text-rose-600\">Marketing bền vững</span></strong> đang phát triển từ một mối quan tâm ngách hoặc một chiến thuật PR thành một nguồn tiềm năng của lợi thế cạnh tranh và sự đổi mới. Các công ty thực sự gắn kết tính bền vững vào mô hình kinh doanh cốt lõi của họ có thể xây dựng danh tiếng thương hiệu mạnh mẽ hơn, thu hút nhân tài, nuôi dưỡng lòng trung thành của khách hàng và thậm chí khám phá các cơ hội thị trường mới. Ngày càng có nhiều yêu cầu xã hội về trách nhiệm của doanh nghiệp. Một số công ty đón nhận điều này như một \"cơ hội để làm tốt bằng cách làm điều tốt\". \"Chủ nghĩa tư bản có tâm\" gợi ý một mô hình kinh doanh nơi lợi ích xã hội/môi trường là không thể thiếu, không phải là một phần phụ thêm. Nhiệm vụ ba phần của Ben & Jerry's (sản phẩm, kinh tế, xã hội) minh họa cho sự tích hợp này. Sự tích hợp này có thể dẫn đến những đổi mới sản phẩm (ví dụ: tìm nguồn cung ứng bền vững, sản phẩm thân thiện với môi trường), hiệu quả hoạt động (ví dụ: giảm thiểu chất thải, tiết kiệm năng lượng) và nâng cao sức hấp dẫn thương hiệu đối với những người tiêu dùng có ý thức. Do đó, tính bền vững không chỉ là chi phí hay hạn chế mà có thể là động lực của giá trị và sự khác biệt hóa lâu dài."
  ]),
};