import { PageData } from '../../types';
import { cleanParagraphs } from '../dataUtils';

const CHAPTER_1_TITLE = "Chương 1: Marketing – Tạo Giá Trị và Thu Hút Khách Hàng";

export const chap1SecVPageData: PageData = {
  id: 'chap1-secV',
  chapterTitle: CHAPTER_1_TITLE,
  pageTitle: "V. Quản trị Quan hệ Khách hàng và Thu nhận Giá trị Khách hàng (Bước 4 & 5)",
  paragraphs: cleanParagraphs([
    "Ba bước đầu tiên của quy trình marketing – thấu hiểu thị trường và nhu cầu khách hàng, thiết kế chiến lược marketing hướng đến giá trị khách hàng, và xây dựng chương trình marketing – đều dẫn đến bước thứ tư và thứ năm quan trọng nhất: thu hút khách hàng, quản trị các mối quan hệ khách hàng có lợi nhuận và thu nhận giá trị từ họ.",
    "<strong>A. Quản trị Quan hệ Khách hàng (Customer Relationship Management - CRM)</strong>",
    "<strong><span class=\"text-rose-600\">Quản trị quan hệ khách hàng (Customer Relationship Management - CRM)</span></strong> có lẽ là khái niệm quan trọng nhất của marketing hiện đại. Theo nghĩa rộng nhất, <strong><span class=\"text-rose-600\">CRM</span></strong> là toàn bộ quá trình xây dựng và duy trì các mối quan hệ khách hàng có lợi nhuận bằng cách mang đến sự hài lòng cùng giá trị khách hàng vượt trội. Nó liên quan đến tất cả các khía cạnh của việc tìm kiếm, thu hút và phát triển khách hàng.",
    "<em><u>Các khối xây dựng mối quan hệ: Giá trị và Sự hài lòng của Khách hàng:</u></em> Đây là chìa khóa để xây dựng mối quan hệ khách hàng lâu dài. Những khách hàng hài lòng có nhiều khả năng là khách hàng trung thành và chia sẻ những trải nghiệm tốt của họ với những người tiêu dùng khác.",
    "<em>Giá trị được nhận thức bởi khách hàng:</em> Như đã thảo luận, đây là đánh giá của khách hàng về sự khác biệt giữa lợi ích và chi phí so với đối thủ. Khách hàng thường không đánh giá giá trị và chi phí một cách \"chính xác\" hay \"khách quan\". Họ hành động dựa trên giá trị cảm nhận. Ví dụ về đàn piano Steinway cho thấy giá trị cảm nhận có thể vượt xa giá cả vật chất, bao gồm cả trải nghiệm sở hữu, uy tín thương hiệu và yếu tố thần bí. Với nhiều khách hàng, giá trị của một chiếc Steinway thực sự là vô giá.",
    "<em>Sự hài lòng của khách hàng:</em> Phụ thuộc vào sự tương quan giữa hiệu suất sản phẩm và kỳ vọng. Nếu hiệu suất sản phẩm thấp hơn kỳ vọng, khách hàng sẽ không hài lòng. Nếu hiệu suất khớp với kỳ vọng, khách hàng sẽ hài lòng. Nếu hiệu suất vượt quá kỳ vọng, khách hàng sẽ rất hài lòng hoặc vui sướng. Các công ty như L.L.Bean xây dựng văn hóa làm hài lòng khách hàng, thậm chí là làm họ vui sướng bằng cách vượt trên cả kỳ vọng, dẫn đến lòng trung thành cao và sự ủng hộ mạnh mẽ.",
    "<em><u>Các cấp độ và công cụ của mối quan hệ khách hàng:</u></em> Các công ty xây dựng mối quan hệ ở nhiều cấp độ. Với số lượng lớn khách hàng lợi nhuận thấp (ví dụ: người tiêu dùng xà phòng Tide của P&G), công ty phát triển mối quan hệ cơ bản qua trải nghiệm sản phẩm, quảng cáo thương hiệu và truyền thông đại chúng. Với số ít khách hàng lợi nhuận cao (ví dụ: P&G với các nhà bán lẻ lớn như Walmart, Kroger), công ty xây dựng quan hệ đối tác đầy đủ. Các công cụ như <strong><span class=\"text-rose-600\">chương trình khách hàng thường xuyên (FMPs)</span></strong> và chương trình khách hàng thân thiết (ví dụ: TrueBlue của JetBlue, Starbucks Rewards) được sử dụng để tăng cường sự gắn kết, thưởng cho những khách hàng mua thường xuyên hoặc với số lượng lớn. Ngoài ra, các công ty có thể tài trợ cho các câu lạc bộ khách hàng, tạo cộng đồng thương hiệu trực tuyến hoặc tổ chức các sự kiện đặc biệt.",
    "CRM không chỉ là một công nghệ hay một bộ phận; đó là một triết lý và quy trình xuyên suốt toàn công ty. Thành công của nó phụ thuộc vào việc thực hiện nhất quán lời hứa thương hiệu tại mọi điểm tiếp xúc với khách hàng. Văn hóa dịch vụ khách hàng của L.L.Bean, được mô tả là \"ăn sâu bén rễ\" và là một \"hoạt động hàng ngày, liên tục, không bao giờ ngừng nghỉ, bền bỉ và thể hiện lòng trắc ẩn\", cho thấy đây là một cam kết chiến lược được dệt nên trong cơ cấu của tổ chức, chứ không chỉ là một chiến thuật marketing cụ thể.",
    "<strong>B. Marketing Gắn kết Khách hàng</strong>",
    "Trong kỷ nguyên số, các công ty đang chuyển từ marketing đại chúng sang các phương pháp tương tác sâu hơn. <strong><span class=\"text-rose-600\">Marketing gắn kết khách hàng (Customer engagement marketing)</span></strong> là việc làm cho thương hiệu trở thành một phần có ý nghĩa trong các cuộc đối thoại và cuộc sống của người tiêu dùng bằng cách thúc đẩy sự tham gia trực tiếp và liên tục của khách hàng vào việc định hình các cuộc đối thoại về thương hiệu, trải nghiệm thương hiệu và cộng đồng thương hiệu. Đây không chỉ là việc marketing <em><u>đến</u></em> người tiêu dùng, mà là marketing <em><u>cùng với</u></em> họ. Mục tiêu là làm cho thương hiệu trở thành một phần có ý nghĩa trong các cuộc trò chuyện và cuộc sống của người tiêu dùng.",
    "Sự phát triển mạnh mẽ của Internet và truyền thông xã hội đã tạo điều kiện thuận lợi cho marketing gắn kết. Khách hàng ngày nay được thông tin tốt hơn, kết nối nhiều hơn và có nhiều quyền lực hơn. Họ có thể dễ dàng chia sẻ trải nghiệm thương hiệu và ảnh hưởng đến người khác thông qua các bài đánh giá trực tuyến, blog, video và mạng xã hội. Điều này dẫn đến các mối quan hệ do khách hàng quản lý, nơi khách hàng tự kết nối với công ty và với nhau để tạo ra và chia sẻ trải nghiệm thương hiệu của riêng họ. Các nhà marketing phải chuyển từ <strong><span class=\"text-rose-600\">marketing xâm nhập (intrusion marketing)</span></strong> sang <strong><span class=\"text-rose-600\">marketing bằng sự hấp dẫn (attraction marketing)</span></strong>, tạo ra các thông điệp và đề xuất thị trường thu hút khách hàng thay vì làm gián đoạn họ. Các thương hiệu hiện diện trên Twitter, Facebook, YouTube, Instagram, và các blog (ví dụ: thương hiệu Life is good với trang Facebook sôi động) để tương tác ở mức độ cá nhân hơn, lắng nghe và trả lời các cuộc trò chuyện của khách hàng.",
    "Một hình thức của marketing gắn kết là <strong><span class=\"text-rose-600\">marketing do khách hàng tạo lập (customer-generated marketing)</span></strong>, nơi chính người tiêu dùng đóng vai trò ngày càng tăng trong việc định hình trải nghiệm thương hiệu của họ và của những người tiêu dùng khác. Điều này có thể xảy ra thông qua các blog, trang chia sẻ video, mạng xã hội và các diễn đàn trực tuyến. Nhiều công ty mời khách hàng đóng góp ý tưởng sản phẩm (LEGO Ideas, My Starbucks Idea) hoặc tạo nội dung quảng cáo (cuộc thi \"Crash the Super Bowl\" của Doritos, chiến dịch Baja Blast của Mountain Dew). Tuy nhiên, việc này có thể tốn kém, khó kiểm soát và đôi khi phản tác dụng nếu nội dung tiêu cực lan truyền (ví dụ: chiến dịch #McDStories của McDonald's). Dù vậy, tiềm năng của marketing do khách hàng tạo lập là rất lớn khi được quản lý tốt.",
    "Sự trỗi dậy của marketing gắn kết khách hàng và nội dung do khách hàng tạo ra báo hiệu một sự thay đổi quyền lực cơ bản từ nhà tiếp thị sang người tiêu dùng. Thương hiệu không còn được xây dựng đơn độc bởi các công ty mà được đồng sáng tạo cùng với khán giả của họ. Điều này đòi hỏi một tư duy mới về việc từ bỏ một phần quyền kiểm soát và chấp nhận sự hợp tác đích thực. Nếu trước đây marketing là việc \"tiếp thị thương hiệu đến người tiêu dùng\", thì nay là \"marketing gắn kết khách hàng\" thúc đẩy \"sự tham gia trực tiếp và liên tục của khách hàng\". Khách hàng \"được thông tin nhiều hơn, kết nối nhiều hơn và được trao quyền nhiều hơn\", và họ \"đóng vai trò ngày càng tăng trong việc định hình trải nghiệm thương hiệu của chính họ và của những người tiêu dùng khác\". Điều này có nghĩa là các thương hiệu không còn là tác giả duy nhất của câu chuyện của họ; người tiêu dùng là những người tham gia tích cực và đồng tác giả. Sự thay đổi này đòi hỏi sự minh bạch, tính xác thực và sẵn sàng lắng nghe, phản hồi tiếng nói của khách hàng, ngay cả những lời phê bình.",
    "<strong>C. Quản trị Quan hệ Đối tác (Partner Relationship Management)</strong>",
    "Để tạo ra giá trị khách hàng và xây dựng mối quan hệ khách hàng, các nhà marketing không thể hành động một mình. Họ phải thực hiện tốt <strong><span class=\"text-rose-600\">quản trị quan hệ đối tác (partner relationship management)</span></strong> – hợp tác chặt chẽ với các đối tác khác bên trong công ty (các phòng ban khác như tài chính, kế toán, sản xuất, R&D, nhân sự) và bên ngoài công ty (nhà cung cấp, nhà phân phối, nhà bán lẻ) để cùng nhau mang lại giá trị lớn hơn cho khách hàng.",
    "<em>Đối tác nội bộ:</em> Mỗi phòng ban trong công ty là một mắt xích trong <strong><span class=\"text-rose-600\">chuỗi giá trị (value chain)</span></strong> nội bộ của công ty. Sự hợp tác đa chức năng là rất cần thiết để đảm bảo mọi người đều tập trung vào việc tạo ra giá trị cho khách hàng. Ví dụ, bộ phận marketing cần hợp tác với bộ phận CNTT để phát triển các công cụ CRM, với bộ phận tài chính để đảm bảo nguồn lực, và với bộ phận sản xuất để đảm bảo sản phẩm đáp ứng kỳ vọng.",
    "<em>Đối tác bên ngoài:</em> Bao gồm các nhà cung cấp và các kênh marketing (nhà phân phối, nhà bán lẻ). Quản trị chuỗi cung ứng (supply chain) và <strong><span class=\"text-rose-600\">mạng lưới phân phối giá trị (value delivery network)</span></strong> là rất quan trọng. Các công ty ngày càng coi các nhà cung cấp và nhà phân phối là đối tác trong việc cung cấp giá trị, thay vì chỉ là các bên giao dịch. Ví dụ, McDonald's phụ thuộc rất nhiều vào mạng lưới các nhà cung cấp và đối tác nhượng quyền để đảm bảo chất lượng và tính nhất quán trên toàn cầu.",
    "Quản trị quan hệ đối tác mở rộng khái niệm lấy khách hàng làm trung tâm ra ngoài phạm vi bộ phận marketing, đến toàn bộ tổ chức và hệ sinh thái bên ngoài của nó. Nó thừa nhận rằng việc cung cấp giá trị khách hàng vượt trội là một trách nhiệm chung. Marketing một mình không thể tạo ra giá trị khách hàng vượt trội. Nội bộ, tất cả các phòng ban phải làm việc cùng nhau trong một \"chuỗi giá trị\". Bên ngoài, các công ty phải hợp tác với các nhà cung cấp và đối tác kênh trong một \"mạng lưới phân phối giá trị\". Sự thành công của trải nghiệm khách hàng cuối cùng phụ thuộc vào hiệu suất của toàn bộ mạng lưới này. Do đó, việc xây dựng mối quan hệ bền chặt với các đối tác nội bộ và bên ngoài cũng quan trọng như việc xây dựng mối quan hệ bền chặt với khách hàng."
  ]),
};