import { PageData } from '../../types';
import { cleanParagraphs } from '../dataUtils';

const CHAPTER_4_TITLE = "Chương 4: Quản trị Thông tin Marketing để Thấu hiểu Khách hàng";

export const chap4SecIPageData: PageData = {
  id: 'chap4-secI',
  chapterTitle: CHAPTER_4_TITLE,
  pageTitle: "I. Giới thiệu: Tầm quan trọng của Thông tin Marketing và Thấu hiểu Khách hàng",
  paragraphs: cleanParagraphs([
    "<strong>A. Vai trò của thông tin trong việc đạt được sự thấu hiểu sâu sắc về thị trường và khách hàng</strong><br/>Trong bối cảnh thị trường hiện đại, việc thấu hiểu sâu sắc người tiêu dùng và thị trường là yếu tố then chốt quyết định sự thành công của doanh nghiệp. Chương này tập trung khám phá cách thức các chuyên gia marketing đạt được sự thấu hiểu này, cũng như cách các doanh nghiệp phát triển và quản lý thông tin về những yếu tố thị trường quan trọng như khách hàng, đối thủ cạnh tranh và các chương trình marketing. Để thành công, doanh nghiệp phải có khả năng biến khối lượng thông tin marketing khổng lồ thành những hiểu biết mới mẻ, sâu sắc về khách hàng, từ đó giúp doanh nghiệp gắn kết hiệu quả hơn và mang lại giá trị lớn hơn cho họ. Điều này không chỉ đơn thuần là thu thập dữ liệu, mà quan trọng hơn là quá trình chuyển hóa dữ liệu đó thành những洞察 (thấu hiểu) có thể hành động được.",
    "Minh chứng điển hình cho tầm quan trọng của việc thấu hiểu khách hàng thông qua quản trị thông tin marketing là câu chuyện của Tập đoàn LEGO. Công ty đã thành lập Nhóm Nghiên cứu Toàn cầu và áp dụng các phương pháp nghiên cứu sáng tạo như phương pháp nhập vai và quan sát thực địa để hiểu rõ hơn về cách trẻ em thực sự chơi đùa. Quá trình này đã mang lại những \"Khoảnh khắc Aha\" – những phát hiện bất ngờ làm thay đổi hoàn toàn triết lý sản phẩm của LEGO. Từ những bộ đồ chơi xây dựng đơn giản, LEGO đã chuyển hướng sang phát triển các bộ sản phẩm phức tạp hơn, có chủ đề rõ ràng, thậm chí kết hợp công nghệ cao như dòng sản phẩm LEGO MINDSTORMS (robot tùy chỉnh lập trình được) và LEGO Fusion (kết hợp trò chơi số và thế giới thực). Nghiên cứu cũng chỉ ra sự khác biệt trong cách chơi của bé trai và bé gái, dẫn đến sự ra đời của dòng sản phẩm LEGO Friends hướng đến các bé gái. Không chỉ dừng lại ở đó, LEGO còn tích cực tương tác và đồng sáng tạo với cộng đồng người hâm mộ trưởng thành (AFOLs), mời họ tham gia trực tiếp vào quá trình phát triển sản phẩm. Kết quả là LEGO không chỉ tự giải cứu mình khỏi bờ vực phá sản mà còn vươn lên trở thành nhà sản xuất đồ chơi lớn nhất thế giới.",
    "Câu chuyện của LEGO cho thấy nghiên cứu marketing không chỉ là một chức năng hỗ trợ mà đã trở thành một yêu cầu chiến lược bắt buộc để tồn tại và phát triển, đặc biệt khi đối mặt với những thay đổi đột phá của thị trường, ví dụ như tác động của số hóa lên ngành đồ chơi truyền thống. LEGO đã \"gần như bị phá sản\" chính vì \"thất bại trong việc kết nối với khách hàng\", và sự phục hồi của họ bắt nguồn từ việc \"kết nối lại với khách hàng\" thông qua \"rất nhiều nghiên cứu marketing\". Điều này minh chứng mối quan hệ nhân quả trực tiếp giữa việc thiếu hiểu biết về khách hàng và sự suy giảm kinh doanh, và ngược lại, giữa việc đầu tư vào nghiên cứu để có được thấu hiểu và sự thành công của doanh nghiệp.",
    "Thành công của các sản phẩm như MINDSTORMS và Fusion, xuất phát từ việc LEGO nhận ra rằng \"trẻ em không còn phân biệt giữa trò chơi số và trò chơi đồ vật thông thường\" , cho thấy thông tin marketing hiệu quả phải nắm bắt được những mô hình hành vi đang phát triển và sự xóa nhòa ranh giới giữa trải nghiệm vật lý và kỹ thuật số. Đây là một xu hướng vượt xa ngành công nghiệp đồ chơi. Nghiên cứu đã tiết lộ một sự thay đổi cơ bản trong cách trẻ em chơi, vượt qua những giả định truyền thống của LEGO, và sự thấu hiểu này đã trực tiếp dẫn đến các dòng sản phẩm sáng tạo tích hợp công nghệ, chứng tỏ thông tin marketing phải mang tính tương lai và thích ứng với những thay đổi hành vi.",
    "Hơn nữa, việc LEGO tương tác với cộng đồng AFOLs để đồng sáng tạo sản phẩm làm nổi bật sức mạnh ngày càng tăng của sự đổi mới dựa trên khách hàng và nội dung/thấu hiểu do người dùng tạo ra. Điều này đánh dấu sự chuyển dịch khỏi quan điểm lấy công ty làm trung tâm thuần túy trong phát triển sản phẩm và marketing. Việc AFOLs cung cấp \"ý tưởng và hiểu biết mới về khách hàng\" và việc LEGO \"mời khách hàng tham gia trực tiếp vào quá trình phát triển sản phẩm\", cùng với thành công của bộ tàu LEGO Santa Fe Super Chief bán hết veo \"mà không cần có hoạt động marketing nào\" 1, đã chứng minh sức mạnh tự nhiên của việc đồng sáng tạo và gắn kết cộng đồng.",
    "<strong>B. \"Dữ liệu lớn\" (Big Data) và sự bùng nổ thông tin</strong><br/>Sự bùng nổ của công nghệ thông tin đã mang lại cho các doanh nghiệp khả năng tạo ra và tiếp cận một lượng thông tin marketing khổng lồ. Người tiêu dùng ngày nay, thông qua việc sử dụng điện thoại thông minh, máy tính cá nhân, máy tính bảng và các tương tác trên mạng xã hội, đang tự nguyện truyền tải một lượng lớn thông tin đến các doanh nghiệp. Kết quả là, các nhà quản trị marketing không còn đối mặt với tình trạng thiếu thông tin, mà ngược lại, họ thường xuyên bị quá tải bởi dữ liệu. Khái niệm \"dữ liệu lớn\" (Big Data) ra đời để mô tả các tập dữ liệu khổng lồ và phức tạp này, được tạo ra bởi công nghệ hiện đại trong việc tạo lập, thu thập, lưu trữ và phân tích thông tin.",
    "Thời đại kỹ thuật số đã dẫn đến một khối lượng, tốc độ và sự đa dạng dữ liệu chưa từng có. Mặc dù điều này mang lại cơ hội to lớn, nó cũng đặt ra một thách thức đáng kể trong việc xử lý và trích xuất những hiểu biết có ý nghĩa. Thách thức của \"Dữ liệu lớn\" không nằm ở việc thu thập dữ liệu mà là ở khả năng diễn giải và chuyển hóa dữ liệu thành những thấu hiểu có thể hành động. Các công ty cần nhiều hơn là khả năng lưu trữ; họ cần năng lực phân tích mạnh mẽ. Thực tế cho thấy, \"Không còn thiếu thông tin, hầu hết nhà quản trị marketing giờ đây đều quá tải với dữ liệu và thường bị các thông tin làm choáng ngợp\". Điều này ngụ ý rằng nút thắt không phải là sự sẵn có của dữ liệu mà là khả năng hiểu và tận dụng nó.",
    "<strong>C. Từ thông tin đến thấu hiểu khách hàng có giá trị</strong><br/>Bản thân thông tin marketing có rất ít giá trị nếu không được chuyển hóa. Giá trị thực sự nằm ở sự thấu hiểu khách hàng thu được từ thông tin đó và cách các chuyên gia marketing sử dụng những hiểu biết này để đưa ra các quyết định tốt hơn. \"Sự thấu hiểu khách hàng\" được định nghĩa là những hiểu biết mới mẻ về khách hàng và thị trường, bắt nguồn từ thông tin marketing, và chúng làm cơ sở để sáng tạo giá trị cũng như xây dựng mối quan hệ với khách hàng.",
    "Ví dụ điển hình là Pinterest. Mạng xã hội này đã đạt được thành công nhanh chóng nhờ vào một sự thấu hiểu khách hàng cực kỳ quan trọng: nhiều người muốn sử dụng mạng xã hội không chỉ để trao đổi thông điệp và hình ảnh, mà còn muốn có một công cụ để thu thập, tổ chức và chia sẻ những mối quan tâm và đam mê của họ trên internet.",
    "Mục tiêu cuối cùng của việc quản trị thông tin marketing là thu được những thấu hiểu giúp định hình chiến lược tốt hơn, xây dựng mối quan hệ khách hàng mạnh mẽ hơn và tạo ra lợi thế cạnh tranh. Những thấu hiểu này đóng vai trò như cầu nối giữa dữ liệu thô và chiến lược marketing hiệu quả. Chúng chính là những \"Khoảnh khắc Aha!\" (như đã thấy với LEGO) có thể định nghĩa lại các sản phẩm hoặc phương pháp tiếp cận thị trường. Sự thành công của Pinterest gắn liền trực tiếp với \"sự thấu hiểu khách hàng cực kỳ quan trọng\". Sự thấu hiểu này không chỉ là dữ liệu đơn thuần; đó là việc nhận ra một nhu cầu chưa được đáp ứng, từ đó dẫn đến một đề xuất giá trị độc đáo."
  ]),
};