import { PageData } from '../../types';
import { cleanParagraphs } from '../dataUtils';

const CHAPTER_4_TITLE = "Chương 4: Quản trị Thông tin Marketing để Thấu hiểu Khách hàng";

export const chap4SecIIIPageData: PageData = {
  id: 'chap4-secIII',
  chapterTitle: CHAPTER_4_TITLE,
  pageTitle: "III. Đánh giá Nhu cầu Thông tin và Phát triển Dữ liệu",
  paragraphs: cleanParagraphs([
    "<strong>A. Đánh giá nhu cầu thông tin marketing: Cân bằng giữa mong muốn, nhu cầu thực sự và chi phí</strong><br/>Hệ thống thông tin marketing (MIS) không chỉ phục vụ các nhà quản trị marketing và các nhà quản trị khác trong nội bộ doanh nghiệp mà còn có thể cung cấp thông tin cho các đối tác bên ngoài, như nhà cung cấp, các đơn vị trung gian, hoặc các đại lý dịch vụ marketing. Một ví dụ điển hình là hệ thống Retail Link của Walmart, cho phép các nhà cung cấp chủ chốt truy cập thông tin đa dạng từ hành vi mua sắm của khách hàng, lượng hàng tồn kho tại cửa hàng, cho đến số lượng mặt hàng cụ thể mà họ đã bán được trong 24 giờ qua.",
    "Một MIS hiệu quả cần phải cân bằng giữa thông tin mà người sử dụng muốn có, thông tin họ thực sự cần, và thông tin có thể cung cấp một cách hợp lý. Một số nhà quản trị có xu hướng yêu cầu mọi loại thông tin mà không cân nhắc kỹ lưỡng về nhu cầu thực sự. Trong kỷ nguyên dữ liệu lớn, việc thu thập và lưu trữ một lượng khổng lồ dữ liệu số trở nên dễ dàng hơn nhờ công nghệ, nhưng quá nhiều thông tin cũng có thể gây bất lợi tương tự như việc có quá ít thông tin. Ngược lại, một số nhà quản trị khác có thể bỏ qua những thông tin quan trọng mà họ cần biết, hoặc không biết cách yêu cầu những loại thông tin mà họ nên có. Do đó, MIS phải có khả năng giám sát môi trường marketing để chủ động cung cấp cho các nhà lãnh đạo những thông tin và sự thấu hiểu khách hàng cần thiết cho việc ra các quyết định then chốt.",
    "Cuối cùng, chi phí liên quan đến việc thu thập, phân tích, lưu trữ và truyền đạt thông tin có thể tăng lên rất nhanh. Doanh nghiệp cần phải đưa ra quyết định liệu giá trị của sự thấu hiểu khách hàng thu được từ thông tin bổ sung có tương xứng với chi phí bỏ ra để có được nó hay không. Đây là một bài toán khó, vì cả giá trị và chi phí đều rất khó để đánh giá một cách chính xác.",
    "Việc đánh giá nhu cầu thông tin đóng vai trò như một bộ lọc quan trọng trong quy trình MIS. Nếu không có bước này, các tổ chức có nguy cơ bị nhấn chìm trong dữ liệu không liên quan, dẫn đến việc ra quyết định không hiệu quả và lãng phí nguồn lực. Điều này đòi hỏi một cuộc đối thoại chặt chẽ giữa người cung cấp thông tin và người sử dụng thông tin. Tài liệu cảnh báo về những nhà quản lý \"đòi hỏi bất cứ thông tin nào mà không nghĩ xem họ thực sự cần gì\" hoặc những người \"muốn thu thập và lưu giữ một lượng khổng lồ dữ liệu số đơn giản là vì công nghệ cho phép làm việc đó\". Điều này cho thấy sự cần thiết của một quy trình đánh giá nhu cầu có kỷ luật để tránh những cạm bẫy này.",
    "<strong>B. Phát triển thông tin cần thiết</strong><br/>Các chuyên gia marketing có thể thu thập thông tin cần thiết từ ba nguồn chính: dữ liệu nội bộ, thông tin tình báo marketing cạnh tranh, và nghiên cứu marketing.",
    "<strong>1. Dữ liệu nội bộ</strong><br/>Nhiều doanh nghiệp xây dựng các cơ sở dữ liệu nội bộ lớn, nơi tập hợp thông tin về khách hàng và thị trường từ các nguồn dữ liệu khác nhau trong mạng lưới của doanh nghiệp. Thông tin này có thể đến từ bộ phận marketing (đặc điểm khách hàng, giao dịch bán hàng, lượng truy cập web/mạng xã hội), bộ phận dịch vụ khách hàng (hồ sơ hài lòng, vấn đề dịch vụ), bộ phận kế toán (doanh số, chi phí, dòng tiền), bộ phận vận hành (sản xuất, giao hàng, tồn kho), bộ phận bán hàng (phản ứng trung gian, hoạt động đối thủ), và cả các đối tác trong kênh marketing (dữ liệu giao dịch bán hàng).",
    "Lợi ích: Việc khai thác hiệu quả dữ liệu nội bộ có thể mang lại những hiểu biết sâu sắc về khách hàng và tạo ra lợi thế cạnh tranh. Thông thường, dữ liệu nội bộ có thể được truy cập nhanh chóng hơn và với chi phí thấp hơn so với các nguồn thông tin khác.",
    "Hạn chế: Tuy nhiên, dữ liệu nội bộ cũng có những vấn đề nhất định. Do thường được thu thập cho các mục đích khác, nó có thể không hoàn chỉnh hoặc không ở định dạng phù hợp cho việc ra quyết định marketing. Dữ liệu cũng nhanh chóng trở nên lỗi thời, đòi hỏi nỗ lực lớn để duy trì tính cập nhật. Cuối cùng, việc quản lý và khai thác khối lượng lớn thông tin trong một doanh nghiệp lớn đòi hỏi các thiết bị và kỹ thuật rất tinh vi.",
    "Nhà cung cấp dịch vụ tài chính và bảo hiểm USAA là một ví dụ điển hình về việc sử dụng hiệu quả cơ sở dữ liệu nội bộ để xây dựng lòng trung thành của khách hàng. USAA phục vụ quân nhân Mỹ và gia đình họ, chủ yếu qua marketing trực tiếp. Công ty duy trì một cơ sở dữ liệu khách hàng khổng lồ, được xây dựng từ lịch sử mua sắm, thông tin khảo sát, dữ liệu giao dịch và hành vi duyệt web. USAA sử dụng cơ sở dữ liệu này để điều chỉnh các đề xuất marketing trực tiếp theo nhu cầu cá nhân của từng khách hàng. Ví dụ, họ gửi thông tin về quy hoạch bất động sản cho những khách hàng sắp nghỉ hưu, hoặc thông tin về quản lý thẻ tín dụng cho các gia đình có con ở độ tuổi đại học. Việc sử dụng khéo léo cơ sở dữ liệu đã giúp USAA phục vụ mỗi khách hàng một cách độc đáo, dẫn đến sự hài lòng và lòng trung thành cao, giữ chân được 98% khách hàng của mình.",
    "Mặc dù tiết kiệm chi phí, giá trị thực sự của dữ liệu nội bộ thường tiềm ẩn và đòi hỏi năng lực phân tích tinh vi (như của USAA) để khai phá các cơ hội marketing cá nhân hóa. Tính chất lịch sử của nó cũng có nghĩa là nó phải được bổ sung bằng thông tin tình báo hướng tới tương lai. Thành công của USAA không chỉ đến từ việc sở hữu dữ liệu, mà từ \"việc sử dụng khéo léo cơ sở dữ liệu của mình\" để \"phục vụ mỗi khách hàng một cách độc đáo\". Điều này ngụ ý việc xử lý và ứng dụng dữ liệu tiên tiến, chứ không chỉ là lưu trữ thụ động. Tài liệu cũng lưu ý rằng dữ liệu nội bộ \"thường được thu thập cho các mục đích khác\" , nhấn mạnh khả năng không phù hợp của nó với các nhu cầu ra quyết định marketing cụ thể.",
    "<strong>2. Thu thập thông tin marketing cạnh tranh (Competitive Marketing Intelligence)</strong><br/><span class=\"text-rose-600\"><strong>Thu thập thông tin marketing cạnh tranh (Competitive Marketing Intelligence)</strong></span> là việc theo dõi, thu thập và phân tích một cách có hệ thống các thông tin công khai có sẵn về người tiêu dùng, đối thủ cạnh tranh và sự phát triển của thị trường. Mục tiêu chính của hoạt động này là nhằm cải thiện việc ra các quyết định chiến lược bằng cách thấu hiểu môi trường của người tiêu dùng, đánh giá và theo dõi hành động của đối thủ cạnh tranh, cũng như cung cấp những cảnh báo sớm về các cơ hội và nguy cơ trên thị trường.",
    "Kỹ thuật: Các kỹ thuật thu thập thông tin cạnh tranh rất đa dạng, từ việc quan sát trực tiếp người tiêu dùng, hỏi nhân viên của doanh nghiệp, so sánh sản phẩm cạnh tranh, nghiên cứu trực tuyến, đến việc giám sát các phương tiện truyền thông xã hội.",
    "Các trung tâm chỉ huy truyền thông xã hội: Nhiều công ty lớn như PepsiCo, Mastercard, Kraft và Dell đã thành lập các trung tâm chỉ huy kỹ thuật số tinh vi, thường xuyên theo dõi hoạt động thị trường và người tiêu dùng trực tuyến liên quan đến thương hiệu của họ.",
    "Mastercard (Conversation Suite): Trung tâm này giám sát, phân tích và phản ứng theo thời gian thực với hàng triệu cuộc thảo luận trực tuyến trên toàn thế giới liên quan đến thương hiệu Mastercard tại 43 thị trường và bằng 26 ngôn ngữ. Thông tin được tổng hợp và hiển thị trên màn hình LED lớn, cập nhật mỗi 4 phút, giúp các nhà quản lý đưa ra quyết định. Mastercard sử dụng những hiểu biết này để cải thiện sản phẩm, hoạt động marketing, theo dõi hiệu suất thương hiệu và gắn kết với người tiêu dùng. Họ thậm chí còn đào tạo \"đại sứ xã hội\" để tham gia trực tiếp vào các cuộc thảo luận trực tuyến.",
    "Gatorade (Gatorade Mission Control): Trung tâm này giám sát toàn bộ hoạt động truyền thông xã hội liên quan đến thương hiệu Gatorade theo thời gian thực, bao gồm đối thủ cạnh tranh, vận động viên và các chủ đề liên quan. Thông tin được sử dụng để cải thiện sản phẩm, marketing và tương tác với khách hàng. Một ví dụ điển hình là cách Gatorade xử lý tình huống LeBron James bị chuột rút trong trận chung kết NBA, biến một cuộc thảo luận tiêu cực tiềm ẩn thành một chiến thắng truyền thông.",
    "Hội Chữ Thập Đỏ Mỹ (Digital Operations Center): Hợp tác với Dell, trung tâm này giúp tổ chức cải thiện các phản ứng trong trường hợp khẩn cấp và thiên tai, dựa trên việc giám sát truyền thông xã hội.",
    "Giám sát đối thủ: Các doanh nghiệp cũng cần chủ động giám sát hoạt động của đối thủ cạnh tranh. Ví dụ, đội ngũ của Amazon hàng ngày mua sắm trên web và mạng xã hội của đối thủ để phân tích sản phẩm và dịch vụ. Samsung thường xuyên theo dõi các hoạt động truyền thông xã hội xoay quanh việc ra mắt sản phẩm mới của Apple để nhanh chóng định hình các phản ứng marketing cho sản phẩm của mình.",
    "Nguồn thông tin: Thông tin cạnh tranh có thể được thu thập từ nhiều nguồn: bên trong doanh nghiệp (quản lý cấp cao, kỹ sư, nhân viên bán hàng), bên ngoài (nhà cung cấp, trung gian, khách hàng chủ chốt), và hàng nghìn cơ sở dữ liệu trực tuyến (một số miễn phí như của Ủy ban Giao dịch và Chứng khoán Mỹ, Văn phòng Sáng chế và Thương hiệu Mỹ; một số trả phí như Hoover's, LexisNexis, Dun & Bradstreet).",
    "Vấn đề đạo đức: Sự gia tăng của tình báo marketing cũng đặt ra các vấn đề đạo đức. Doanh nghiệp nên tận dụng thông tin công khai có sẵn thay vì các hành vi phi đạo đức như rình mò hay đánh cắp thông tin. Với nguồn thông tin hợp pháp dồi dào hiện nay, không cần thiết phải phá luật. Các doanh nghiệp cũng nên tự \"hút bụi\" thông tin công khai về chính mình để phát hiện các rò rỉ thông tin tiềm ẩn.",
    "Sự ra đời của các trung tâm chỉ huy truyền thông xã hội đánh dấu một sự chuyển dịch trong tình báo cạnh tranh từ một chức năng định kỳ, phản ứng sang một năng lực chiến lược liên tục, chủ động và theo thời gian thực. Điều này cho phép phản ứng ngay lập tức và thậm chí định hình các cuộc trò chuyện trên thị trường. Conversation Suite của Mastercard hoạt động \"theo thời gian thực\" và Mission Control của Gatorade cung cấp \"giám sát toàn bộ hoạt động của các phương tiện truyền thông xã hội liên quan đến thương hiệu theo thời gian thực\". Khả năng của Samsung \"phác thảo các phản ứng\" ngay khi các sự kiện của Apple diễn ra là một minh chứng cho năng lực thời gian thực này.",
    "Ranh giới đạo đức trong tình báo cạnh tranh là rất quan trọng. Mặc dù việc tận dụng thông tin công khai là hợp pháp, nhưng khả năng tiếp cận dễ dàng với lượng lớn dữ liệu trực tuyến đòi hỏi một khuôn khổ đạo đức mạnh mẽ để ngăn chặn các hành vi như gián điệp doanh nghiệp hoặc vi phạm quyền riêng tư. Tài liệu tuyên bố rõ ràng: \"Rõ ràng là các doanh nghiệp nên tận dụng thông tin công khai có sẵn thay vì rình mò hay đánh cắp thông tin.\" Nó cũng khuyên các công ty nên tự kiểm tra tình báo để tìm \"những rò rỉ thông tin có thể gây tổn hại.\""
  ]),
};