import { PageData } from '../../types';
import { cleanParagraphs } from '../dataUtils';

const CHAPTER_4_TITLE = "Chương 4: Quản trị Thông tin Marketing để Thấu hiểu Khách hàng";

export const chap4SecVIIPageData: PageData = {
  id: 'chap4-secVII',
  chapterTitle: CHAPTER_4_TITLE,
  pageTitle: "VII. Những Vấn đề Khác về Thông tin Marketing",
  paragraphs: cleanParagraphs([
    "Phần này thảo luận về thông tin marketing trong hai bối cảnh đặc biệt: nghiên cứu marketing trong các doanh nghiệp nhỏ và tổ chức phi lợi nhuận, và nghiên cứu marketing quốc tế. Sau đó, xem xét các chính sách công cũng như vấn đề đạo đức trong nghiên cứu marketing.",
    "<strong>A. Nghiên cứu marketing trong doanh nghiệp nhỏ và tổ chức phi lợi nhuận</strong><br/>Cũng như các doanh nghiệp lớn, các doanh nghiệp nhỏ và tổ chức phi lợi nhuận đều cần thông tin thị trường và sự thấu hiểu khách hàng. Mặc dù các nghiên cứu quy mô lớn có thể vượt quá ngân sách của hầu hết các tổ chức nhỏ, họ vẫn có thể áp dụng nhiều kỹ thuật nghiên cứu marketing đã được thảo luận theo những cách thức ít mang tính chính thức hơn và với chi phí nhỏ hơn hoặc bằng không.",
    "Phương pháp: Các tổ chức này có thể thu được những hiểu biết thị trường tốt thông qua việc quan sát hoặc thực hiện các cuộc khảo sát không chính thức, sử dụng các mẫu thuận tiện với kích thước nhỏ. Ngoài ra, nhiều hiệp hội, phương tiện truyền thông địa phương và các cơ quan chính phủ (như Cơ quan Quản lý Doanh nghiệp nhỏ Mỹ - SBA, Cục Điều tra Dân số Mỹ, Cục Phân tích Kinh tế) cũng cung cấp sự trợ giúp đặc biệt. Cuối cùng, các doanh nghiệp nhỏ có thể thu thập một lượng thông tin đáng kể trên mạng internet với chi phí rất thấp, chẳng hạn như truy cập các trang web đánh giá sản phẩm và dịch vụ, sử dụng công cụ tìm kiếm để nghiên cứu các công ty và vấn đề cụ thể, thậm chí tìm hiểu trang web và mạng xã hội của đối thủ cạnh tranh và khách hàng.",
    "Lưu ý: Mặc dù các phương pháp nghiên cứu không chính thức này ít phức tạp và tốn kém hơn, chúng vẫn phải được tiến hành một cách cẩn thận. Các nhà quản trị phải suy nghĩ kỹ về mục tiêu nghiên cứu, thiết kế câu hỏi trước, nhận diện các sai lệch có thể xảy ra do mẫu nhỏ hoặc người nghiên cứu thiếu kỹ năng, và tiến hành nghiên cứu một cách có hệ thống.",
    "Ví dụ Bibbentuckers: Trước khi mở cửa hàng giặt khô Bibbentuckers, Robert Byerley đã tiến hành nhiều nghiên cứu thị trường. Ông dành thời gian nghiên cứu trực tuyến, tổ chức các nhóm tập trung (thông qua một hãng marketing địa phương) để thảo luận về tên, hình thức cửa hàng, và đánh giá các đối thủ cạnh tranh. Dựa trên nghiên cứu, ông xác định chất lượng là ưu tiên hàng đầu. Kết quả là Bibbentuckers, một cửa hàng giặt khô cao cấp định vị bằng chất lượng và sự tiện lợi, đã thành công và phát triển thành một hệ thống 8 cửa hàng.",
    "Ví dụ về Bibbentuckers cho thấy rằng ngay cả đối với các doanh nghiệp nhỏ, địa phương, một mức độ nghiên cứu thị trường cơ bản là rất quan trọng để định vị và tạo sự khác biệt hiệu quả, cho phép họ cạnh tranh thành công với các đối thủ đã có tên tuổi bằng cách hiểu sâu sắc mong muốn của khách hàng (trong trường hợp này là chất lượng và sự tiện lợi hơn là giá cả). Byerley đã tiến hành nghiên cứu để hiểu \"Làm thế nào để doanh nghiệp của ông nổi trội hơn những doanh nghiệp khác?\". Nghiên cứu của ông đã dẫn đến một chiến lược định vị rõ ràng (\"chất lượng cao và sự tiện lợi\") trực tiếp giải quyết những gì khách hàng mong muốn, dẫn đến một \"hệ thống với 8 cửa hàng làm ăn phát đạt\".",
    "<strong>B. Nghiên cứu marketing quốc tế</strong><br/>Các nhà nghiên cứu marketing quốc tế thực hiện theo các bước tương tự như các nhà nghiên cứu trong nước, từ việc xác định vấn đề nghiên cứu và phát triển kế hoạch nghiên cứu đến diễn giải và báo cáo kết quả. Tuy nhiên, họ thường phải đối mặt với nhiều vấn đề phức tạp hơn đáng kể.",
    "Thách thức:",
    "Thị trường đa dạng: Các thị trường quốc tế thường khác biệt lớn về mức độ phát triển kinh tế, văn hóa, phong tục và thói quen mua hàng.",
    "Khan hiếm dữ liệu thứ cấp: Nhiều quốc gia gần như không có các dịch vụ nghiên cứu thị trường đáng tin cậy. Ngay cả khi có dữ liệu (ví dụ, Nielsen có văn phòng tại hơn 100 quốc gia), việc thu thập từ nhiều nguồn khác nhau cũng gây khó khăn trong việc kết hợp hoặc so sánh thông tin.",
    "Khó khăn thu thập dữ liệu sơ cấp:",
    "Lấy mẫu: Việc thiết lập các mẫu nghiên cứu tốt có thể rất khó khăn do thiếu các nguồn dữ liệu như danh bạ điện thoại hoặc dữ liệu điều tra dân số ở nhiều quốc gia.",
    "Tiếp cận người trả lời: Ở nhiều nơi trên thế giới, việc tiếp cận người trả lời không dễ dàng. Ví dụ, ở Mexico, hầu hết việc thu thập dữ liệu phải tiến hành trực tiếp tại các thành phố lớn. Ở một số nước, tỷ lệ người có máy tính hoặc internet rất thấp (ví dụ Madagascar chỉ 2/100 dân có internet so với 84/100 ở Mỹ). Hệ thống bưu chính có thể không đáng tin cậy (ví dụ, ở Brazil, ước tính 30% thư không được phát). Đường sá và giao thông kém ở các nước đang phát triển cũng gây khó khăn và tốn kém cho phỏng vấn cá nhân.",
    "Khác biệt văn hóa và ngôn ngữ: Ngôn ngữ là một trở ngại rõ ràng. Bảng hỏi phải được dịch sang nhiều ngôn ngữ, và phản hồi phải được dịch ngược lại, làm tăng chi phí và nguy cơ sai sót. Nhiều thành ngữ và cụm từ có ý nghĩa khác nhau ở các nền văn hóa khác nhau (ví dụ, câu \"xa mặt cách lòng\" từng được dịch thành \"những thứ vô hình thật điên rồ\"). Thái độ của người tiêu dùng đối với nghiên cứu marketing cũng khác nhau; phong tục có thể cấm nói chuyện với người lạ, hoặc các câu hỏi nghiên cứu có thể bị coi là quá riêng tư (ví dụ, ở các nước Hồi giáo). Tình trạng mù chữ cũng là một rào cản ở một số quốc gia.",
    "Tầm quan trọng: Bất chấp những khó khăn và chi phí cao, việc không thực hiện nghiên cứu marketing quốc tế có thể dẫn đến những tổn thất lớn hơn do bỏ lỡ cơ hội hoặc mắc phải sai lầm. Nhiều vấn đề có thể được khắc phục hoặc tránh được nếu doanh nghiệp nhận thức được tầm quan trọng của nó.",
    "Những thách thức trong nghiên cứu marketing quốc tế nhấn mạnh tầm quan trọng sống còn của sự nhạy cảm văn hóa và khả năng thích ứng tại địa phương trong tất cả các khía cạnh của quy trình nghiên cứu, từ thiết kế công cụ, phương pháp thu thập dữ liệu đến giải thích kết quả. Một cách tiếp cận \"một kích cỡ phù hợp cho tất cả\" chắc chắn sẽ thất bại. Tài liệu đã liệt kê nhiều ví dụ về cách sự khác biệt văn hóa và cơ sở hạ tầng tác động đến nghiên cứu: khó khăn trong việc tiếp cận người trả lời do hệ thống bưu chính kém hoặc thiếu internet , những cạm bẫy trong dịch thuật ngôn ngữ (ví dụ \"xa mặt cách lòng\" được dịch thành \"những thứ vô hình thật điên rồ\") , và các chuẩn mực văn hóa khác nhau liên quan đến quyền riêng tư hoặc tương tác với người lạ. Tất cả những điều này đều chỉ ra sự cần thiết phải có sự hiểu biết sâu sắc về địa phương.",
    "<strong>C. Chính sách công bố và các vấn đề đạo đức trong nghiên cứu marketing</strong><br/>Các hoạt động nghiên cứu marketing có thể làm nảy sinh các vấn đề liên quan đến chính sách công và đạo đức, chủ yếu xoay quanh hai lĩnh vực: sự xâm phạm quyền riêng tư của người tiêu dùng và việc lạm dụng kết quả nghiên cứu.",
    "<strong>1. Xâm phạm quyền riêng tư của người tiêu dùng</strong><br/>Đây là một trong những mối quan tâm lớn nhất trong nghiên cứu marketing hiện đại. Người tiêu dùng ngày càng lo ngại về việc các doanh nghiệp thu thập quá nhiều thông tin cá nhân của họ, sử dụng các kỹ thuật tinh vi để thăm dò những cảm xúc thầm kín, theo dõi việc sử dụng thiết bị di động, hoạt động trên internet hoặc hành vi mua sắm, và sau đó có thể sử dụng những kiến thức này để thao túng quyết định mua hàng của họ. Một cuộc khảo sát gần đây cho thấy hơn 90% người Mỹ cảm thấy họ đã mất quyền kiểm soát đối với việc thu thập và sử dụng dữ liệu cá nhân cũng như thông tin chia sẻ trên các trang mạng xã hội.",
    "Ví dụ về xâm phạm quyền riêng tư:",
    "Target dự đoán mang thai: Target đã sử dụng dữ liệu lịch sử mua hàng để xác định những khách hàng nữ có khả năng đang mang thai, thậm chí ước tính chính xác giới tính và ngày sinh của đứa trẻ, sau đó gửi phiếu giảm giá cá nhân hóa cho các mặt hàng liên quan đến em bé. Chiến lược này đã gây ra phản ứng tiêu cực khi một người cha phát hiện con gái đang học trung học của mình nhận được các phiếu giảm giá này trước cả khi gia đình biết cô bé mang thai. Nhiều khách hàng cảm thấy lo sợ khi Target biết những thông tin riêng tư như vậy về họ.",
    "SAP Consumer Insight 365: Dịch vụ này giúp các nhà cung cấp dịch vụ di động trích xuất dữ liệu về người đăng ký và lối sống lấy thiết bị di động làm trung tâm của họ.",
    "Theo dõi trực tuyến: Các hành vi như sử dụng người mua sắm giả với máy quay bí mật để ghi lại đặc điểm nhân khẩu học và hành vi mua sắm, giám sát các bài đăng của khách hàng trên mạng xã hội, hoặc theo dõi việc sử dụng điện thoại di động để cung cấp quảng cáo theo vị trí đều làm dấy lên lo ngại về quyền riêng tư.",
    "Giải pháp và cân nhắc:",
    "Ủy ban Thương mại Liên bang Mỹ (FTC) đã khuyến nghị thiết lập một hệ thống \"Do Not Track\" (Không theo dõi) cho phép người dùng từ chối việc bị theo dõi trực tuyến, tương tự như đăng ký \"Do Not Call\" (Không gọi điện).",
    "Nhiều công ty lớn hiện nay đã bổ nhiệm Giám đốc về quyền riêng tư (CPO) để bảo vệ quyền riêng tư của khách hàng.",
    "Nếu các nhà nghiên cứu cung cấp giá trị thực sự để đổi lấy thông tin, khách hàng có thể sẽ sẵn lòng cung cấp thông tin đó (ví dụ, khách hàng của Amazon không bận tâm nếu hãng xây dựng cơ sở dữ liệu mua sắm để đưa ra các khuyến nghị sản phẩm hữu ích). Cách tốt nhất là các nhà nghiên cứu chỉ nên hỏi những thông tin họ thực sự cần, sử dụng thông tin một cách có trách nhiệm để cung cấp giá trị cho khách hàng, và tránh chia sẻ thông tin mà không có sự cho phép của khách hàng.",
    "Thách thức đạo đức về quyền riêng tư của người tiêu dùng trong nghiên cứu marketing xoay quanh việc tìm kiếm sự cân bằng giữa lợi ích của việc cá nhân hóa và quyền cá nhân. Mặc dù người tiêu dùng có thể đánh giá cao các ưu đãi phù hợp, họ phản đối việc giám sát xâm nhập, tạo ra sự thiếu hụt lòng tin mà các nhà tiếp thị phải chủ động giải quyết thông qua tính minh bạch và quản lý dữ liệu có trách nhiệm. Ví dụ về Target minh họa hoàn hảo sự căng thẳng này. Mặc dù các phiếu giảm giá được cá nhân hóa nhằm mục đích hữu ích, phương pháp thu thập thông tin (dự đoán mang thai) được coi là một sự vi phạm quyền riêng tư nghiêm trọng, gây ra phản ứng dữ dội từ khách hàng. Tài liệu cũng lưu ý, \"nếu các nhà nghiên cứu cung cấp giá trị để đổi lấy thông tin, khách hàng sẽ sẵn sàng cung cấp thông tin\" , cho thấy sự trao đổi có đi có lại là cần thiết để chia sẻ dữ liệu.",
    "<strong>2. Lạm dụng kết quả nghiên cứu</strong><br/>Các nghiên cứu có thể là công cụ thuyết phục mạnh mẽ, và các doanh nghiệp thường sử dụng kết quả nghiên cứu như những tuyên bố trong hoạt động quảng cáo và xúc tiến của họ. Tuy nhiên, hiện nay, nhiều nghiên cứu có vẻ chỉ là các phương tiện để bán sản phẩm của nhà tài trợ nghiên cứu, hoặc được thiết kế chỉ để tạo ra những hiệu ứng đã được dự tính trước.",
    "Ví dụ về lạm dụng: Khảo sát của Black Flag đặt câu hỏi mang tính dẫn dắt về hiệu quả của một loại đĩa diệt gián, và không ngạc nhiên khi 79% người trả lời nói rằng sản phẩm đó hiệu quả.",
    "Lạm dụng tinh vi và diễn giải thiên vị: Hầu hết sự lạm dụng thường tinh vi hơn là việc thiết kế nghiên cứu sai lệch hoặc xuyên tạc kết quả một cách trắng trợn. Có sự gia tăng tranh cãi về giá trị, sự diễn giải và việc sử dụng kết quả nghiên cứu. Hầu như bất kỳ kết quả nghiên cứu nào cũng có thể được diễn giải theo những cách khác nhau tùy thuộc vào thành kiến và quan điểm của nhà nghiên cứu.",
    "Vai trò của các hiệp hội ngành: Nhận thấy nghiên cứu marketing có thể bị lạm dụng, một số hiệp hội như Hiệp hội Marketing Mỹ (AMA), Hiệp hội Nghiên cứu Marketing (MRA), và Hội đồng Các tổ chức nghiên cứu khảo sát Mỹ (CASRO) đã thiết lập các quy tắc đạo đức và tiêu chuẩn nghiên cứu. Ví dụ, các tiêu chuẩn của CASRO phác thảo trách nhiệm của nhà nghiên cứu đối với người trả lời (giữ bí mật, quyền riêng tư, tránh quấy rối) và trách nhiệm trong việc báo cáo kết quả cho khách hàng và công chúng.",
    "Trách nhiệm của doanh nghiệp: Tuy nhiên, các hành động phi đạo đức và vô trách nhiệm không thể được điều chỉnh một cách đơn giản chỉ bằng các quy tắc. Mỗi doanh nghiệp cần có trách nhiệm đối với chính sách thực hiện và báo cáo nghiên cứu marketing của chính mình để bảo vệ lợi ích tốt nhất của người tiêu dùng cũng như của chính doanh nghiệp."
  ]),
};