import { PageData } from '../../types';
import { cleanParagraphs } from '../dataUtils';

const CHAPTER_4_TITLE = "Chương 4: Quản trị Thông tin Marketing để Thấu hiểu Khách hàng";

export const chap4SecVPageData: PageData = {
  id: 'chap4-secV',
  chapterTitle: CHAPTER_4_TITLE,
  pageTitle: "V. Phân tích và Sử dụng Thông tin Marketing",
  paragraphs: cleanParagraphs([
    "Thông tin thu được từ cơ sở dữ liệu nội bộ, thông tin marketing cạnh tranh và nghiên cứu marketing luôn đòi hỏi các bước phân tích bổ sung. Các nhà quản trị có thể cần sự trợ giúp để ứng dụng thông tin này nhằm đạt được sự thấu hiểu sâu sắc về khách hàng và thị trường, từ đó cải thiện các quyết định marketing của họ. Sự trợ giúp này có thể bao gồm các phân tích nâng cao để tìm hiểu sâu hơn về các mối quan hệ trong một bộ dữ liệu, hoặc áp dụng các mô hình phân tích giúp nhà quản trị đưa ra quyết định tốt hơn. Khi thông tin đã được xử lý và phân tích, nó phải được cung cấp tới đúng người ra quyết định và vào đúng thời điểm.",
    "<strong>A. Quản trị quan hệ khách hàng (CRM)</strong><br/>Trong kỷ nguyên dữ liệu lớn hiện nay, hầu hết các doanh nghiệp đều tràn ngập thông tin về khách hàng và thị trường. Các doanh nghiệp khôn ngoan sẽ nắm bắt thông tin tại mọi điểm tiếp xúc khách hàng có thể có, bao gồm hành vi mua hàng, liên hệ với lực lượng bán hàng, các cuộc gọi dịch vụ và hỗ trợ, lượt truy cập trang web và mạng xã hội, khảo sát sự hài lòng, tương tác tín dụng và thanh toán, nghiên cứu thị trường – tóm lại là mọi mối liên hệ giữa khách hàng và doanh nghiệp. Tuy nhiên, thông tin này thường nằm rải rác trong toàn tổ chức hoặc bị chôn sâu trong các cơ sở dữ liệu riêng biệt. Để khắc phục điều này, nhiều doanh nghiệp đang chuyển sang sử dụng Quản trị Quan Hệ Khách hàng (CRM) để quản lý thông tin chi tiết về khách hàng cá nhân và các điểm tiếp xúc với khách hàng một cách cẩn trọng, nhằm mục tiêu cuối cùng là tối đa hóa lòng trung thành của khách hàng.",
    "CRM bao gồm các phần mềm và công cụ phân tích tinh vi từ các hãng như Salesforce.com, Oracle, Microsoft và SAS. Những công cụ này giúp tích hợp thông tin khách hàng và thị trường từ nhiều nguồn, phân tích dữ liệu và áp dụng kết quả để xây dựng mối quan hệ khách hàng mạnh mẽ hơn, cung cấp cái nhìn 360 độ về mối quan hệ với khách hàng.",
    "Ví dụ, MetLife đã phát triển một hệ thống CRM nội bộ có tên \"The MetLife Wall\". Hệ thống này giải quyết thách thức trong việc nhanh chóng tìm kiếm thông tin khách hàng vốn được lưu trữ rải rác. The MetLife Wall sử dụng giao diện giống Facebook, cung cấp cái nhìn tổng hợp về từng trải nghiệm dịch vụ khách hàng, thu thập dữ liệu từ 70 hệ thống khác nhau. Nó hiển thị tất cả thông tin khách hàng và các liên kết liên quan trên một màn hình duy nhất, cập nhật theo thời gian thực, giúp đại diện bán hàng và dịch vụ có cái nhìn tổng thể về chính sách, giao dịch, khiếu nại và thanh toán của khách hàng, từ đó thúc đẩy dịch vụ khách hàng và nỗ lực bán chéo, đồng thời có \"tác động rất lớn đến sự hài lòng của khách hàng\".",
    "Một ví dụ khác là Netflix, công ty duy trì cơ sở dữ liệu khách hàng khổng lồ và sử dụng các phân tích marketing tinh vi để đạt được sự thấu hiểu. Netflix theo dõi chi tiết hành vi xem của từng thuê bao (xem gì, khi nào, trên thiết bị nào, ở đâu, thậm chí cả khi họ tạm dừng hoặc tua). Họ bổ sung dữ liệu này bằng thông tin mua từ Nielsen, Facebook, Twitter và các nguồn khác, đồng thời thuê chuyên gia phân loại từng video theo hàng trăm đặc tính. Từ đó, Netflix xây dựng hồ sơ chi tiết khách hàng, cá nhân hóa trải nghiệm xem, đưa ra các đề xuất (chiếm tới 75% hoạt động xem của khách hàng), quyết định chương trình nào sẽ cung cấp và phát triển nội dung độc quyền. Việc này giúp tăng thời gian xem trung bình và giữ chân thuê bao.",
    "Tuy nhiên, CRM và phân tích dữ liệu lớn cũng có những rủi ro. Lỗi phổ biến nhất là coi CRM chỉ như một quy trình công nghệ, hoặc bị chôn vùi trong chi tiết mà bỏ lỡ bức tranh tổng thể. Chỉ riêng công nghệ không thể xây dựng mối quan hệ khách hàng có lợi nhuận. Thay vào đó, các nhà marketing nên bắt đầu với các nguyên lý cơ bản của CRM, sau đó mới sử dụng dữ liệu công nghệ cao và các giải pháp phân tích. Điều quan trọng nhất là phải tập trung vào chữ 'R' – Relationship (Mối quan hệ) – thành phần cốt lõi của CRM.",
    "Sức mạnh thực sự của CRM không nằm ở bản thân công nghệ, mà ở việc áp dụng chiến lược các hiểu biết về khách hàng thu được từ hệ thống để nuôi dưỡng các mối quan hệ chân thực, dựa trên giá trị. Một cách tiếp cận ưu tiên công nghệ mà không có một triết lý lấy mối quan hệ làm trung tâm rất dễ thất bại. Tài liệu cảnh báo rằng một cạm bẫy phổ biến là \"coi CRM và phân tích marketing chỉ như một quy trình công nghệ.\" Nó nhấn mạnh rằng các nhà tiếp thị nên \"tập trung trước hết vào R – Relationship (mối quan hệ) – thành phần cốt lõi của CRM.\"",
    "<strong>B. Dữ liệu lớn (Big Data) và Phân tích Marketing (Marketing Analytics)</strong><br/>Các công ty đang tích cực khai thác các mô hình có ý nghĩa trong khối lượng dữ liệu lớn (Big Data) để đạt được sự thấu hiểu khách hàng và đánh giá hiệu suất marketing. Netflix là một ví dụ điển hình về việc sử dụng phân tích marketing trên dữ liệu lớn. Công ty không chỉ sử dụng dữ liệu để cá nhân hóa trải nghiệm xem mà còn để quyết định những chương trình nào nên được thêm vào kho nội dung, nhằm \"tối đa hóa hạnh phúc trên mỗi đồng tiền chi thêm\" cho các thuê bao. Sự thấu hiểu khách hàng từ dữ liệu lớn cũng được Netflix sử dụng để phát triển và bổ sung các nội dung video độc quyền, những chương trình mà khán giả chỉ có thể xem trên Netflix.",
    "Phân tích marketing áp dụng cho Dữ liệu lớn cho phép chuyển đổi từ marketing đại chúng sang marketing cá nhân hóa cao ở quy mô lớn, như được minh chứng bằng khả năng của Netflix trong việc điều chỉnh các đề xuất và thậm chí cả nội dung cho từng hồ sơ người dùng cá nhân. Khả năng của Netflix trong việc cung cấp các đề xuất chiếm 75% lượt xem và \"cá nhân hóa trải nghiệm xem của từng khách hàng\" là kết quả trực tiếp của việc phân tích các bộ dữ liệu khổng lồ. Mức độ cá nhân hóa này sẽ không thể thực hiện được nếu không có phân tích Dữ liệu lớn."
  ]),
};