import { PageData } from '../../types';
import { cleanParagraphs } from '../dataUtils';

const CHAPTER_4_TITLE = "Chương 4: Quản trị Thông tin Marketing để Thấu hiểu Khách hàng";

export const chap4SecVIPageData: PageData = {
  id: 'chap4-secVI',
  chapterTitle: CHAPTER_4_TITLE,
  pageTitle: "VI. Phân phối và Sử dụng Thông tin Marketing",
  paragraphs: cleanParagraphs([
    "<strong>A. Cung cấp thông tin cho người ra quyết định đúng lúc, đúng định dạng</strong><br/>Thông tin marketing chỉ thực sự có giá trị khi nó được sử dụng để đưa ra các quyết định marketing tốt hơn. Do đó, hệ thống thông tin marketing (MIS) phải đảm bảo rằng thông tin sẵn sàng cho các nhà quản trị và những người khác khi họ cần. Trong một số trường hợp, điều này có nghĩa là cung cấp các báo cáo kết quả đều đặn, cập nhật thông tin cạnh tranh và báo cáo về kết quả nghiên cứu marketing. Tuy nhiên, các nhà quản trị marketing cũng có thể có nhu cầu truy cập các thông tin đặc thù cho các tình huống đặc biệt và các quyết định tại chỗ, ví dụ như một quản lý bán hàng cần tóm tắt doanh số của một khách hàng lớn, hoặc một nhà quản trị thương hiệu muốn biết về mức độ bàn tán trên mạng xã hội về một sản phẩm mới ra mắt. Do đó, việc phân phối thông tin hiện nay chủ yếu nhằm đảm bảo cung cấp thông tin kịp thời và thân thiện với người sử dụng.",
    "<strong>B. Vai trò của mạng nội bộ (Intranet) và mạng ngoại bộ (Extranet)</strong><br/>Nhiều doanh nghiệp sử dụng mạng nội bộ (intranet) công ty và các hệ thống CRM nội bộ để tạo điều kiện thuận lợi cho quá trình phân phối thông tin. Các hệ thống này cung cấp quyền truy cập ngay lập tức vào thông tin nghiên cứu và tình báo, thông tin giao dịch và trải nghiệm khách hàng, các báo cáo và tài liệu được chia sẻ.",
    "Ví dụ về Intranet: Hệ thống CRM của nhà bán lẻ quà tặng trực tuyến và qua điện thoại 1-800-Flowers.com cho phép nhân viên tiếp cận khách hàng truy cập thông tin khách hàng theo thời gian thực. Khi một khách hàng thường xuyên gọi đến, hệ thống ngay lập tức lấy dữ liệu về các giao dịch trước đó, giúp đại diện bán hàng dễ dàng cá nhân hóa trải nghiệm khách hàng, ví dụ như gợi ý loại hoa tulip mà khách hàng thường mua tặng vợ. Điều này tạo ra sự hài lòng và lòng trung thành lớn hơn, đồng thời tăng doanh số cho công ty.",
    "Ngoài ra, các doanh nghiệp ngày càng cho phép những khách hàng then chốt và các thành viên thuộc mạng lưới giá trị của họ truy cập vào tài khoản, sản phẩm và các dữ liệu khác theo yêu cầu thông qua mạng ngoại bộ (extranet). Các nhà cung cấp, khách hàng, đại lý mua hàng và các thành viên khác trong mạng lưới có thể truy cập extranet của doanh nghiệp để cập nhật tài khoản, sắp xếp mua hàng, và kiểm tra đơn hàng dựa trên hàng tồn kho, nhằm cải thiện dịch vụ khách hàng.",
    "Ví dụ về Extranet: Nhà bán lẻ trực tuyến giày và phụ kiện Zappos coi các nhà cung cấp là \"một phần của gia đình Zappos\". Thông qua mạng extranet ZUUL (Zappos Unified User Login), hàng nghìn nhà cung cấp của Zappos được cấp quyền truy cập đầy đủ về mức tồn kho, số liệu doanh thu, thậm chí cả lợi nhuận của các thương hiệu liên quan. Các nhà cung cấp có thể sử dụng ZUUL để tương tác với nhóm sáng tạo của Zappos và nhập các đơn hàng được đề xuất cho người mua của Zappos xem xét.",
    "Việc sử dụng extranet, như Zappos ZUUL, phản ánh một sự chuyển dịch chiến lược hướng tới tính minh bạch và hợp tác lớn hơn trong mạng lưới phân phối giá trị. Việc chia sẻ dữ liệu quan trọng với các nhà cung cấp giúp củng cố mối quan hệ đối tác mạnh mẽ hơn và có thể dẫn đến hiệu quả cải thiện và dịch vụ khách hàng tốt hơn. Zappos \"coi các nhà cung cấp là những đối tác có giá trị và chia sẻ thông tin với họ\" thông qua ZUUL, cho họ \"quyền truy cập đầy đủ về mức tồn kho, số liệu doanh thu, thậm chí cả lợi nhuận\". Mức độ cởi mở này được thiết kế để xây dựng các mối quan hệ đối tác mạnh mẽ hơn, tích hợp hơn.",
    "<strong>C. Tiếp cận thông tin qua công nghệ hiện đại</strong><br/>Nhờ công nghệ hiện đại, ngày nay các nhà quản trị marketing có thể truy cập trực tiếp vào hệ thống thông tin của doanh nghiệp bất cứ lúc nào và từ bất cứ đâu – từ văn phòng tại nhà, địa điểm của khách hàng, sân bay, hay một quán cà phê có kết nối internet – thông qua máy tính xách tay, máy tính bảng hoặc điện thoại thông minh. Các hệ thống như vậy cho phép nhà quản trị có được thông tin họ cần một cách trực tiếp, nhanh chóng và điều chỉnh nó theo nhu cầu cụ thể của họ."
  ]),
};