import { PageData } from '../../types';
import { cleanParagraphs } from '../dataUtils';

const CHAPTER_5_TITLE = "Chương 5: Hành vi Mua của Người tiêu dùng";

export const chap5SecIIIPageData: PageData = {
  id: 'chap5-secIII',
  chapterTitle: CHAPTER_5_TITLE,
  pageTitle: "III. Quá trình Ra quyết định của Người mua",
  paragraphs: cleanParagraphs([
    "Bây giờ chúng ta đã xem xét các yếu tố ảnh hưởng đến hành vi của người mua, chúng ta sẽ xem xét cách người tiêu dùng đưa ra quyết định mua hàng. Hình 5.4 cho thấy người mua trải qua năm giai đoạn: nhận biết nhu cầu, tìm kiếm thông tin, đánh giá các lựa chọn thay thế, quyết định mua và hành vi sau mua. Rõ ràng, quá trình mua bắt đầu rất lâu trước khi mua thực tế và tiếp tục rất lâu sau đó. Các nhà marketing cần tập trung vào toàn bộ quá trình mua chứ không chỉ quyết định mua.",
    "<strong>A. Các giai đoạn trong Quy trình Ra quyết định của Người mua</strong><br/>Mô hình này gợi ý rằng người tiêu dùng trải qua tất cả năm giai đoạn với mỗi lần mua hàng theo một cách thức cân nhắc. Tuy nhiên, trong các giao dịch mua thông thường hơn, người tiêu dùng thường bỏ qua hoặc đảo ngược một số giai đoạn này. Ví dụ, một người phụ nữ mua nhãn hiệu kem đánh răng thường xuyên của mình có thể nhận ra nhu cầu và đi thẳng đến quyết định mua, bỏ qua việc tìm kiếm thông tin và đánh giá. Tuy nhiên, chúng ta sử dụng mô hình trong Hình 5.4 vì nó cho thấy tất cả các cân nhắc phát sinh khi người tiêu dùng phải đối mặt với một tình huống mua hàng mới và phức tạp.",
    "<strong>1. Nhận biết Nhu cầu (Need Recognition):</strong><br/>Quá trình mua bắt đầu bằng việc <span class=\"text-rose-600\"><strong>nhận biết nhu cầu (need recognition)</strong></span> – người mua nhận ra một vấn đề hoặc nhu cầu. Nhu cầu có thể được kích hoạt bởi các kích thích bên trong (ví dụ: một trong những nhu cầu bình thường của một người – đói hoặc khát – tăng lên đến một mức độ trở thành động lực) hoặc các kích thích bên ngoài (ví dụ: một quảng cáo hoặc cuộc trò chuyện với bạn bè có thể khiến bạn nghĩ về việc mua một chiếc xe mới). Ở giai đoạn này, nhà marketing nên nghiên cứu người tiêu dùng để tìm ra những loại nhu cầu hoặc vấn đề nào phát sinh, điều gì gây ra chúng và chúng dẫn người tiêu dùng đến một sản phẩm cụ thể như thế nào.",
    "<strong>2. Tìm kiếm Thông tin (Information Search):</strong><br/>Một người tiêu dùng quan tâm có thể tìm kiếm hoặc không tìm kiếm thêm thông tin. Nếu động lực của người tiêu dùng mạnh mẽ và một sản phẩm thỏa mãn ở gần đó, người đó có thể sẽ mua nó ngay lúc đó. Nếu không, người tiêu dùng có thể lưu trữ nhu cầu trong bộ nhớ hoặc thực hiện tìm kiếm thông tin liên quan đến nhu cầu đó.",
    "Người tiêu dùng có thể lấy thông tin từ nhiều nguồn khác nhau. Chúng bao gồm:",
    "<ul class='list-disc pl-5 mb-1'><li><span class=\"text-rose-600\"><strong>Nguồn cá nhân (Personal sources):</strong></span> Gia đình, bạn bè, hàng xóm, người quen.</li><li><span class=\"text-rose-600\"><strong>Nguồn thương mại (Commercial sources):</strong></span> Quảng cáo, nhân viên bán hàng, trang web của đại lý, bao bì, trưng bày.</li><li><span class=\"text-rose-600\"><strong>Nguồn công cộng (Public sources):</strong></span> Phương tiện thông tin đại chúng, các tổ chức đánh giá người tiêu dùng, tìm kiếm trên mạng xã hội và internet, đánh giá của người dùng đồng trang lứa và các đánh giá trực tuyến khác.</li><li><span class=\"text-rose-600\"><strong>Nguồn thực nghiệm (Experiential sources):</strong></span> Xử lý, kiểm tra và sử dụng sản phẩm.</li></ul>",
    "Ảnh hưởng tương đối của các nguồn thông tin này khác nhau tùy theo sản phẩm và người mua. Nói chung, người tiêu dùng nhận được nhiều thông tin nhất về một sản phẩm từ các nguồn thương mại – những nguồn do nhà marketing kiểm soát. Tuy nhiên, các nguồn hiệu quả nhất có xu hướng là các nguồn cá nhân hoặc thực nghiệm, hoặc các đánh giá trực tuyến độc lập. Các nguồn thương mại thường thông báo cho người mua, nhưng các nguồn cá nhân hoặc công cộng hợp pháp hóa hoặc đánh giá sản phẩm cho người mua. Ví dụ, một nghiên cứu cho thấy 68% người tiêu dùng tin tưởng các ý kiến trực tuyến của người tiêu dùng, trong khi chỉ có khoảng 33% tin tưởng quảng cáo văn bản trên điện thoại di động. Khi ngày càng có nhiều thông tin được thu thập, nhận thức của người tiêu dùng về các thương hiệu và tính năng có sẵn sẽ tăng lên. Một công ty phải thiết kế tổ hợp marketing của mình để làm cho khách hàng tiềm năng nhận biết và hiểu biết về thương hiệu của mình. Nó nên cẩn thận xác định các nguồn thông tin của người tiêu dùng và tầm quan trọng của từng nguồn.",
    "<strong>3. Đánh giá các Lựa chọn thay thế (Evaluation of Alternatives):</strong><br/>Các nhà marketing cần biết về việc đánh giá các lựa chọn thay thế – tức là cách người tiêu dùng xử lý thông tin để chọn giữa các thương hiệu khác nhau. Thật không may, người tiêu dùng không sử dụng một quy trình đánh giá đơn giản và duy nhất trong mọi tình huống mua hàng. Thay vào đó, một số quy trình đánh giá đang hoạt động.",
    "Người tiêu dùng đi đến thái độ đối với các thương hiệu khác nhau thông qua một số quy trình đánh giá. Cách người tiêu dùng đánh giá các lựa chọn thay thế mua hàng phụ thuộc vào từng người tiêu dùng và tình huống mua hàng cụ thể. Trong một số trường hợp, người tiêu dùng sử dụng các tính toán cẩn thận và suy nghĩ logic. Vào những thời điểm khác, chính những người tiêu dùng đó lại ít hoặc không đánh giá gì cả; thay vào đó, họ mua theo cảm hứng và dựa vào trực giác. Đôi khi người tiêu dùng tự mình đưa ra quyết định mua hàng; đôi khi họ tìm đến bạn bè, đánh giá trực tuyến hoặc nhân viên bán hàng để được tư vấn mua hàng.",
    "Giả sử bạn đã thu hẹp lựa chọn máy ảnh của mình xuống còn ba thương hiệu. Và giả sử rằng bạn chủ yếu quan tâm đến bốn thuộc tính: chất lượng hình ảnh, dễ sử dụng, kích thước và giá cả. Bạn đã hình thành niềm tin về cách mỗi thương hiệu hoạt động trên mỗi thuộc tính. Rõ ràng, nếu một thương hiệu được xếp hạng tốt nhất trên tất cả các thuộc tính, chúng ta có thể dự đoán rằng bạn sẽ chọn nó. Tuy nhiên, các thương hiệu có khả năng khác nhau về các thuộc tính khác nhau. Bằng cách biết tầm quan trọng mà bạn gán cho từng thuộc tính, nhà marketing có thể dự đoán và ảnh hưởng đến quyết định mua máy ảnh của bạn một cách đáng tin cậy hơn.",
    "<strong>4. Quyết định Mua (Purchase Decision):</strong><br/>Trong giai đoạn đánh giá, người tiêu dùng xếp hạng các thương hiệu và hình thành ý định mua. Nói chung, quyết định mua của người tiêu dùng sẽ là mua thương hiệu được ưa thích nhất, nhưng hai yếu tố có thể xen vào giữa ý định mua và quyết định mua (Hình 5.5).",
    "<span class=\"text-rose-600\"><strong>Thái độ của người khác (Attitudes of others):</strong></span> Nếu một người quan trọng đối với bạn nghĩ rằng bạn nên mua chiếc xe có giá thấp nhất, thì cơ hội bạn mua một chiếc xe đắt tiền hơn sẽ giảm đi.",
    "<span class=\"text-rose-600\"><strong>Các yếu tố tình huống không lường trước (Unexpected situational factors):</strong></span> Người tiêu dùng có thể hình thành ý định mua dựa trên các yếu tố như thu nhập dự kiến, giá dự kiến và lợi ích sản phẩm dự kiến. Tuy nhiên, các sự kiện không lường trước có thể thay đổi ý định mua. Ví dụ, nền kinh tế có thể xấu đi, một đối thủ cạnh tranh thân thiết có thể giảm giá, hoặc một người bạn có thể báo cáo rằng họ thất vọng với chiếc xe bạn ưa thích. Do đó, sở thích và thậm chí cả ý định mua không phải lúc nào cũng dẫn đến lựa chọn mua thực tế."
  ]),
};
