import { PageData } from '../../types';
import { cleanParagraphs } from '../dataUtils';

const CHAPTER_6_TITLE = "Chương 6: Thị Trường Doanh Nghiệp và Hành Vi Của Khách Hàng Doanh Nghiệp";

export const chap6SecIVPageData: PageData = {
  id: 'chap6-secIV',
  chapterTitle: CHAPTER_6_TITLE,
  pageTitle: "IV. Gắn Kết Khách Hàng Doanh Nghiệp Với Marketing Số và Marketing Xã Hội",
  paragraphs: cleanParagraphs([
    "Sự bùng nổ của công nghệ thông tin, đặc biệt là internet, di động và các phương tiện truyền thông xã hội, đã và đang làm thay đổi sâu sắc cách thức các doanh nghiệp tương tác và thực hiện giao dịch. Trong bối cảnh B2B, những công nghệ này không chỉ tối ưu hóa quy trình mua hàng mà còn mở ra những kênh mới để gắn kết và xây dựng mối quan hệ với khách hàng doanh nghiệp.",
    "<strong>A. Mua hàng điện tử và Mua hàng trực tuyến (E-procurement and Online Buying)</strong>",
    "<em>Các hình thức:</em>",
    "Mua hàng trực tuyến, thường được gọi là <strong><span class=\"text-rose-600\">mua hàng điện tử (e-procurement)</span></strong>, đã có sự tăng trưởng mạnh mẽ trong những năm gần đây và hiện đã trở thành một quy trình chuẩn mực ở hầu hết các doanh nghiệp. Thông qua e-procurement, các chuyên gia marketing B2B có thể kết nối trực tuyến với khách hàng, chia sẻ thông tin marketing, bán sản phẩm và dịch vụ, cung cấp dịch vụ hỗ trợ và duy trì các mối quan hệ liên tục với khách hàng doanh nghiệp của họ.",
    "Các doanh nghiệp có thể thực hiện mua hàng điện tử theo nhiều cách khác nhau. Họ có thể tiến hành <strong><span class=\"text-rose-600\">đấu giá ngược (reverse auctions)</span></strong>, trong đó họ đưa ra các yêu cầu mua hàng trực tuyến và mời các nhà cung cấp tham gia đấu thầu. Hoặc họ có thể tham gia vào các <strong><span class=\"text-rose-600\">giao dịch thương mại trực tuyến (online trading exchanges)</span></strong>, nơi các doanh nghiệp hợp tác với nhau để hỗ trợ cho quá trình giao thương. Doanh nghiệp cũng có thể thực hiện mua hàng điện tử bằng cách thiết lập các <strong><span class=\"text-rose-600\">trang mua hàng riêng (company buying sites)</span></strong>; ví dụ, GE đã mở trang giao dịch của riêng mình để đăng tải các nhu cầu mua, mời thầu, thương thuyết điều khoản và đặt hàng. Một hình thức khác là tạo ra các <strong><span class=\"text-rose-600\">liên kết mạng lưới ngoại bộ (extranet links)</span></strong> với những nhà cung cấp chủ chốt, cho phép khách hàng doanh nghiệp mua trực tiếp trang thiết bị, nguyên vật liệu và vật tư đầu vào từ các nhà cung cấp như Dell hoặc Staples. Một ví dụ cụ thể là Staples đã thiết lập một bộ phận mua hàng B2B chuyên biệt có tên là Staples Business Advantage để phục vụ nhu cầu mua sắm các thiết bị và vật tư văn phòng, cũng như các dịch vụ khác cho các khách hàng doanh nghiệp ở mọi quy mô, từ những doanh nghiệp chỉ có 10 nhân viên cho đến những doanh nghiệp nằm trong danh sách Fortune 1000.",
    "<em>Lợi ích:</em>",
    "Lĩnh vực mua hàng điện tử trên thị trường B2B mang lại nhiều lợi ích đáng kể. Trước tiên, nó giúp cắt giảm các chi phí giao dịch, dẫn đến việc mua bán hiệu quả hơn cho cả bên mua và nhà cung cấp. E-procurement cũng giúp giảm thời gian giữa lúc đặt hàng và lúc giao nhận. Hơn nữa, một chương trình mua hàng trực tuyến có thể loại bỏ phần lớn công việc bàn giấy liên quan đến các thủ tục đặt hàng và tiêu chuẩn truyền thống, đồng thời giúp doanh nghiệp theo dõi sát sao hơn tất cả các hoạt động mua bán. Cuối cùng, nhờ việc tiết kiệm chi phí và thời gian, mua hàng điện tử giải phóng những người có trách nhiệm mua hàng khỏi các công việc giấy tờ và những phiền phức không cần thiết. Thay vào đó, họ có thể tập trung vào các vấn đề mang tính chiến lược hơn như tìm kiếm nguồn cung ứng tốt hơn, làm việc với các nhà cung cấp để giảm chi phí hay phát triển các sản phẩm mới.",
    "<em>Vấn đề:</em>",
    "Tuy nhiên, việc mở rộng nhanh chóng của mua hàng điện tử cũng đặt ra một số vấn đề. Ví dụ, đồng thời với việc giúp nhà cung cấp và khách hàng có thể chia sẻ các dữ liệu kinh doanh và thậm chí hợp tác với nhau trong việc thiết kế sản phẩm, mạng internet cũng có thể làm xói mòn những mối quan hệ giữa khách hàng – nhà cung cấp vốn đã được xây dựng và duy trì qua hàng thập kỷ. Ngày nay, nhiều người mua có xu hướng sử dụng sức mạnh của mạng internet để khiến các nhà cung cấp phải cạnh tranh đối đầu với nhau và tìm kiếm những thương vụ, sản phẩm và thời gian quay vòng tốt hơn trên từng giao dịch cụ thể.",
    "<em>Phân tích và Tầm quan trọng:</em> E-procurement rõ ràng đã mang lại một cuộc cách mạng trong cách thức mua hàng B2B, với những lợi ích không thể phủ nhận về hiệu quả và tiết kiệm chi phí. Tuy nhiên, nó cũng tạo ra một nghịch lý: trong khi tăng cường hiệu quả giao dịch, nó lại có nguy cơ làm suy yếu các mối quan hệ đối tác chiến lược nếu không được quản lý một cách cẩn trọng. Các doanh nghiệp B2B cần phải tích hợp e-procurement vào một chiến lược quan hệ khách hàng rộng lớn hơn, sử dụng công nghệ không chỉ để tối ưu hóa giá mà còn để tăng cường giao tiếp, minh bạch và hợp tác. Các nhà cung cấp, đối mặt với áp lực cạnh tranh về giá trên các nền tảng trực tuyến, cần phải tìm cách tạo ra sự khác biệt và giá trị gia tăng vượt ra ngoài yếu tố giá cả, chẳng hạn như thông qua dịch vụ, sự đổi mới, hoặc khả năng tùy chỉnh.",
    "<strong>B. Marketing số và Marketing qua phương tiện truyền thông xã hội trên thị trường B2B</strong>",
    "<em>Mục tiêu và công cụ:</em>",
    "Đáp lại sự chuyển dịch nhanh chóng của khách hàng doanh nghiệp sang các hình thức mua hàng trực tuyến, các chuyên gia marketing B2B ngày nay đang ngày càng tích cực sử dụng các công cụ <strong><span class=\"text-rose-600\">marketing số và marketing qua các phương tiện truyền thông xã hội</span></strong>. Các công cụ này bao gồm từ các trang web, blog, ứng dụng trên điện thoại di động, thư thông báo điện tử và các mạng lưới trực tuyến độc quyền cho đến những phương tiện truyền thông xã hội chủ đạo như Facebook, LinkedIn, YouTube, Google+ và Twitter. Mục tiêu là để gắn kết và quản lý các mối quan hệ với khách hàng doanh nghiệp ở bất cứ nơi đâu và tại bất cứ thời điểm nào.",
    "Lĩnh vực marketing số và marketing qua phương tiện truyền thông xã hội trên thị trường B2B không chỉ đơn thuần là tăng trưởng mà còn đang thực sự bùng nổ và nhanh chóng trở thành một không gian mới, quan trọng cho việc gắn kết các khách hàng doanh nghiệp.",
    "Một ví dụ điển hình là Maersk Line, một trong những hãng vận tải container đường thủy hàng đầu thế giới. Mặc dù hoạt động trong một ngành công nghiệp truyền thống, Maersk Line đã trở thành một trong những nhà làm marketing số và marketing qua phương tiện truyền thông xã hội B2B tiên tiến và toàn diện nhất. Họ đã triển khai một cách mạnh mẽ các hoạt động trên nhiều kênh truyền thông xã hội, bao gồm Facebook (với hơn 1,1 triệu người theo dõi và mức độ tương tác cao), Instagram (nơi họ chia sẻ hình ảnh và câu chuyện về nhân viên và khách hàng để làm sống động hình ảnh thương hiệu), YouTube (đăng tải các video thông tin và giáo dục), Twitter (cung cấp tin tức, sự kiện mới nhất và tạo ra các cuộc hội thoại), và LinkedIn (gắn kết với khách hàng, những người nổi tiếng và có tầm ảnh hưởng trong ngành). Mục tiêu của Maersk Line khi sử dụng tất cả các kênh truyền thông xã hội này là để \"đến gần hơn với các khách hàng của chúng tôi\".",
    "So với các phương pháp bán hàng và truyền thông truyền thống, kỹ thuật số và các phương tiện truyền thông xã hội có khả năng tạo nên sự tương tác và gắn kết với khách hàng ở mức độ sâu sắc hơn. Các chuyên gia marketing trên thị trường B2B hiểu rằng họ không thực sự bán hàng cho các \"doanh nghiệp\" một cách trừu tượng, mà họ đang bán hàng cho các cá nhân cụ thể trong các doanh nghiệp đó, những người có ảnh hưởng đến quyết định mua. Và ngày nay, các khách hàng doanh nghiệp này thường xuyên kết nối với thế giới thông qua các phương tiện kỹ thuật số, bất kể đó là máy tính cá nhân, máy tính bảng hay điện thoại thông minh.",
    "Marketing B2B thường được thực hiện trên các mạng xã hội, nhưng môi trường kỹ thuật số cũng mang lại hàng loạt các công cụ và ứng dụng kết nối mạng lưới mới. Một số doanh nghiệp B2B có thể mắc sai lầm khi cho rằng kỹ thuật số và các phương tiện truyền thông xã hội ngày nay chủ yếu chỉ hữu ích với các doanh nghiệp cung ứng sản phẩm và dịch vụ cho người tiêu dùng cuối cùng (B2C). Tuy nhiên, thực tế cho thấy, bất kể là ngành nghề nào, các nền tảng kỹ thuật số đều có thể là những công cụ đầy sức mạnh để gắn kết với khách hàng và với các cộng đồng quan trọng khác. Ví dụ, General Electric (GE), một \"doanh nghiệp hạ tầng công nghiệp\" với phần lớn doanh thu đến từ các sản phẩm và dịch vụ công nghiệp, đã trở thành một hình mẫu về cách một doanh nghiệp B2B có thể sử dụng hiệu quả kỹ thuật số và phương tiện truyền thông xã hội. GE không chỉ sử dụng các nền tảng này để trực tiếp gắn kết và hỗ trợ các khách hàng doanh nghiệp mà còn để kể những câu chuyện thương hiệu hấp dẫn về GE một cách rộng rãi hơn, đảm bảo rằng công ty luôn mang tính gắn kết, tính thời đại và dễ tiếp cận.",
    "<em>Tầm quan trọng của việc gắn kết cá nhân trong doanh nghiệp:</em>",
    "<em>Phân tích và Tầm quan trọng:</em> Quan niệm cho rằng truyền thông xã hội và marketing số chỉ phù hợp với thị trường B2C là một nhận định sai lầm và hạn hẹp. Thực tế đã chứng minh rằng các nền tảng kỹ thuật số là những công cụ vô cùng mạnh mẽ để các doanh nghiệp B2B có thể gắn kết với khách hàng, xây dựng thương hiệu, và tạo ra lợi thế cạnh tranh. Việc áp dụng marketing số và truyền thông xã hội trong B2B không chỉ đơn thuần là việc sử dụng các kênh truyền thông mới, mà nó còn đòi hỏi một sự thay đổi căn bản trong tư duy marketing – từ việc \"đẩy\" thông điệp một chiều sang việc \"kéo\" khách hàng bằng cách cung cấp nội dung giá trị, xây dựng cộng đồng và tạo ra các cuộc đối thoại hai chiều. Các nhà marketing B2B cần phải phát triển năng lực sáng tạo nội dung hấp dẫn và phù hợp, kỹ năng quản lý cộng đồng trực tuyến, và khả năng lắng nghe, phân tích các cuộc thảo luận trên mạng xã hội để có thể thành công trong không gian số ngày càng cạnh tranh này.",
    "Một mối liên hệ tiềm ẩn nhưng quan trọng là giữa dữ liệu từ các giao dịch e-procurement và việc cá nhân hóa các nỗ lực marketing số. E-procurement tạo ra một lượng lớn dữ liệu chi tiết về lịch sử mua hàng, tần suất, loại sản phẩm ưa thích, và các thông tin khác của khách hàng doanh nghiệp. Dữ liệu này, khi được phân tích và khai thác một cách hiệu quả, có thể cung cấp những thông tin đầu vào vô cùng quý giá cho việc cá nhân hóa các chiến dịch marketing số và truyền thông xã hội. Ví dụ, một khách hàng doanh nghiệp thường xuyên mua một loại vật tư cụ thể thông qua hệ thống e-procurement có thể được nhắm mục tiêu bằng các bài viết blog chuyên sâu, các buổi hội thảo trực tuyến (webinar) liên quan, hoặc thông tin về các sản phẩm mới bổ sung cho nhu cầu của họ thông qua email marketing hoặc các tin nhắn được cá nhân hóa trên LinkedIn. Điều này tạo ra một vòng lặp thông tin và tương tác, không chỉ giúp tăng cường mối quan hệ với khách hàng mà còn nâng cao đáng kể hiệu quả của các hoạt động marketing, biến dữ liệu giao dịch thành lợi thế cạnh tranh."
  ]),
};