import { PageData } from '../../types';
import { cleanParagraphs } from '../dataUtils';

const CHAPTER_6_TITLE = "Chương 6: Thị Trường Doanh Nghiệp và Hành Vi Của Khách Hàng Doanh Nghiệp";

export const chap6SecIIIPageData: PageData = {
  id: 'chap6-secIII',
  chapterTitle: CHAPTER_6_TITLE,
  pageTitle: "III. Quy Trình Ra Quyết Định Mua Của Khách Hàng Doanh Nghiệp",
  paragraphs: cleanParagraphs([
    "Giới thiệu Hình 6.3, mô tả một quy trình ra quyết định mua của khách hàng doanh nghiệp bao gồm 8 bước. Quy trình này thường được áp dụng đầy đủ khi người mua đối mặt với một tình huống mua mới (new task). Trong khi đó, đối với các tình huống mua lặp lại không điều chỉnh (straight rebuy) hoặc mua lặp lại có điều chỉnh (modified rebuy), một số bước có thể được bỏ qua hoặc rút gọn.",
    "<strong>A. Bước 1: Nhận thức vấn đề (Problem Recognition)</strong>",
    "Quá trình mua của doanh nghiệp bắt đầu khi một cá nhân hoặc bộ phận nào đó trong doanh nghiệp nhận thấy một vấn đề hay một nhu cầu có thể được giải quyết hoặc đáp ứng bằng việc mua một sản phẩm hoặc dịch vụ cụ thể. Sự nhận thức này có thể xuất phát từ các kích thích bên trong tổ chức, chẳng hạn như doanh nghiệp quyết định tung ra một sản phẩm mới và do đó cần nguyên vật liệu cũng như trang thiết bị mới để phục vụ sản xuất; một máy móc hiện có bị hỏng hóc và cần các bộ phận thay thế; hoặc có thể giám đốc mua hàng cảm thấy không hài lòng với chất lượng sản phẩm, dịch vụ hoặc giá cả của nhà cung cấp hiện tại. Mặt khác, nhận thức vấn đề cũng có thể đến từ các kích thích bên ngoài, ví dụ như người mua có được những ý tưởng mới tại một cuộc triển lãm thương mại, xem một quảng cáo hoặc truy cập một trang web giới thiệu sản phẩm, hoặc nhận được một cuộc gọi từ một nhân viên bán hàng chào bán một sản phẩm tốt hơn hoặc với mức giá cạnh tranh hơn.",
    "Trong thực tế, các chuyên gia marketing B2B thường chủ động đóng vai trò trong việc kích hoạt nhận thức vấn đề của khách hàng. Họ có thể cảnh báo khách hàng về các vấn đề tiềm ẩn mà khách hàng chưa nhận ra và sau đó cho thấy sản phẩm hoặc dịch vụ của họ cung cấp giải pháp hiệu quả cho những vấn đề đó. Một ví dụ điển hình là chiến dịch quảng cáo B2B từng đoạt giải thưởng \"High Performance. Delivered.\" (Mang lại hiệu suất cao) của hãng tư vấn Accenture. Chiến dịch này đã chỉ ra nhu cầu cấp thiết đối với các doanh nghiệp là phải bắt kịp tốc độ với sự phát triển của công nghệ số, đồng thời đề xuất rằng \"Công nghệ số của Accenture có thể giúp bạn thu hút thêm khách hàng.\" Hình ảnh những con bướm đêm bay về phía ánh sáng của màn hình điện thoại thông minh trong quảng cáo này đã ẩn dụ cho sức hút của công nghệ số. Giải pháp mà Accenture đưa ra là: \"Địa vị của chúng tôi trong ngành cùng với khả năng tích hợp việc tương tác, phân tích và tính cơ động có thể giúp bạn tận dụng các cơ hội để đổi mới và hoàn thiện.” Các quảng cáo khác trong cùng chuỗi chiến dịch cũng kể những câu chuyện thành công về việc Accenture đã giúp đỡ các khách hàng doanh nghiệp như thế nào trong việc nhận diện và giải quyết các vấn đề của họ.",
    "Phân tích và Tầm quan trọng: Đây là bước khởi đầu mang tính quyết định của toàn bộ quy trình mua. Các nhà marketing B2B có thể và nên chủ động tham gia vào giai đoạn này bằng cách giáo dục thị trường, cung cấp thông tin về các xu hướng mới, hoặc chỉ ra những cơ hội cải tiến mà sản phẩm/dịch vụ của họ có thể mang lại. Việc hiểu rõ các yếu tố nào thường kích hoạt sự nhận thức vấn đề của khách hàng mục tiêu sẽ giúp nhà marketing định vị sản phẩm hoặc dịch vụ của mình một cách hiệu quả như một giải pháp tối ưu.",
    "<strong>B. Bước 2: Mô tả khái quát nhu cầu (General Need Description)</strong>",
    "Sau khi đã nhận ra được nhu cầu, bên mua sẽ tiếp tục chuẩn bị một bản mô tả khái quát về nhu cầu đó. Bản mô tả này thường bao gồm các đặc điểm chung và số lượng ước tính của mặt hàng đang có nhu cầu. Đối với những mặt hàng tiêu chuẩn, thông dụng, giai đoạn này thường không gặp nhiều trở ngại. Tuy nhiên, đối với những mặt hàng phức tạp hơn, bên mua có thể cần phải làm việc và tham khảo ý kiến của những người khác trong tổ chức như các kỹ sư, người sử dụng trực tiếp sản phẩm, hoặc các chuyên gia tư vấn bên ngoài để có thể xác định một cách chính xác các đặc điểm riêng của nhu cầu. Trong giai đoạn này, họ cũng có thể muốn đánh giá mức độ quan trọng tương đối của các yếu tố như độ an toàn, độ bền, giá cả và các đặc điểm mong muốn khác của mặt hàng.",
    "Các chuyên gia marketing B2B có thể đóng một vai trò hữu ích trong giai đoạn này bằng cách chủ động giúp người mua xác định và làm rõ nhu cầu của họ, đồng thời cung cấp thông tin về giá trị của những đặc điểm khác nhau trong các sản phẩm hoặc dịch vụ có khả năng thỏa mãn nhu cầu đó.",
    "Phân tích và Tầm quan trọng: Giai đoạn này mang đến một cơ hội quý giá để các nhà marketing tham gia sớm vào quá trình ra quyết định của khách hàng. Bằng cách cung cấp thông tin và tư vấn, họ có thể giúp định hình các tiêu chí nhu cầu của khách hàng theo hướng có lợi cho những điểm mạnh và sự khác biệt của sản phẩm hoặc dịch vụ mà họ cung cấp.",
    "<strong>C. Bước 3: Xác định đặc điểm sản phẩm (Product Specification)</strong>",
    "Tiếp theo giai đoạn mô tả nhu cầu, bên mua hàng phải tiến hành xác định các đặc điểm kỹ thuật chi tiết của sản phẩm cần mua. Công việc này thường được thực hiện với sự trợ giúp của một nhóm kỹ sư chuyên về <strong><span class=\"text-rose-600\">phân tích giá trị sản phẩm (product value analysis)</span></strong>. Phân tích giá trị sản phẩm là một phương pháp tiếp cận có hệ thống nhằm mục đích giảm chi phí thông qua việc nghiên cứu kỹ lưỡng các thành phần của sản phẩm để quyết định xem liệu chúng có cần được thiết kế lại, tiêu chuẩn hóa, hoặc có thể được chế tạo bằng các phương pháp sản xuất có chi phí thấp hơn hay không. Nhóm phân tích giá trị sẽ quyết định và lựa chọn các đặc điểm sản phẩm được cho là hợp lý nhất và sau đó xác định rõ ràng từng đặc điểm đó trong bản yêu cầu kỹ thuật.",
    "Không chỉ người mua, người bán cũng có thể sử dụng phương pháp phân tích giá trị như một công cụ hữu hiệu để giành được khách hàng mới. Bằng cách chỉ ra một cách thức tốt hơn, hiệu quả hơn về chi phí để tạo ra một sản phẩm, những người bán khác có thể chuyển một tình huống mua lặp lại thông thường thành một tình huống mua mới, từ đó tạo ra cơ hội kinh doanh mới cho chính họ.",
    "Phân tích và Tầm quan trọng: Phân tích giá trị sản phẩm là một công cụ mạnh mẽ, mang lại lợi ích cho cả người mua và người bán. Đối với người mua, nó giúp tối ưu hóa chi phí và đảm bảo sản phẩm đáp ứng đúng yêu cầu. Đối với người bán, nó là cơ hội để chứng minh giá trị vượt trội của sản phẩm/dịch vụ, đề xuất các giải pháp sáng tạo và hiệu quả hơn về chi phí, từ đó tạo lợi thế cạnh tranh.",
    "<strong>D. Bước 4: Tìm kiếm nhà cung cấp (Supplier Search)</strong>",
    "Đến bước này của quy trình, người mua bắt đầu thực hiện việc tìm kiếm các nhà cung cấp tiềm năng để có thể tìm ra những đối tác tốt nhất. Người mua có thể tập hợp một danh sách rút gọn các nhà cung cấp được đánh giá là có chất lượng thông qua việc xem xét các danh mục thương mại, thực hiện các tìm kiếm trực tuyến, hoặc gọi điện thoại cho các doanh nghiệp khác trong ngành để tham khảo ý kiến và kinh nghiệm. Ngày càng có nhiều doanh nghiệp chuyển sang tham khảo thông tin trên mạng internet để tìm kiếm nhà cung cấp. Điều này đã tạo ra một sân chơi bình đẳng hơn, mang lại cho các nhà cung cấp nhỏ rất nhiều lợi thế so với những đối thủ cạnh tranh lớn hơn, có tên tuổi lâu đời hơn.",
    "Đối với các tình huống mua mới, cũng như đối với những mặt hàng càng phức tạp và có chi phí càng cao, thì lượng thời gian mà người mua dành cho việc tìm kiếm nhà cung cấp cũng càng lớn hơn.",
    "Nhiệm vụ của nhà cung cấp trong giai đoạn này là phải đảm bảo rằng công ty của mình được liệt kê trong các danh mục thương mại chính, xây dựng được danh tiếng tốt trên thị trường, và quan trọng nhất là phải đảm bảo rằng công ty của họ được người mua xem xét đến. Nhân viên bán hàng nên chủ động theo dõi các doanh nghiệp đang trong quá trình tìm kiếm nhà cung cấp và đảm bảo rằng công ty của họ nằm trong danh sách cân nhắc của khách hàng tiềm năng.",
    "Phân tích và Tầm quan trọng: Trong kỷ nguyên số, sự hiện diện trực tuyến mạnh mẽ và một danh tiếng tốt trên internet là những yếu tố cực kỳ quan trọng đối với các nhà cung cấp B2B. Các chiến lược tối ưu hóa công cụ tìm kiếm (SEO), marketing nội dung (content marketing) và quản lý danh tiếng trực tuyến (online reputation management) trở thành những công cụ thiết yếu để thu hút sự chú ý của người mua trong giai đoạn tìm kiếm này.",
    "<strong>E. Bước 5: Yêu cầu chào hàng (Proposal Solicitation)</strong>",
    "Sau khi đã có một danh sách các nhà cung cấp tiềm năng, bên mua sẽ mời các nhà cung cấp được đánh giá là có chất lượng này đệ trình các đề xuất chào hàng (proposals). Đáp lại lời mời này, một vài nhà cung cấp có thể chỉ đơn giản là đề xuất người mua truy cập vào trang web của họ hoặc tham khảo các tài liệu giới thiệu sản phẩm, hoặc cử nhân viên bán hàng gọi điện thoại trực tiếp đến khách hàng tiềm năng. Tuy nhiên, đối với những hạng mục mua sắm phức tạp hoặc có giá trị lớn, bên mua thường yêu cầu một bản đề xuất chi tiết bằng văn bản hoặc một cuộc thuyết trình chính thức từ từng bên cung ứng tiềm năng.",
    "Các chuyên gia marketing B2B cần phải được trang bị đầy đủ các kỹ năng cần thiết trong việc nghiên cứu, soạn thảo và thuyết trình các đề xuất chào hàng sao cho đáp ứng tốt nhất các yêu cầu của bên mua. Một đề xuất chào hàng hiệu quả nên được trình bày như một tài liệu marketing thuyết phục chứ không chỉ đơn thuần là một tài liệu kỹ thuật khô khan. Phần trình bày cũng cần phải tạo được niềm tin nơi khách hàng và làm cho doanh nghiệp của mình trở nên nổi bật, khác biệt so với các đối thủ cạnh tranh.",
    "Phân tích và Tầm quan trọng: Đây là một giai đoạn quan trọng, nơi nhà cung cấp có cơ hội thể hiện sự hiểu biết sâu sắc của mình về nhu cầu và vấn đề của khách hàng, đồng thời trình bày giải pháp của mình một cách thuyết phục và chuyên nghiệp. Chất lượng của bản đề xuất chào hàng, cả về nội dung lẫn hình thức, có thể là yếu tố mang tính quyết định đến việc liệu nhà cung cấp có được lựa chọn hay không.",
    "<strong>F. Bước 6: Lựa chọn nhà cung cấp (Supplier Selection)</strong>",
    "Tại bước này, các thành viên của trung tâm mua sẽ tiến hành xem xét kỹ lưỡng các đề xuất chào hàng đã nhận được và sau đó lựa chọn một hoặc nhiều nhà cung cấp. Trong suốt giai đoạn lựa chọn nhà cung cấp, trung tâm mua thường sẽ xây dựng một danh sách các đặc điểm mong muốn ở một nhà cung cấp lý tưởng và xác định mức độ quan trọng tương đối của từng đặc điểm đó. Các đặc điểm này có thể bao gồm chất lượng sản phẩm và dịch vụ, danh tiếng của nhà cung cấp trên thị trường, thời gian giao hàng cam kết, hành vi trách nhiệm và đạo đức của doanh nghiệp, khả năng truyền thông trung thực và minh bạch, và tất nhiên là cả giá cả cạnh tranh. Các thành viên của trung tâm mua sẽ đánh giá các nhà cung cấp dựa trên những tiêu chí này và từ đó xác định ra nhà cung cấp tốt nhất.",
    "Người mua có thể cố gắng thương lượng thêm với các nhà cung cấp được ưu tiên để có được mức giá và các điều khoản hợp đồng tốt hơn trước khi đưa ra lựa chọn cuối cùng. Sau đó, họ có thể quyết định lựa chọn một nhà cung cấp duy nhất hoặc một vài nhà cung cấp. Nhiều người mua có xu hướng thích sử dụng nhiều nguồn cung ứng để tránh tình trạng hoàn toàn phụ thuộc vào một nhà cung cấp duy nhất, đồng thời việc này cũng cho phép họ so sánh mức giá và hiệu quả hoạt động của một số nhà cung cấp theo thời gian. Ngày nay, các nhà quản lý có nhiệm vụ phát triển nhà cung cấp thường mong muốn xây dựng một mạng lưới các đối tác-nhà cung cấp chính thức, có mối quan hệ chặt chẽ, những người có thể giúp công ty mang lại nhiều giá trị hơn cho khách hàng của chính họ.",
    "Phân tích và Tầm quan trọng: Quá trình lựa chọn nhà cung cấp trong B2B thường dựa trên một tập hợp đa dạng các tiêu chí, không chỉ giới hạn ở yếu tố giá cả. Khả năng xây dựng một mối quan hệ đối tác lâu dài, tin cậy và mang lại giá trị gia tăng ngày càng được các doanh nghiệp mua hàng coi trọng.",
    "<strong>G. Bước 7: Soạn thảo đơn đặt hàng (Order-Routine Specification)</strong>",
    "Đến bước này, sau khi đã lựa chọn được nhà cung cấp (hoặc các nhà cung cấp), bên mua sẽ tiến hành soạn thảo đơn đặt hàng cuối cùng. Đơn đặt hàng này bao gồm các thông tin chi tiết như danh sách các đặc điểm kỹ thuật của sản phẩm/dịch vụ, số lượng đặt hàng cụ thể, thời gian giao hàng mong muốn, các chính sách liên quan đến việc hoàn trả sản phẩm (nếu có), và các điều khoản bảo hành.",
    "Trong trường hợp các mặt hàng cần được bảo trì, sửa chữa và vận hành thường xuyên (MRO – Maintenance, Repair, and Operations), bên mua có thể cần sử dụng một <strong><span class=\"text-rose-600\">hợp đồng khung (blanket contract)</span></strong> thay vì các đơn đặt hàng định kỳ riêng lẻ. Một hợp đồng khung sẽ tạo ra một mối quan hệ cung ứng dài hạn, trong đó nhà cung cấp cam kết sẽ cung ứng lại sản phẩm/dịch vụ cho bên mua khi cần thiết, với mức giá đã được hai bên thỏa thuận trước, trong một khoảng thời gian nhất định.",
    "Nhiều tổ chức mua hàng lớn hiện nay đang thực hiện mô hình <strong><span class=\"text-rose-600\">lưu kho do người bán quản lý (Vendor-Managed Inventory - VMI)</span></strong>. Theo mô hình này, họ chuyển giao trách nhiệm đặt hàng và quản lý hàng tồn kho cho chính các nhà cung cấp của mình. Trong hệ thống VMI, bên mua sẽ chia sẻ trực tiếp các thông tin về doanh số bán hàng và tình hình tồn kho của mình với các nhà cung cấp chủ chốt. Dựa trên những thông tin này, các nhà cung ứng sẽ chủ động theo dõi, điều chỉnh mức tồn kho và tự động cấp bổ sung hàng hóa cho bên mua khi cần thiết. Ví dụ, hầu hết những nhà cung cấp chính cho các tập đoàn bán lẻ lớn như Walmart, Target, Home Depot và Lowe's đều phải thực hiện trách nhiệm quản lý hàng tồn kho cho các đối tác này.",
    "Phân tích và Tầm quan trọng: Các công cụ như hợp đồng khung và mô hình VMI là minh chứng rõ ràng cho mức độ tích hợp và hợp tác ngày càng sâu sắc trong các mối quan hệ B2B hiện đại. Những phương thức này không chỉ giúp tăng cường hiệu quả hoạt động mà còn góp phần giảm thiểu chi phí cho cả hai bên mua và bán, đồng thời đảm bảo sự ổn định và liên tục của chuỗi cung ứng.",
    "<strong>H. Bước 8: Đánh giá việc thực hiện (Performance Review)</strong>",
    "Trong giai đoạn cuối cùng này của quy trình mua hàng, bên mua sẽ tiến hành xem xét và đánh giá lại việc thực hiện của nhà cung cấp. Bên mua có thể liên lạc trực tiếp với những người sử dụng sản phẩm/dịch vụ trong tổ chức của mình và đề nghị họ đưa ra những đánh giá về mức độ hài lòng đối với sản phẩm/dịch vụ cũng như đối với nhà cung cấp.",
    "Kết quả của việc đánh giá này có thể dẫn tới việc bên mua đưa ra quyết định tiếp tục duy trì mối quan hệ và đặt hàng tiếp, hoặc đề xuất những điều chỉnh cần thiết trong đơn hàng tiếp theo (mua lại có điều chỉnh), hoặc thậm chí là hủy bỏ hoàn toàn thỏa thuận mua hàng với nhà cung cấp đó nếu hiệu suất không đạt yêu cầu.",
    "Về phía nhà cung cấp (bên bán), công việc của họ trong giai đoạn này là phải theo dõi sát sao các yếu tố mà bên mua đưa ra trong quá trình đánh giá, từ đó có những điều chỉnh cần thiết để chắc chắn rằng mình đã và sẽ tiếp tục mang lại sự hài lòng như mong đợi cho khách hàng.",
    "Phân tích và Tầm quan trọng: Đây là một bước cực kỳ quan trọng để duy trì và phát triển các mối quan hệ khách hàng lâu dài trong B2B. Việc thu thập phản hồi một cách thường xuyên và chủ động cải tiến liên tục dựa trên những phản hồi đó là điều cần thiết để đảm bảo sự hài lòng của khách hàng và giữ chân họ trong một môi trường cạnh tranh.",
    "<strong>I. Tính phức tạp của quy trình thực tế</strong>",
    "Mô hình 8 bước được trình bày ở trên thực chất chỉ là một cái nhìn đơn giản hóa về cách thức việc mua hàng của khách hàng doanh nghiệp diễn ra, đặc biệt là trong một tình huống mua lần đầu. Tuy nhiên, quy trình mua hàng trong thực tế thường phức tạp hơn nhiều. Trong các tình huống mua lặp lại không có điều chỉnh hoặc mua lặp lại có điều chỉnh, một vài bước trong quy trình có thể được rút gọn hoặc thậm chí bỏ qua hoàn toàn. Mỗi tổ chức mua hàng có những cách thức và quy trình riêng, và từng tình huống mua hàng cụ thể lại có những yêu cầu riêng biệt không hoàn toàn giống nhau. Các thành viên khác nhau của trung tâm mua có thể tham gia vào những bước khác nhau của quy trình. Mặc dù một số bước nhất định của quy trình mua hàng thường diễn ra theo một trình tự logic như đã mô tả, bên mua không phải lúc nào cũng thực hiện theo đúng trật tự đó, và họ có thể thêm vào một vài bước khác hoặc lặp lại một số bước nhất định của quy trình. Cuối cùng, một mối quan hệ khách hàng có thể liên quan đến nhiều loại hình mua hàng khác nhau theo thời gian, và do đó, bên bán phải quản lý mối quan hệ với khách hàng một cách tổng thể, chứ không chỉ quan tâm đến từng giao dịch mua bán riêng lẻ.",
    "Phân tích và Tầm quan trọng: Điều này nhấn mạnh sự cần thiết của tính linh hoạt và khả năng tùy chỉnh cao trong cách tiếp cận của các nhà marketing B2B. Không có một giải pháp \"một kích cỡ phù hợp cho tất cả\" (one-size-fits-all) trong marketing B2B. Thay vào đó, các nhà marketing cần phải hiểu rõ đặc thù của từng khách hàng, từng tình huống mua để có thể điều chỉnh chiến lược và quy trình tương tác cho phù hợp.",
    "Quy trình ra quyết định mua của doanh nghiệp, mặc dù được trình bày một cách tuần tự qua 8 bước, nhưng trong thực tế lại mang tính lặp đi lặp lại và tương tác cao. Điều này đòi hỏi các nhà marketing B2B phải duy trì sự tham gia và cung cấp giá trị một cách liên tục tại nhiều điểm tiếp xúc khác nhau trong suốt hành trình mua của khách hàng, chứ không chỉ tập trung nỗ lực vào giai đoạn chào hàng hay chốt đơn. Các giai đoạn trong quy trình có thể chồng chéo lên nhau, và thông tin mới thu thập được ở một giai đoạn sau có thể khiến bên mua phải quay trở lại các giai đoạn trước đó để xem xét và điều chỉnh lại các quyết định của mình. Ví dụ, trong quá trình \"Lựa chọn nhà cung cấp\" (Bước 6), việc phát hiện ra một thông tin mới quan trọng về một nhà cung cấp tiềm năng có thể khiến bên mua phải \"Mô tả lại khái quát nhu cầu\" (Bước 2) hoặc thậm chí \"Xác định lại đặc điểm sản phẩm\" (Bước 3) cho phù hợp hơn. Do đó, các nhà marketing B2B cần phải xây dựng một chiến lược \"luôn hiện diện\" (always-on), sẵn sàng cung cấp thông tin, tư vấn và hỗ trợ phù hợp ở tất cả các giai đoạn, đồng thời phải linh hoạt để thích ứng với những thay đổi và sự lặp lại không thể đoán trước trong quy trình của khách hàng. Các công cụ như marketing nội dung, hệ thống quản trị quan hệ khách hàng (CRM), và các nền tảng tương tác kỹ thuật số trở nên vô cùng quan trọng để duy trì sự gắn kết và hỗ trợ khách hàng một cách hiệu quả trong suốt hành trình phức tạp này.",
    "Bên cạnh đó, sự trỗi dậy của các khái niệm như \"Phân tích giá trị sản phẩm\" (Product Value Analysis - PVA) ở Bước 3 và xu hướng \"Lưu kho do người bán quản lý\" (Vendor-Managed Inventory - VMI) ở Bước 7 cho thấy một động lực kép đang diễn ra trong lĩnh vực B2B: một mặt, các doanh nghiệp mua hàng ngày càng tìm cách tối ưu hóa chi phí một cách khoa học và bài bản thông qua PVA; mặt khác, họ cũng ngày càng tăng cường hợp tác và tích hợp sâu hơn vào chuỗi cung ứng thông qua các mô hình như VMI. Hai khái niệm này, dù xuất hiện ở các bước khác nhau của quy trình mua hàng, cùng phản ánh một xu hướng lớn hơn là các doanh nghiệp đang nỗ lực đạt được hiệu quả hoạt động cao hơn thông qua cả việc tối ưu hóa thiết kế và sản xuất sản phẩm lẫn việc hợp lý hóa các quy trình trong chuỗi cung ứng. Điều này mang một hàm ý quan trọng đối với các nhà cung cấp B2B: để thành công, họ không chỉ cần cạnh tranh về giá cả hay chất lượng sản phẩm đơn thuần, mà còn phải chứng minh được khả năng đóng góp vào việc tối ưu hóa chi phí và quy trình tổng thể của khách hàng. Họ cần phải cho thấy một cách rõ ràng lợi tức đầu tư (ROI) mà họ mang lại và khả năng tích hợp một cách liền mạch vào hệ thống hoạt động của khách hàng.",
    "Nhìn một cách tổng thể, toàn bộ quy trình 8 bước, từ \"Nhận thức vấn đề\" cho đến \"Đánh giá việc thực hiện\", đã nhấn mạnh một sự thay đổi trong vai trò của nhà marketing B2B. Họ không còn đơn thuần là những người bán hàng, mà ngày càng trở thành những nhà tư vấn và đối tác chiến lược của khách hàng. Ở Bước 1, nhà marketing B2B chủ động \"cảnh báo khách hàng về các vấn đề tiềm ẩn\" và \"cho thấy sản phẩm/dịch vụ của họ cung cấp được giải pháp\". Ở Bước 2, họ \"có thể giúp người mua xác định nhu cầu\". Và ở Bước 3, \"người bán cũng có thể sử dụng phân tích giá trị như một công cụ trợ giúp để giành được khách hàng mới\". Xuyên suốt các bước còn lại, vai trò của nhà marketing B2B là cung cấp thông tin, thuyết trình giải pháp, tham gia thương lượng và đảm bảo sự hài lòng sau bán hàng. Tất cả những điều này cho thấy một sự chuyển dịch rõ ràng từ một mối quan hệ mang tính giao dịch sang một mối quan hệ tư vấn, nơi nhà cung cấp chủ động tham gia vào việc giúp khách hàng xác định vấn đề, định hình giải pháp và cuối cùng là đạt được các mục tiêu kinh doanh của họ. Điều này đòi hỏi các nhà marketing B2B phải trang bị cho mình không chỉ kiến thức sâu rộng về sản phẩm/dịch vụ của công ty mà còn cả sự am hiểu về ngành nghề kinh doanh của khách hàng và các kỹ năng tư vấn chuyên nghiệp.",
    `
<div class="overflow-x-auto py-2">
  <p class="font-semibold text-lg my-3">Bảng 3: Quy Trình Ra Quyết Định Mua Của Doanh Nghiệp: Các Giai Đoạn, Hoạt Động Chính và Hàm Ý Marketing</p>
  <table class="min-w-full w-full table-auto border-collapse border border-slate-400 prose-sm">
    <thead class="bg-slate-50">
      <tr>
        <th class="border border-slate-300 px-3 py-2 text-left text-xs font-semibold text-slate-700 uppercase tracking-wider">Bước trong Quy trình</th>
        <th class="border border-slate-300 px-3 py-2 text-left text-xs font-semibold text-slate-700 uppercase tracking-wider">Mô tả Hoạt Động Chính của Người Mua</th>
        <th class="border border-slate-300 px-3 py-2 text-left text-xs font-semibold text-slate-700 uppercase tracking-wider">Vai trò/Cơ hội của Nhà Marketing B2B</th>
      </tr>
    </thead>
    <tbody class="bg-white divide-y divide-slate-200">
      <tr>
        <td class="border border-slate-300 px-3 py-2 text-sm text-slate-700">1. Nhận thức vấn đề</td>
        <td class="border border-slate-300 px-3 py-2 text-sm text-slate-700">Nhận ra vấn đề/nhu cầu có thể được đáp ứng bằng việc mua sản phẩm/dịch vụ. Có thể do kích thích bên trong hoặc bên ngoài.</td>
        <td class="border border-slate-300 px-3 py-2 text-sm text-slate-700">Chủ động tạo nhận thức vấn đề (ví dụ: giáo dục thị trường, chỉ ra cơ hội cải tiến), định vị sản phẩm/dịch vụ như một giải pháp.</td>
      </tr>
      <tr>
        <td class="border border-slate-300 px-3 py-2 text-sm text-slate-700">2. Mô tả khái quát nhu cầu</td>
        <td class="border border-slate-300 px-3 py-2 text-sm text-slate-700">Chuẩn bị bản mô tả khái quát nhu cầu (đặc điểm, số lượng). Có thể làm việc với kỹ sư, người sử dụng, chuyên gia tư vấn cho mặt hàng phức tạp.</td>
        <td class="border border-slate-300 px-3 py-2 text-sm text-slate-700">Giúp người mua xác định và làm rõ nhu cầu, cung cấp thông tin về giá trị của các đặc điểm sản phẩm, định hình tiêu chí nhu cầu theo hướng có lợi.</td>
      </tr>
      <tr>
        <td class="border border-slate-300 px-3 py-2 text-sm text-slate-700">3. Xác định đặc điểm sản phẩm</td>
        <td class="border border-slate-300 px-3 py-2 text-sm text-slate-700">Xác định đặc điểm kỹ thuật chi tiết của sản phẩm, thường với sự trợ giúp của nhóm kỹ sư <strong><span class="text-rose-600">phân tích giá trị sản phẩm (product value analysis)</span></strong>.</td>
        <td class="border border-slate-300 px-3 py-2 text-sm text-slate-700">Sử dụng phân tích giá trị để chứng minh giá trị vượt trội, đề xuất giải pháp hiệu quả chi phí, chuyển tình huống mua lặp lại thành mua mới.</td>
      </tr>
      <tr>
        <td class="border border-slate-300 px-3 py-2 text-sm text-slate-700">4. Tìm kiếm nhà cung cấp</td>
        <td class="border border-slate-300 px-3 py-2 text-sm text-slate-700">Tìm kiếm nhà cung cấp tốt nhất qua danh mục, tìm kiếm trực tuyến, tham khảo. Thời gian tìm kiếm lớn hơn cho mua mới/mặt hàng phức tạp.</td>
        <td class="border border-slate-300 px-3 py-2 text-sm text-slate-700">Đảm bảo sự hiện diện trực tuyến (SEO, content marketing), xây dựng danh tiếng, được liệt kê trong các danh mục chính, chủ động theo dõi khách hàng tiềm năng.</td>
      </tr>
      <tr>
        <td class="border border-slate-300 px-3 py-2 text-sm text-slate-700">5. Yêu cầu chào hàng</td>
        <td class="border border-slate-300 px-3 py-2 text-sm text-slate-700">Mời các nhà cung cấp chất lượng đệ trình đề xuất chào hàng. Yêu cầu đề xuất chi tiết/thuyết trình cho hạng mục phức tạp/đắt tiền.</td>
        <td class="border border-slate-300 px-3 py-2 text-sm text-slate-700">Phát triển kỹ năng nghiên cứu, viết và thuyết trình đề xuất hiệu quả. Đề xuất phải mang tính marketing, tạo niềm tin, làm nổi bật doanh nghiệp.</td>
      </tr>
      <tr>
        <td class="border border-slate-300 px-3 py-2 text-sm text-slate-700">6. Lựa chọn nhà cung cấp</td>
        <td class="border border-slate-300 px-3 py-2 text-sm text-slate-700">Thành viên trung tâm mua xem xét đề xuất, chọn một hoặc nhiều nhà cung cấp dựa trên các đặc điểm mong muốn (chất lượng, giá, giao hàng, đạo đức...). Có thể thương lượng.</td>
        <td class="border border-slate-300 px-3 py-2 text-sm text-slate-700">Nhấn mạnh các điểm mạnh phù hợp với tiêu chí của khách hàng, xây dựng uy tín, thể hiện cam kết đối tác lâu dài.</td>
      </tr>
      <tr>
        <td class="border border-slate-300 px-3 py-2 text-sm text-slate-700">7. Soạn thảo đơn đặt hàng</td>
        <td class="border border-slate-300 px-3 py-2 text-sm text-slate-700">Soạn đơn đặt hàng cuối cùng (đặc điểm kỹ thuật, số lượng, giao hàng, bảo hành...). Sử dụng <strong><span class="text-rose-600">hợp đồng khung (blanket contract)</span></strong> hoặc <strong><span class="text-rose-600">VMI (Vendor-Managed Inventory)</span></strong> cho một số trường hợp.</td>
        <td class="border border-slate-300 px-3 py-2 text-sm text-slate-700">Đảm bảo các điều khoản rõ ràng, hỗ trợ triển khai hợp đồng khung hoặc VMI nếu phù hợp để tăng cường hợp tác và hiệu quả.</td>
      </tr>
      <tr>
        <td class="border border-slate-300 px-3 py-2 text-sm text-slate-700">8. Đánh giá việc thực hiện</td>
        <td class="border border-slate-300 px-3 py-2 text-sm text-slate-700">Bên mua xem xét lại việc thực hiện của nhà cung cấp, thu thập phản hồi từ người sử dụng. Quyết định mua tiếp, điều chỉnh hoặc hủy bỏ.</td>
        <td class="border border-slate-300 px-3 py-2 text-sm text-slate-700">Theo dõi sát sao hiệu suất, thu thập phản hồi chủ động, thực hiện các điều chỉnh cần thiết để đảm bảo sự hài lòng liên tục, duy trì mối quan hệ.</td>
      </tr>
    </tbody>
  </table>
</div>
    `
  ]),
};