import { PageData } from '../../types';
import { cleanParagraphs } from '../dataUtils';

const CHAPTER_6_TITLE = "Chương 6: Thị Trường Doanh Nghiệp và Hành Vi Của Khách Hàng Doanh Nghiệp";

export const chap6SecIPageData: PageData = {
  id: 'chap6-secI',
  chapterTitle: CHAPTER_6_TITLE,
  pageTitle: "I. Tổng Quan về Thị Trường Doanh Nghiệp và Hành Vi Mua Của Khách Hàng Doanh Nghiệp",
  paragraphs: cleanParagraphs([
    "Để hiểu rõ bản chất của marketing B2B, điều cần thiết trước tiên là phải xác định rõ các khái niệm nền tảng và nhận diện những đặc điểm khác biệt cơ bản của thị trường này so với thị trường người tiêu dùng.",
    "<strong>A. Định nghĩa Thị trường Doanh nghiệp và Hành vi Mua của Khách hàng Doanh nghiệp</strong>",
    "Theo Kotler và Armstrong, <strong><span class=\"text-rose-600\">hành vi mua của khách hàng doanh nghiệp (business buyer behavior)</span></strong> được định nghĩa là hành vi mua của các tổ chức mua sản phẩm và dịch vụ nhằm mục đích sử dụng trong quá trình sản xuất ra các sản phẩm và dịch vụ khác để bán, cho thuê hoặc cung ứng cho các đối tượng khác. Định nghĩa này cũng bao hàm hành vi của các doanh nghiệp bán buôn và bán lẻ khi họ mua hàng hóa với mục đích bán lại hoặc cho thuê lại để thu lợi nhuận.1 Song song đó, <strong><span class=\"text-rose-600\">quá trình ra quyết định mua của doanh nghiệp (business buying process)</span></strong> được mô tả là một chuỗi các bước mà qua đó các doanh nghiệp xác định những sản phẩm và dịch vụ mà tổ chức của họ cần mua, sau đó tiến hành tìm kiếm, đánh giá và cuối cùng là lựa chọn giữa các nhà cung cấp và thương hiệu khác nhau trên thị trường.1",
    "Một điểm quan trọng được nhấn mạnh là thị trường doanh nghiệp có quy mô vô cùng lớn. Thực tế, thị trường này liên quan đến nhiều tiền bạc và nhiều mặt hàng hơn đáng kể so với thị trường người tiêu dùng. Để minh họa, 1 đã sử dụng ví dụ về chuỗi các giao dịch B2B phức tạp liên quan đến việc sản xuất và bán một bộ lốp xe của Goodyear. Quá trình này bắt đầu từ việc nhiều nhà cung cấp bán cao su, thép, dụng cụ và các hàng hóa cần thiết khác cho Goodyear. Sau đó, Goodyear lại bán sản phẩm lốp xe hoàn thiện cho các nhà bán lẻ (một giao dịch B2B khác), và các nhà bán lẻ này mới bán cho người tiêu dùng cuối cùng. Ngoài ra, Goodyear còn bán lốp xe trực tiếp cho các nhà sản xuất ô tô làm thiết bị đầu vào và cho các doanh nghiệp sử dụng cho đội xe của họ.1",
    "Việc nắm vững các định nghĩa này là nền tảng cơ bản. Nó giúp phân định rõ ràng phạm vi và đối tượng của marketing B2B. Sự phân biệt giữa hành vi mua (một khái niệm bao trùm các yếu tố tâm lý, xã hội, tổ chức) và quá trình ra quyết định mua (một chuỗi các hành động cụ thể, có trình tự) cho phép các nhà marketing B2B xác định đúng đắn các điểm tiếp xúc và các yếu tố cần tác động để đạt được hiệu quả. Quy mô khổng lồ của thị trường B2B không chỉ phản ánh tầm quan trọng kinh tế của nó mà còn cho thấy sự đa dạng và phức tạp của các cơ hội cũng như thách thức mà các doanh nghiệp hoạt động trong lĩnh vực này phải đối mặt.",
    "<strong>B. So sánh Thị trường Doanh nghiệp và Thị trường Người tiêu dùng</strong>",
    "Mặc dù cả thị trường doanh nghiệp và thị trường người tiêu dùng đều có sự tham gia của những cá nhân hoặc nhóm người đóng vai trò mua hàng và ra quyết định mua nhằm thỏa mãn một nhu cầu nào đó, 1 khẳng định rằng thị trường doanh nghiệp khác biệt một cách đáng kể so với thị trường người tiêu dùng ở nhiều khía cạnh cơ bản. Những khác biệt này bao gồm: cấu trúc và nhu cầu thị trường, bản chất của đơn vị mua, các loại quyết định mua và bản thân quá trình ra quyết định mua.1 Việc nhận diện và thấu hiểu sâu sắc từng điểm khác biệt này là yếu tố then chốt, giúp các nhà marketing B2B xây dựng được những chiến lược tiếp cận thị trường thực sự hiệu quả, tránh được việc áp dụng một cách máy móc và thiếu phù hợp các nguyên tắc của marketing B2C vào một môi trường kinh doanh có những đặc thù riêng biệt.",
    "<strong>Cấu trúc và Nhu cầu Thị trường</strong>",
    "Sự khác biệt về cấu trúc và nhu cầu thị trường là một trong những điểm phân biệt rõ nét nhất giữa B2B và B2C.",
    "<strong><span class=\"text-rose-600\">Ít người mua hơn nhưng quy mô lớn hơn:</span></strong> Một đặc điểm nổi bật của thị trường B2B là các nhà marketing thường giao dịch với một số lượng người mua ít hơn đáng kể so với thị trường tiêu dùng. Tuy nhiên, mỗi người mua trong thị trường B2B lại có quy mô giao dịch lớn hơn rất nhiều. Thậm chí, trong một thị trường doanh nghiệp có quy mô lớn, chỉ một số ít người mua cũng đã chiếm phần lớn tổng lượng mua bán.1 Ví dụ được đưa ra là Goodyear: khi bán lốp xe thay thế cho người tiêu dùng cuối cùng, thị trường tiềm năng của họ bao gồm hàng triệu chủ sở hữu xe. Ngược lại, trên thị trường doanh nghiệp, Goodyear lại phụ thuộc chủ yếu vào các đơn đặt hàng từ một số ít các nhà sản xuất ô tô lớn.1",
    "<strong><span class=\"text-rose-600\">Cầu phái sinh (Derived Demand):</span></strong> Đây là một khái niệm nền tảng và có ý nghĩa chiến lược trong marketing B2B. Cầu của thị trường doanh nghiệp về cơ bản là xuất phát từ, hay \"phái sinh\" từ, cầu đối với các sản phẩm tiêu dùng. Nói cách khác, nếu nhu cầu của người tiêu dùng cuối cùng đối với một sản phẩm nào đó giảm sút, thì nhu cầu đối với tất cả các hàng hóa và dịch vụ doanh nghiệp được sử dụng để sản xuất ra sản phẩm đó cũng sẽ theo đó mà suy giảm.11 minh họa điều này qua ví dụ về cầu thị trường đối với vải Gore-Tex, vốn phụ thuộc vào nhu cầu của người tiêu dùng mua các loại trang phục ngoài trời được làm từ loại vải này. Tương tự, nhu cầu đối với kính Gorilla của Corning chỉ tồn tại khi người tiêu dùng mua máy tính xách tay, máy tính bảng và điện thoại thông minh từ các nhà sản xuất như Apple, Samsung, Lenovo, Dell, HP, Sony và Microsoft – những hãng sử dụng loại kính này.1 Chính vì đặc điểm này, các nhà marketing B2B đôi khi thấy cần thiết phải quảng bá sản phẩm của họ trực tiếp đến người tiêu dùng cuối cùng, nhằm mục đích thúc đẩy cầu phái sinh. Chiến dịch marketing \"cứng, nhưng đẹp\" (Tough yet beautiful) của Corning nhắm tới người dùng cuối cùng, thuyết phục họ rằng việc lựa chọn sản phẩm kỹ thuật số với màn hình làm bằng kính Gorilla là hợp lý, từ đó mang lại lợi ích cho cả Corning và các thương hiệu đối tác sử dụng loại kính này.1",
    "<strong><span class=\"text-rose-600\">Cầu không co giãn (Inelastic Demand):</span></strong> Tổng cầu đối với nhiều sản phẩm và dịch vụ doanh nghiệp thường biểu hiện tính không co giãn, nghĩa là ít bị ảnh hưởng bởi sự thay đổi về giá, đặc biệt là trong ngắn hạn. Một ví dụ điển hình là việc giảm giá nguyên liệu da sẽ không nhất thiết làm cho các doanh nghiệp sản xuất giày mua nhiều nguyên liệu đó hơn, trừ khi việc giảm giá này dẫn đến giảm giá thành của giày thành phẩm, từ đó kích thích nhu cầu của người tiêu dùng đối với giày.1",
    "<strong><span class=\"text-rose-600\">Cầu biến động mạnh (Fluctuating Demand):</span></strong> Nhu cầu thị trường đối với nhiều sản phẩm và dịch vụ doanh nghiệp có xu hướng thay đổi nhiều hơn và nhanh hơn so với nhu cầu đối với hàng hóa và dịch vụ tiêu dùng. Một sự thay đổi, dù là nhỏ, trong nhu cầu của người tiêu dùng cũng có thể dẫn đến một sự thay đổi lớn và đột ngột hơn nhiều trong nhu cầu trên thị trường doanh nghiệp.1",
    "Những đặc điểm về cấu trúc và nhu cầu thị trường này mang những hàm ý quan trọng đối với chiến lược marketing B2B. Việc có ít khách hàng lớn hơn đòi hỏi sự tập trung vào xây dựng và duy trì các mối quan hệ đối tác lâu dài, cá nhân hóa và ổn định, thay vì các chiến dịch quảng bá đại chúng. Đặc điểm cầu phái sinh buộc các nhà marketing B2B không chỉ hiểu rõ khách hàng trực tiếp của mình mà còn phải theo dõi sát sao, phân tích và dự báo các xu hướng của thị trường tiêu dùng cuối cùng mà khách hàng của họ phục vụ. Điều này có thể dẫn đến việc các công ty B2B cần phát triển năng lực nghiên cứu thị trường B2C hoặc thậm chí tham gia vào các hoạt động marketing B2B2C, như trường hợp của Corning, để chủ động tác động đến nhu cầu cuối cùng. Tính không co giãn và biến động mạnh của cầu đòi hỏi các doanh nghiệp B2B phải có khả năng dự báo nhu cầu chính xác, quản lý hàng tồn kho một cách linh hoạt và xây dựng các chiến lược quản lý rủi ro hiệu quả trong toàn bộ chuỗi cung ứng của mình.",
    "<strong>Bản chất của Đơn vị Mua (Nature of the Buying Unit)</strong>",
    "Bản chất của đơn vị mua trong thị trường B2B cũng thể hiện những khác biệt rõ rệt so với thị trường B2C.",
    "So với hành vi mua của người tiêu dùng cá nhân, việc mua hàng của doanh nghiệp thường liên quan đến nhiều người tham gia vào quá trình ra quyết định hơn. Đồng thời, nỗ lực mua hàng cũng mang tính chuyên nghiệp hơn một cách rõ rệt.1",
    "Việc mua hàng của các doanh nghiệp thường được thực hiện bởi các nhân viên mua hàng được đào tạo chuyên nghiệp, những người đã dành cả sự nghiệp của mình để học hỏi và hoàn thiện kỹ năng mua hàng sao cho có lợi nhất. Khi quy mô và mức độ phức tạp của việc mua bán càng tăng, thì càng có nhiều khả năng sẽ có nhiều cá nhân và bộ phận khác nhau trong tổ chức tham gia vào quá trình ra quyết định. Các <strong><span class=\"text-rose-600\">trung tâm mua hàng (buying centers)</span></strong> của doanh nghiệp thường bao gồm các chuyên gia kỹ thuật và thậm chí cả các nhà quản lý cấp cao.1",
    "Thực tế này đặt ra một thách thức mới cho các chuyên gia marketing B2B: họ phải đối mặt với một thế hệ các nhà quản trị cung ứng (supply managers) ngày càng có trình độ cao hơn và được đào tạo tốt hơn. Do đó, các doanh nghiệp B2B buộc phải đầu tư vào việc đào tạo bài bản cho đội ngũ chuyên gia marketing và nhân viên bán hàng của mình, trang bị cho họ đủ kiến thức và kỹ năng để có thể giao tiếp và tương tác hiệu quả với những người mua chuyên nghiệp và có trình độ này.1",
    "Sự tham gia của nhiều người và tính chuyên nghiệp cao của đơn vị mua đòi hỏi các nhà marketing B2B phải phát triển các thông điệp marketing đa chiều, có khả năng thuyết phục được nhiều đối tượng khác nhau với những mối quan tâm và tiêu chí đánh giá riêng biệt trong cùng một tổ chức khách hàng. Đội ngũ bán hàng B2B không chỉ cần am hiểu sâu sắc về sản phẩm và ngành nghề của mình mà còn phải sở hữu kỹ năng đàm phán, thuyết trình và xây dựng mối quan hệ ở cấp độ chuyên nghiệp cao.",
    "<strong>Các loại Quyết định và Quá trình Ra quyết định Mua</strong>",
    "Các loại quyết định và quy trình ra quyết định mua trong thị trường B2B cũng mang những đặc trưng riêng biệt.",
    "<strong><span class=\"text-rose-600\">Quyết định phức tạp hơn:</span></strong> Người mua doanh nghiệp thường phải đối mặt với các quyết định mua có tính phức tạp cao hơn nhiều so với người mua tiêu dùng. Các giao dịch mua của doanh nghiệp thường liên quan đến số tiền lớn, đòi hỏi những cân nhắc sâu sắc về các yếu tố kinh tế và kỹ thuật, cũng như sự tương tác và phối hợp giữa nhiều cá nhân ở các cấp độ và bộ phận khác nhau trong tổ chức của người mua.1",
    "<strong><span class=\"text-rose-600\">Quá trình dài hơn và chính thức hơn:</span></strong> Do tính phức tạp của các quyết định, quá trình mua của doanh nghiệp cũng có xu hướng kéo dài hơn và mang tính chính thức, quy chuẩn hóa cao hơn. Việc mua hàng quy mô lớn của các doanh nghiệp thường yêu cầu các quy cách sản phẩm được xác định một cách chi tiết, các lệnh đặt hàng phải được thực hiện bằng văn bản, việc tìm kiếm và đánh giá nhà cung cấp phải được tiến hành một cách cẩn thận, và các đề xuất mua hàng phải được phê duyệt chính thức qua nhiều cấp.1",
    "<strong><span class=\"text-rose-600\">Sự phụ thuộc lẫn nhau giữa người mua và người bán:</span></strong> Một đặc điểm quan trọng khác là trong quá trình mua của doanh nghiệp, người mua và người bán thường có mức độ phụ thuộc lẫn nhau cao hơn. Các nhà marketing trên thị trường B2B không chỉ đơn thuần bán sản phẩm mà còn phải lên kế hoạch và làm việc chặt chẽ với khách hàng trong tất cả các giai đoạn của quá trình mua. Điều này bao gồm việc giúp khách hàng xác định vấn đề của họ, cùng họ tìm ra giải pháp tối ưu, và cung cấp sự hỗ trợ cần thiết cho các hoạt động sau bán hàng.1 Ví dụ điển hình là bộ phận Cocoa & Chocolate của tập đoàn Cargill. Họ không chỉ bán các sản phẩm ca cao và sô-cô-la cho các khách hàng doanh nghiệp lớn như Mars và Mondelez, mà còn hợp tác mật thiết với những khách hàng này. Cargill sử dụng khả năng chuyên môn sâu rộng của mình để trợ giúp khách hàng sử dụng các sản phẩm của Cargill một cách hiệu quả hơn trong việc phục vụ khách hàng của chính họ, từ đó mang lại lợi nhuận nhiều hơn. Điều này bao gồm việc giúp khách hàng cập nhật các xu hướng ẩm thực mới nhất, hỗ trợ cá nhân hóa việc phát triển sản phẩm, và giải quyết các thách thức trong ứng dụng sản phẩm.1",
    "<strong><span class=\"text-rose-600\">Phát triển mạng lưới nhà cung cấp (Supplier Development):</span></strong> Trong những năm gần đây, mối quan hệ giữa hầu hết khách hàng và các nhà cung cấp đã có sự chuyển biến rõ rệt, từ chỗ hoàn toàn mang tính đối đầu sang gần gũi và thân thiết hơn, như trường hợp của Cargill. Thực tế, rất nhiều khách hàng doanh nghiệp hiện nay đang tích cực thực hiện việc \"phát triển mạng lưới nhà cung cấp\" – một cách tiếp cận có hệ thống nhằm xây dựng và phát triển mạng lưới các đối tác cung ứng đáng tin cậy, đảm bảo nguồn cung ổn định cho những sản phẩm và nguyên liệu mà họ sử dụng để tạo ra sản phẩm của mình hoặc bán lại cho người khác. Walmart là một ví dụ tiêu biểu; họ không có \"Phòng mua hàng\" theo nghĩa truyền thống mà thay vào đó là \"Phòng phát triển mạng lưới cung ứng\", phản ánh sự chủ động trong việc xây dựng và quản lý mối quan hệ với các đối tác cung ứng.1",
    "Tính phức tạp và quy trình chính thức của việc mua hàng B2B đòi hỏi các nhà marketing phải có sự kiên nhẫn, cung cấp thông tin một cách chi tiết và minh bạch, đồng thời xây dựng lòng tin với khách hàng một cách có hệ thống và bài bản. Sự phụ thuộc lẫn nhau và xu hướng phát triển mạng lưới nhà cung cấp cho thấy một sự chuyển dịch quan trọng trong tư duy marketing B2B: từ việc tập trung vào các giao dịch mua bán đơn lẻ, ngắn hạn sang việc xây dựng các mối quan hệ đối tác chiến lược, lâu dài, nơi giá trị được đồng tạo ra và chia sẻ giữa người mua và người bán.Một khía cạnh đáng chú ý là sự chuyên nghiệp hóa ngày càng tăng của chức năng mua hàng trong các tổ chức. Điều này, kết hợp với xu hướng xây dựng quan hệ đối tác, cho thấy các quyết định mua B2B ngày càng ít dựa trên các yếu tố giao dịch thuần túy (như giá thấp nhất) mà thay vào đó, các yếu tố như khả năng của nhà cung cấp trong việc đóng góp vào mục tiêu chiến lược dài hạn của bên mua, khả năng hợp tác, đổi mới và đồng tạo giá trị ngày càng được coi trọng. Các nhà cung cấp B2B do đó phải liên tục nâng cao năng lực, không chỉ về chất lượng sản phẩm/dịch vụ mà còn về khả năng tư vấn, hỗ trợ và đồng hành cùng sự phát triển của khách hàng, như cách Cargill đã làm.Tuy nhiên, một mô hình ẩn có thể quan sát thấy là sự căng thẳng tiềm ẩn giữa tính chính thức, quy trình kéo dài của việc mua B2B truyền thống và nhu cầu ngày càng tăng về sự nhanh nhạy, linh hoạt trong môi trường kinh doanh hiện đại, biến đổi nhanh chóng. Trong khi quy trình mua B2B được mô tả là \"dài hơn và chính thống hơn\" với nhiều thủ tục phức tạp 1, thì môi trường kinh doanh ngày nay lại đòi hỏi các công ty phải có khả năng phản ứng nhanh chóng với những thay đổi của thị trường và công nghệ. Sự mâu thuẫn này tạo ra một thách thức không nhỏ: làm thế nào để các tổ chức có thể duy trì tính kỷ luật, cẩn trọng và toàn diện của quy trình mua B2B trong khi vẫn đảm bảo được tốc độ và sự linh hoạt cần thiết để không bỏ lỡ các cơ hội hoặc đối phó kịp thời với các mối đe dọa. Điều này có thể thúc đẩy các doanh nghiệp B2B tìm kiếm các giải pháp công nghệ, như mua hàng điện tử (e-procurement) sẽ được thảo luận sau, để hợp lý hóa và tăng tốc quy trình, hoặc phát triển các mô hình quan hệ đối tác linh hoạt hơn với các nhà cung cấp chiến lược, cho phép ra quyết định nhanh hơn đối với một số loại hình mua sắm nhất định.",
    `
<div class="overflow-x-auto py-2">
  <p class="font-semibold text-lg my-3">Bảng 1: So sánh Thị trường Doanh nghiệp và Thị trường Người tiêu dùng</p>
  <table class="min-w-full w-full table-auto border-collapse border border-slate-400 prose-sm">
    <thead class="bg-slate-50">
      <tr>
        <th class="border border-slate-300 px-3 py-2 text-left text-xs font-semibold text-slate-700 uppercase tracking-wider">Đặc điểm so sánh</th>
        <th class="border border-slate-300 px-3 py-2 text-left text-xs font-semibold text-slate-700 uppercase tracking-wider">Thị trường Doanh nghiệp (B2B)</th>
        <th class="border border-slate-300 px-3 py-2 text-left text-xs font-semibold text-slate-700 uppercase tracking-wider">Thị trường Người tiêu dùng (B2C)</th>
      </tr>
    </thead>
    <tbody class="bg-white divide-y divide-slate-200">
      <tr>
        <td class="border border-slate-300 px-3 py-2 text-sm text-slate-700">Cấu trúc thị trường</td>
        <td class="border border-slate-300 px-3 py-2 text-sm text-slate-700">Ít người mua hơn, tập trung về mặt địa lý; Quy mô mua lớn hơn.1</td>
        <td class="border border-slate-300 px-3 py-2 text-sm text-slate-700">Nhiều người mua hơn, phân tán về mặt địa lý; Quy mô mua nhỏ hơn.</td>
      </tr>
      <tr>
        <td class="border border-slate-300 px-3 py-2 text-sm text-slate-700">Đặc điểm nhu cầu</td>
        <td class="border border-slate-300 px-3 py-2 text-sm text-slate-700">Cầu phái sinh (từ cầu tiêu dùng); Cầu ít co giãn với giá trong ngắn hạn; Cầu biến động mạnh và nhanh hơn.1</td>
        <td class="border border-slate-300 px-3 py-2 text-sm text-slate-700">Cầu trực tiếp; Cầu co giãn hơn với giá; Cầu ổn định hơn.</td>
      </tr>
      <tr>
        <td class="border border-slate-300 px-3 py-2 text-sm text-slate-700">Đơn vị mua</td>
        <td class="border border-slate-300 px-3 py-2 text-sm text-slate-700">Liên quan đến nhiều người ra quyết định hơn (trung tâm mua); Nỗ lực mua mang tính chuyên nghiệp hơn, có quy trình chính thức.1</td>
        <td class="border border-slate-300 px-3 py-2 text-sm text-slate-700">Thường là cá nhân hoặc hộ gia đình; Quyết định ít chuyên nghiệp hơn, quy trình ít chính thức hơn.</td>
      </tr>
      <tr>
        <td class="border border-slate-300 px-3 py-2 text-sm text-slate-700">Loại quyết định</td>
        <td class="border border-slate-300 px-3 py-2 text-sm text-slate-700">Các quyết định mua phức tạp hơn, liên quan đến lượng tiền lớn, cân nhắc kỹ thuật và kinh tế phức tạp.1</td>
        <td class="border border-slate-300 px-3 py-2 text-sm text-slate-700">Các quyết định mua thường đơn giản hơn, ít yếu tố kỹ thuật phức tạp.</td>
      </tr>
      <tr>
        <td class="border border-slate-300 px-3 py-2 text-sm text-slate-700">Quy trình quyết định</td>
        <td class="border border-slate-300 px-3 py-2 text-sm text-slate-700">Quá trình mua thường dài hơn, chính thức hơn, đòi hỏi quy cách chi tiết, lệnh đặt hàng văn bản, nghiên cứu nhà cung cấp cẩn thận.1</td>
        <td class="border border-slate-300 px-3 py-2 text-sm text-slate-700">Quá trình mua thường ngắn hơn, ít chính thức hơn.</td>
      </tr>
      <tr>
        <td class="border border-slate-300 px-3 py-2 text-sm text-slate-700">Mối quan hệ người mua-người bán</td>
        <td class="border border-slate-300 px-3 py-2 text-sm text-slate-700">Người mua và người bán thường phụ thuộc nhau nhiều hơn, có xu hướng xây dựng mối quan hệ đối tác lâu dài, hợp tác chặt chẽ (ví dụ: phát triển mạng lưới nhà cung cấp).1</td>
        <td class="border border-slate-300 px-3 py-2 text-sm text-slate-700">Mối quan hệ thường mang tính giao dịch hơn, ít phụ thuộc lẫn nhau.</td>
      </tr>
    </tbody>
  </table>
</div>
    `
  ]),
};
